// This file is auto-generated by @hey-api/openapi-ts

export const StatusResponseSchema = {
    type: 'object',
    properties: {
        status: {
            type: 'string'
        },
        uptime: {
            type: 'number'
        },
        version: {
            type: 'string'
        },
        timestamp: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['status', 'uptime', 'version', 'timestamp']
} as const

export const ErrorResponseSchema = {
    type: 'object',
    properties: {
        success: {
            type: 'boolean',
            enum: [false],
            description: 'Always false for error responses'
        },
        message: {
            type: 'string',
            description: 'Error message describing what went wrong'
        },
        error: {
            nullable: true,
            description: 'Optional additional error details or context'
        }
    },
    required: ['success', 'message']
} as const

export const SnapshotFrequencyEnumSchema = {
    type: 'string',
    enum: ['NONE', 'DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'SEMIANNUAL', 'ANNUAL']
} as const

export const CurrencyEnumSchema = {
    type: 'string',
    enum: [
        'USD',
        'EUR',
        'GBP',
        'JPY',
        'CNY',
        'INR',
        'AUD',
        'CAD',
        'CHF',
        'SEK',
        'NZD',
        'MXN',
        'SGD',
        'HKD',
        'NOK',
        'KRW',
        'TRY',
        'UNKNOWN'
    ]
} as const

export const LanguageEnumSchema = {
    type: 'string',
    enum: [
        'EN',
        'ES',
        'FR',
        'DE',
        'IT',
        'PT',
        'NL',
        'RU',
        'ZH',
        'JA',
        'KO',
        'AR',
        'HI',
        'TH',
        'VI',
        'TR',
        'PL',
        'CS',
        'HU',
        'RO',
        'BG',
        'HR',
        'SK',
        'SL',
        'ET',
        'LV',
        'LT',
        'MT',
        'FI',
        'SV',
        'DA',
        'NO',
        'IS',
        'EL',
        'HE',
        'FA',
        'UR',
        'BN',
        'TA',
        'TE',
        'ML',
        'KN',
        'GU',
        'MR',
        'PA',
        'OR',
        'AS',
        'NE',
        'SI',
        'MY',
        'KH',
        'LO',
        'KA',
        'AM',
        'TI',
        'SW',
        'ZU',
        'AF',
        'XH',
        'ST',
        'TN',
        'SS',
        'VE',
        'TS',
        'NR',
        'IG',
        'YO',
        'HA',
        'FF',
        'WO',
        'BM',
        'DY',
        'SN'
    ]
} as const

export const DateFormatEnumSchema = {
    type: 'string',
    enum: [
        'DD_MM_YYYY',
        'MM_DD_YYYY',
        'YYYY_MM_DD',
        'DD_MM_YY',
        'MM_DD_YY',
        'YY_MM_DD',
        'DD_MMMM_YYYY',
        'MMMM_DD_YYYY',
        'YYYY_MMMM_DD'
    ]
} as const

export const TimezoneEnumSchema = {
    type: 'string',
    enum: [
        'AFRICA_ALGIERS',
        'AFRICA_CAIRO',
        'AFRICA_CASABLANCA',
        'AFRICA_HARARE',
        'AFRICA_JOHANNESBURG',
        'AFRICA_MONROVIA',
        'AFRICA_NAIROBI',
        'AFRICA_WEST_CENTRAL',
        'AMERICA_ARGENTINA_BUENOS_AIRES',
        'AMERICA_BOGOTA',
        'AMERICA_CARACAS',
        'AMERICA_CHICAGO',
        'AMERICA_CHIHUAHUA',
        'AMERICA_DENVER',
        'AMERICA_GUATEMALA',
        'AMERICA_GUYANA',
        'AMERICA_HALIFAX',
        'AMERICA_INDIANA_INDIANAPOLIS',
        'AMERICA_JUNEAU',
        'AMERICA_LA_PAZ',
        'AMERICA_LIMA',
        'AMERICA_QUITO',
        'AMERICA_LOS_ANGELES',
        'AMERICA_MAZATLAN',
        'AMERICA_MEXICO_CITY',
        'AMERICA_GUADALAJARA',
        'AMERICA_MONTERREY',
        'AMERICA_MONTEVIDEO',
        'AMERICA_NEW_YORK',
        'AMERICA_PHOENIX',
        'AMERICA_PUERTO_RICO',
        'AMERICA_REGINA',
        'AMERICA_SANTIAGO',
        'AMERICA_SAO_PAULO',
        'AMERICA_ST_JOHNS',
        'AMERICA_TIJUANA',
        'ASIA_ALMATY',
        'ASIA_ASTANA',
        'ASIA_BAGHDAD',
        'ASIA_BAKU',
        'ASIA_BANGKOK',
        'ASIA_CHENNAI',
        'ASIA_HANOI',
        'ASIA_CHONGQING',
        'ASIA_COLOMBO',
        'ASIA_DHAKA',
        'ASIA_HONG_KONG',
        'ASIA_IRKUTSK',
        'ASIA_JAKARTA',
        'ASIA_JERUSALEM',
        'ASIA_KABUL',
        'ASIA_KAMCHATKA',
        'ASIA_KARACHI',
        'ASIA_ISLAMABAD',
        'ASIA_KATHMANDU',
        'ASIA_KOLKATA',
        'ASIA_MUMBAI',
        'ASIA_NEW_DELHI',
        'ASIA_KRASNOYARSK',
        'ASIA_KUALA_LUMPUR',
        'ASIA_KUWAIT',
        'ASIA_MAGADAN',
        'ASIA_MUSCAT',
        'ASIA_ABU_DHABI',
        'ASIA_NOVOSIBIRSK',
        'ASIA_RIYADH',
        'ASIA_SEOUL',
        'ASIA_SHANGHAI',
        'ASIA_SINGAPORE',
        'ASIA_SREDNEKOLYMSK',
        'ASIA_TAIPEI',
        'ASIA_TASHKENT',
        'ASIA_TBILISI',
        'ASIA_TEHRAN',
        'ASIA_TOKYO',
        'ASIA_OSAKA',
        'ASIA_SAPPORO',
        'ASIA_ULAANBAATAR',
        'ASIA_URUMQI',
        'ASIA_VLADIVOSTOK',
        'ASIA_YAKUTSK',
        'ASIA_YEKATERINBURG',
        'ASIA_YEREVAN',
        'ATLANTIC_AZORES',
        'ATLANTIC_CAPE_VERDE',
        'ATLANTIC_SOUTH_GEORGIA',
        'AUSTRALIA_ADELAIDE',
        'AUSTRALIA_BRISBANE',
        'AUSTRALIA_CANBERRA',
        'AUSTRALIA_DARWIN',
        'AUSTRALIA_HOBART',
        'AUSTRALIA_MELBOURNE',
        'AUSTRALIA_PERTH',
        'AUSTRALIA_SYDNEY',
        'ETC_GMT_PLUS_12',
        'ETC_UTC',
        'EUROPE_AMSTERDAM',
        'EUROPE_ATHENS',
        'EUROPE_BELGRADE',
        'EUROPE_BERN',
        'EUROPE_BERLIN',
        'EUROPE_BRATISLAVA',
        'EUROPE_BRUSSELS',
        'EUROPE_BUCHAREST',
        'EUROPE_BUDAPEST',
        'EUROPE_COPENHAGEN',
        'EUROPE_DUBLIN',
        'EUROPE_HELSINKI',
        'EUROPE_ISTANBUL',
        'EUROPE_KALININGRAD',
        'EUROPE_LISBON',
        'EUROPE_LJUBLJANA',
        'EUROPE_LONDON',
        'EUROPE_EDINBURGH',
        'EUROPE_MADRID',
        'EUROPE_MINSK',
        'EUROPE_MOSCOW',
        'EUROPE_ST_PETERSBURG',
        'EUROPE_PARIS',
        'EUROPE_PRAGUE',
        'EUROPE_RIGA',
        'EUROPE_ROME',
        'EUROPE_SAMARA',
        'EUROPE_SARAJEVO',
        'EUROPE_SKOPJE',
        'EUROPE_SOFIA',
        'EUROPE_STOCKHOLM',
        'EUROPE_TALLINN',
        'EUROPE_VIENNA',
        'EUROPE_VILNIUS',
        'EUROPE_VOLGOGRAD',
        'EUROPE_WARSAW',
        'EUROPE_ZAGREB',
        'EUROPE_ZURICH',
        'PACIFIC_APIA',
        'PACIFIC_AUCKLAND',
        'PACIFIC_WELLINGTON',
        'PACIFIC_CHATHAM',
        'PACIFIC_FAKAOFO',
        'PACIFIC_FIJI',
        'PACIFIC_GUADALCANAL',
        'PACIFIC_GUAM',
        'PACIFIC_HONOLULU',
        'PACIFIC_MAJURO',
        'PACIFIC_MIDWAY',
        'PACIFIC_NOUMEA',
        'PACIFIC_PAGO_PAGO',
        'PACIFIC_PORT_MORESBY',
        'PACIFIC_TONGATAPU'
    ]
} as const

export const UserPreferencesSchema = {
    type: 'object',
    properties: {
        snapshotFrequency: {
            $ref: '#/components/schemas/SnapshotFrequencyEnum'
        },
        preferredCurrency: {
            $ref: '#/components/schemas/CurrencyEnum'
        },
        preferredLanguage: {
            $ref: '#/components/schemas/LanguageEnum'
        },
        dateFormat: {
            $ref: '#/components/schemas/DateFormatEnum'
        },
        country: {
            $ref: '#/components/schemas/CountriesEnum'
        },
        timezone: {
            $ref: '#/components/schemas/TimezoneEnum'
        }
    },
    required: ['snapshotFrequency', 'preferredCurrency', 'preferredLanguage', 'dateFormat', 'country', 'timezone']
} as const

export const UserSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string',
            minLength: 1
        },
        surname: {
            type: 'string',
            minLength: 1
        },
        email: {
            type: 'string',
            format: 'email'
        },
        emailVerified: {
            type: 'boolean'
        },
        onBoardingStep: {
            $ref: '#/components/schemas/OnBoardingStepEnum'
        },
        onBoardingAt: {
            type: 'string',
            nullable: true
        },
        image: {
            type: 'string',
            nullable: true,
            format: 'uri'
        },
        createdAt: {
            type: 'string'
        },
        updatedAt: {
            type: 'string'
        },
        snapshotFrequency: {
            $ref: '#/components/schemas/SnapshotFrequencyEnum'
        },
        preferredCurrency: {
            $ref: '#/components/schemas/CurrencyEnum'
        },
        preferredLanguage: {
            $ref: '#/components/schemas/LanguageEnum'
        },
        dateFormat: {
            $ref: '#/components/schemas/DateFormatEnum'
        },
        country: {
            $ref: '#/components/schemas/CountriesEnum'
        },
        timezone: {
            $ref: '#/components/schemas/TimezoneEnum'
        }
    },
    required: [
        'id',
        'name',
        'surname',
        'email',
        'emailVerified',
        'onBoardingStep',
        'onBoardingAt',
        'image',
        'createdAt',
        'updatedAt',
        'snapshotFrequency',
        'preferredCurrency',
        'preferredLanguage',
        'dateFormat',
        'country',
        'timezone'
    ]
} as const

export const UserLoginSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            minLength: 1,
            format: 'email'
        },
        password: {
            type: 'string',
            minLength: 6
        }
    },
    required: ['email', 'password']
} as const

export const TransactionSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        action: {
            type: 'string'
        },
        categoryId: {
            type: 'string',
            nullable: true
        },
        subcategoryId: {
            type: 'string',
            nullable: true
        },
        icon: {
            type: 'string',
            nullable: true
        },
        date: {
            type: 'string',
            format: 'date-time'
        },
        note: {
            type: 'string',
            nullable: true
        },
        ignore: {
            type: 'boolean'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        status: {
            type: 'string'
        },
        importId: {
            type: 'string',
            nullable: true
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        },
        amounts: {
            type: 'array',
            items: {
                nullable: true
            }
        },
        media: {
            type: 'array',
            items: {
                nullable: true
            }
        },
        transferId: {
            type: 'string',
            nullable: true
        },
        transferHash: {
            type: 'string',
            nullable: true
        }
    },
    required: [
        'id',
        'userId',
        'title',
        'action',
        'categoryId',
        'subcategoryId',
        'icon',
        'date',
        'note',
        'ignore',
        'createdAt',
        'status',
        'importId',
        'updatedAt',
        'amounts',
        'media',
        'transferId',
        'transferHash'
    ]
} as const

export const TransactionRequestSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        date: {
            type: 'string',
            format: 'date-time'
        },
        action: {
            type: 'string'
        },
        categoryId: {
            type: 'string',
            nullable: true
        },
        subcategoryId: {
            type: 'string',
            nullable: true
        },
        icon: {
            type: 'string',
            nullable: true
        },
        note: {
            type: 'string',
            nullable: true
        },
        ignore: {
            type: 'boolean'
        },
        importId: {
            type: 'string',
            nullable: true
        },
        amounts: {
            type: 'array',
            items: {
                nullable: true
            }
        },
        media: {
            type: 'array',
            items: {
                nullable: true
            }
        },
        transferId: {
            type: 'string',
            nullable: true
        }
    },
    required: ['title', 'date', 'action']
} as const

export const TransactionResponseSchema = {
    type: 'object',
    properties: {
        data: {
            $ref: '#/components/schemas/Transaction'
        }
    },
    required: ['data']
} as const

export const FinancialAccountTypeEnumSchema = {
    type: 'string',
    enum: ['ONLINE_BANK', 'BANK_ACCOUNT', 'CIRCUIT', 'DEPOSIT_BANK', 'BROKER', 'WALLET', 'CASH', 'CREDIT_CARD', 'OTHER']
} as const

export const FinancialAccountSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        balance: {
            type: 'number'
        },
        type: {
            $ref: '#/components/schemas/FinancialAccountTypeEnum'
        },
        logoIcon: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'userId', 'title', 'description', 'balance', 'type', 'logoIcon', 'createdAt', 'updatedAt']
} as const

export const FinancialAccountRequestSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        balance: {
            type: 'number'
        },
        type: {
            $ref: '#/components/schemas/FinancialAccountTypeEnum'
        },
        logoIcon: {
            type: 'string'
        }
    },
    required: ['title', 'description', 'balance', 'type', 'logoIcon']
} as const

export const FinancialAccountResponseSchema = {
    type: 'object',
    properties: {
        data: {
            $ref: '#/components/schemas/FinancialAccount'
        }
    },
    required: ['data']
} as const

export const CategorySchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        description: {
            type: 'string',
            nullable: true
        },
        for: {
            type: 'string'
        },
        logoIcon: {
            type: 'string'
        },
        color: {
            type: 'string'
        },
        subcategories: {
            type: 'array',
            items: {
                nullable: true
            }
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'userId', 'title', 'description', 'for', 'logoIcon', 'color', 'subcategories', 'createdAt']
} as const

export const CategoryRequestSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        description: {
            type: 'string',
            nullable: true
        },
        for: {
            type: 'string'
        },
        logoIcon: {
            type: 'string'
        },
        color: {
            type: 'string'
        },
        subcategories: {
            type: 'array',
            items: {
                nullable: true
            }
        }
    },
    required: ['title', 'description', 'for', 'logoIcon', 'color']
} as const

export const CategoryResponseSchema = {
    allOf: [
        {
            $ref: '#/components/schemas/Category'
        },
        {
            type: 'object',
            properties: {}
        }
    ]
} as const

export const SubcategorySchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        categoryId: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        description: {
            type: 'string',
            nullable: true
        },
        logoIcon: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'categoryId', 'title', 'description', 'logoIcon', 'createdAt']
} as const

export const SubcategoryRequestSchema = {
    type: 'object',
    properties: {
        categoryId: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        description: {
            type: 'string',
            nullable: true
        },
        logoIcon: {
            type: 'string'
        }
    },
    required: ['categoryId', 'title']
} as const

export const SubcategoryResponseSchema = {
    type: 'object',
    properties: {
        data: {
            $ref: '#/components/schemas/Subcategory'
        }
    },
    required: ['data']
} as const

export const SnapshotSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        snapshotDate: {
            type: 'string',
            format: 'date-time'
        },
        note: {
            type: 'string',
            nullable: true
        },
        totalCash: {
            type: 'number'
        },
        totalInvestments: {
            type: 'number'
        },
        totalNetWorth: {
            type: 'number'
        },
        userId: {
            type: 'string'
        }
    },
    required: ['id', 'snapshotDate', 'note', 'totalCash', 'totalInvestments', 'totalNetWorth', 'userId']
} as const

export const SnapshotRequestSchema = {
    type: 'object',
    properties: {
        snapshotDate: {
            type: 'string',
            format: 'date-time'
        },
        note: {
            type: 'string',
            nullable: true
        },
        totalCash: {
            type: 'number'
        },
        totalInvestments: {
            type: 'number'
        },
        totalNetWorth: {
            type: 'number'
        }
    },
    required: ['snapshotDate']
} as const

export const SnapshotResponseSchema = {
    type: 'object',
    properties: {
        data: {
            $ref: '#/components/schemas/Snapshot'
        }
    },
    required: ['data']
} as const

export const SessionSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'userId', 'createdAt', 'updatedAt']
} as const

export const SessionRequestSchema = {
    type: 'object',
    properties: {
        token: {
            type: 'string'
        },
        expiresAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const

export const SessionResponseSchema = {
    type: 'object',
    properties: {
        data: {
            $ref: '#/components/schemas/Session'
        }
    },
    required: ['data']
} as const

export const DashboardLayoutSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        version: {
            type: 'number'
        },
        layout: {
            nullable: true
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'userId', 'version', 'createdAt', 'updatedAt']
} as const

export const DashboardLayoutRequestSchema = {
    type: 'object',
    properties: {
        version: {
            type: 'number'
        },
        layout: {
            nullable: true
        }
    }
} as const

export const DashboardLayoutResponseSchema = {
    type: 'object',
    properties: {
        data: {
            $ref: '#/components/schemas/DashboardLayout'
        }
    },
    required: ['data']
} as const

export const ImportFileSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        importId: {
            type: 'string'
        },
        filename: {
            type: 'string'
        },
        filetype: {
            type: 'string'
        },
        path: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'importId', 'filename', 'filetype', 'path', 'createdAt']
} as const

export const ImportSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        financialAccountId: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        transactions: {
            type: 'array',
            items: {
                nullable: true
            }
        },
        files: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ImportFile'
            }
        }
    },
    required: ['id', 'userId', 'title', 'financialAccountId', 'status', 'createdAt']
} as const

export const ImportRequestSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        financialAccountId: {
            type: 'string'
        },
        files: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    filename: {
                        type: 'string'
                    },
                    filetype: {
                        type: 'string'
                    },
                    path: {
                        type: 'string'
                    }
                },
                required: ['filename', 'filetype', 'path']
            }
        }
    },
    required: ['title', 'financialAccountId']
} as const

export const ImportResponseSchema = {
    type: 'object',
    properties: {
        data: {
            $ref: '#/components/schemas/Import'
        }
    },
    required: ['data']
} as const

export const SubscriptionSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        userId: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        description: {
            type: 'string',
            nullable: true
        },
        amount: {
            type: 'number'
        },
        currency: {
            type: 'string'
        },
        appearanceMode: {
            type: 'string'
        },
        appearanceLogoIcon: {
            type: 'string'
        },
        firstPayment: {
            type: 'string',
            format: 'date-time'
        },
        cycleNumber: {
            type: 'string'
        },
        cyclePeriod: {
            type: 'string'
        },
        rememberPeriod: {
            type: 'string'
        },
        financialAccountId: {
            type: 'string'
        },
        isEnabled: {
            type: 'boolean'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: [
        'id',
        'userId',
        'title',
        'description',
        'amount',
        'currency',
        'appearanceMode',
        'appearanceLogoIcon',
        'firstPayment',
        'cycleNumber',
        'cyclePeriod',
        'rememberPeriod',
        'financialAccountId',
        'isEnabled',
        'createdAt'
    ]
} as const

export const SubscriptionRequestSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        description: {
            type: 'string',
            nullable: true
        },
        amount: {
            type: 'number'
        },
        currency: {
            type: 'string'
        },
        appearanceMode: {
            type: 'string'
        },
        appearanceLogoIcon: {
            type: 'string'
        },
        firstPayment: {
            type: 'string',
            format: 'date-time'
        },
        cycleNumber: {
            type: 'string'
        },
        cyclePeriod: {
            type: 'string'
        },
        rememberPeriod: {
            type: 'string'
        },
        financialAccountId: {
            type: 'string'
        },
        isEnabled: {
            type: 'boolean'
        }
    },
    required: [
        'title',
        'amount',
        'currency',
        'appearanceMode',
        'appearanceLogoIcon',
        'firstPayment',
        'cycleNumber',
        'cyclePeriod',
        'rememberPeriod',
        'financialAccountId'
    ]
} as const

export const SubscriptionResponseSchema = {
    type: 'object',
    properties: {
        data: {
            $ref: '#/components/schemas/Subscription'
        }
    },
    required: ['data']
} as const

export const ReportRequestSchema = {
    type: 'object',
    properties: {
        from: {
            type: 'string',
            format: 'date-time'
        },
        to: {
            type: 'string',
            format: 'date-time'
        },
        type: {
            type: 'string'
        }
    },
    required: ['from', 'to']
} as const

export const ReportResponseSchema = {
    type: 'object',
    properties: {
        reportType: {
            type: 'string'
        },
        totals: {
            type: 'object',
            additionalProperties: {
                type: 'number'
            }
        },
        metadata: {
            nullable: true
        }
    },
    required: ['reportType', 'totals']
} as const

export const UpdateUserSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1
        },
        surname: {
            type: 'string',
            minLength: 1
        },
        email: {
            type: 'string',
            format: 'email'
        },
        country: {
            $ref: '#/components/schemas/CountriesEnum'
        },
        preferredCurrency: {
            $ref: '#/components/schemas/CurrencyEnum'
        },
        preferredLanguage: {
            $ref: '#/components/schemas/LanguageEnum'
        },
        dateFormat: {
            $ref: '#/components/schemas/DateFormatEnum'
        },
        timezone: {
            $ref: '#/components/schemas/TimezoneEnum'
        }
    }
} as const

export const UserSessionSchema = {
    type: 'object',
    properties: {
        session: {
            type: 'object',
            properties: {
                id: {
                    type: 'string',
                    format: 'uuid'
                },
                createdAt: {
                    type: 'string'
                },
                updatedAt: {
                    type: 'string'
                },
                userId: {
                    type: 'string',
                    format: 'uuid'
                },
                expiresAt: {
                    type: 'string'
                },
                token: {
                    type: 'string'
                },
                ipAddress: {
                    type: 'string',
                    nullable: true,
                    format: 'ip'
                },
                userAgent: {
                    type: 'string',
                    nullable: true
                }
            },
            required: ['id', 'createdAt', 'updatedAt', 'userId', 'expiresAt', 'token', 'ipAddress', 'userAgent']
        },
        user: {
            $ref: '#/components/schemas/User'
        }
    },
    required: ['session', 'user']
} as const

export const AssetTypeEnumSchema = {
    type: 'string',
    enum: [
        'STOCK',
        'BOND',
        'ETF',
        'MUTUAL_FUND',
        'CRYPTOCURRENCY',
        'REAL_ESTATE',
        'COLLECTIBLE',
        'PRIVATE_EQUITY',
        'VENTURE_CAPITAL',
        'PRIVATE_DEBT',
        'P2P_LENDING',
        'INSURANCE_POLICY',
        'AGRICULTURAL_LAND',
        'OTHER'
    ]
} as const

export const TransactionActionEnumSchema = {
    type: 'string',
    enum: ['EXPENSES', 'INCOME', 'TRANSFER']
} as const

export const TransactionStatusEnumSchema = {
    type: 'string',
    enum: ['APPROVED', 'REJECTED', 'IMPORT_PENDING', 'IMPORT_REJECTED', 'IMPORT_APPROVED']
} as const

export const RememberPeriodEnumSchema = {
    type: 'string',
    enum: ['SAME_DAY', 'THREE_DAYS', 'SEVEN_DAYS', 'FOURTEEN_DAYS', 'THIRTY_DAYS', 'NINETY_DAYS']
} as const

export const AppearanceModeEnumSchema = {
    type: 'string',
    enum: ['LOGO', 'ICON']
} as const

export const FileTypeEnumSchema = {
    type: 'string',
    enum: ['CSV', 'PDF']
} as const

export const OnBoardingStepEnumSchema = {
    type: 'string',
    enum: ['EMAIL', 'GENERALITES', 'PREFERENCES', 'COMPLETED']
} as const

export const CountriesEnumSchema = {
    type: 'string',
    enum: [
        'AFGHANISTAN',
        'ALBANIA',
        'ALGERIA',
        'ANDORRA',
        'ANGOLA',
        'ANTIGUA_AND_BARBUDA',
        'ARGENTINA',
        'ARMENIA',
        'AUSTRALIA',
        'AUSTRIA',
        'AZERBAIJAN',
        'BAHAMAS',
        'BAHRAIN',
        'BANGLADESH',
        'BARBADOS',
        'BELARUS',
        'BELGIUM',
        'BELIZE',
        'BENIN',
        'BHUTAN',
        'BOLIVIA',
        'BOSNIA_AND_HERZEGOVINA',
        'BOTSWANA',
        'BRAZIL',
        'BRUNEI',
        'BULGARIA',
        'BURKINA_FASO',
        'BURUNDI',
        'CABO_VERDE',
        'CAMBODIA',
        'CAMEROON',
        'CANADA',
        'CENTRAL_AFRICAN_REPUBLIC',
        'CHAD',
        'CHILE',
        'CHINA',
        'COLOMBIA',
        'COMOROS',
        'CONGO_DEMOCRATIC_REPUBLIC',
        'CONGO_REPUBLIC',
        'COSTA_RICA',
        'CROATIA',
        'CUBA',
        'CYPRUS',
        'CZECH_REPUBLIC',
        'DENMARK',
        'DJIBOUTI',
        'DOMINICA',
        'DOMINICAN_REPUBLIC',
        'ECUADOR',
        'EGYPT',
        'EL_SALVADOR',
        'EQUATORIAL_GUINEA',
        'ERITREA',
        'ESTONIA',
        'ESWATINI',
        'ETHIOPIA',
        'FIJI',
        'FINLAND',
        'FRANCE',
        'GABON',
        'GAMBIA',
        'GEORGIA',
        'GERMANY',
        'GHANA',
        'GREECE',
        'GRENADA',
        'GUATEMALA',
        'GUINEA',
        'GUINEA_BISSAU',
        'GUYANA',
        'HAITI',
        'HONDURAS',
        'HUNGARY',
        'ICELAND',
        'INDIA',
        'INDONESIA',
        'IRAN',
        'IRAQ',
        'IRELAND',
        'ISRAEL',
        'ITALY',
        'JAMAICA',
        'JAPAN',
        'JORDAN',
        'KAZAKHSTAN',
        'KENYA',
        'KIRIBATI',
        'KOREA_NORTH',
        'KOREA_SOUTH',
        'KUWAIT',
        'KYRGYZSTAN',
        'LAOS',
        'LATVIA',
        'LEBANON',
        'LESOTHO',
        'LIBERIA',
        'LIBYA',
        'LIECHTENSTEIN',
        'LITHUANIA',
        'LUXEMBOURG',
        'MADAGASCAR',
        'MALAWI',
        'MALAYSIA',
        'MALDIVES',
        'MALI',
        'MALTA',
        'MARSHALL_ISLANDS',
        'MAURITANIA',
        'MAURITIUS',
        'MEXICO',
        'MICRONESIA',
        'MOLDOVA',
        'MONACO',
        'MONGOLIA',
        'MONTENEGRO',
        'MOROCCO',
        'MOZAMBIQUE',
        'MYANMAR',
        'NAMIBIA',
        'NAURU',
        'NEPAL',
        'NETHERLANDS',
        'NEW_ZEALAND',
        'NICARAGUA',
        'NIGER',
        'NIGERIA',
        'NORTH_MACEDONIA',
        'NORWAY',
        'OMAN',
        'PAKISTAN',
        'PALAU',
        'PALESTINE',
        'PANAMA',
        'PAPUA_NEW_GUINEA',
        'PARAGUAY',
        'PERU',
        'PHILIPPINES',
        'POLAND',
        'PORTUGAL',
        'QATAR',
        'ROMANIA',
        'RUSSIA',
        'RWANDA',
        'SAINT_KITTS_AND_NEVIS',
        'SAINT_LUCIA',
        'SAINT_VINCENT_AND_GRENADINES',
        'SAMOA',
        'SAN_MARINO',
        'SAO_TOME_AND_PRINCIPE',
        'SAUDI_ARABIA',
        'SENEGAL',
        'SERBIA',
        'SEYCHELLES',
        'SIERRA_LEONE',
        'SINGAPORE',
        'SLOVAKIA',
        'SLOVENIA',
        'SOLOMON_ISLANDS',
        'SOMALIA',
        'SOUTH_AFRICA',
        'SOUTH_SUDAN',
        'SPAIN',
        'SRI_LANKA',
        'SUDAN',
        'SURINAME',
        'SWEDEN',
        'SWITZERLAND',
        'SYRIA',
        'TAIWAN',
        'TAJIKISTAN',
        'TANZANIA',
        'THAILAND',
        'TIMOR_LESTE',
        'TOGO',
        'TONGA',
        'TRINIDAD_AND_TOBAGO',
        'TUNISIA',
        'TURKEY',
        'TURKMENISTAN',
        'TUVALU',
        'UGANDA',
        'UKRAINE',
        'UNITED_ARAB_EMIRATES',
        'UNITED_KINGDOM',
        'UNITED_STATES',
        'URUGUAY',
        'UZBEKISTAN',
        'VANUATU',
        'VATICAN_CITY',
        'VENEZUELA',
        'VIETNAM',
        'YEMEN',
        'ZAMBIA',
        'ZIMBABWE'
    ]
} as const

export const UpdateUserRequestSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string',
            minLength: 1
        },
        surname: {
            type: 'string',
            minLength: 1
        },
        email: {
            type: 'string',
            format: 'email'
        },
        emailVerified: {
            type: 'boolean'
        },
        onBoardingStep: {
            $ref: '#/components/schemas/OnBoardingStepEnum'
        },
        onBoardingAt: {
            type: 'string',
            nullable: true
        },
        image: {
            type: 'string',
            nullable: true,
            format: 'uri'
        },
        createdAt: {
            type: 'string'
        },
        updatedAt: {
            type: 'string'
        },
        snapshotFrequency: {
            $ref: '#/components/schemas/SnapshotFrequencyEnum'
        },
        preferredCurrency: {
            $ref: '#/components/schemas/CurrencyEnum'
        },
        preferredLanguage: {
            $ref: '#/components/schemas/LanguageEnum'
        },
        dateFormat: {
            $ref: '#/components/schemas/DateFormatEnum'
        },
        country: {
            $ref: '#/components/schemas/CountriesEnum'
        },
        timezone: {
            $ref: '#/components/schemas/TimezoneEnum'
        }
    }
} as const

export const SimpleSuccessResponseSchema = {
    type: 'object',
    properties: {
        success: {
            type: 'boolean',
            enum: [true],
            description: 'Always true for success responses'
        },
        message: {
            type: 'string',
            description: 'Optional success message'
        }
    },
    required: ['success']
} as const
