// This file is auto-generated by @hey-api/openapi-ts

import {
    type Client,
    type ClientMeta,
    formDataBodySerializer,
    type Options as Options2,
    type RequestResult,
    type TDataShape
} from './client'
import { client } from './client.gen'
import type {
    ApproveImportTransactionsData,
    ApproveImportTransactionsErrors,
    ApproveImportTransactionsResponses,
    ChangeEmailData,
    ChangeEmailErrors,
    ChangeEmailResponses,
    ChangePasswordData,
    ChangePasswordErrors,
    ChangePasswordResponses,
    CompleteImportData,
    CompleteImportErrors,
    CompleteImportResponses,
    CreateAssetTransactionData,
    CreateAssetTransactionErrors,
    CreateAssetTransactionResponses,
    CreateCategoryData,
    CreateCategoryErrors,
    CreateCategoryResponses,
    CreateCollectibleAssetData,
    CreateCollectibleAssetErrors,
    CreateCollectibleAssetResponses,
    CreateFinancialAccountBalanceData,
    CreateFinancialAccountBalanceErrors,
    CreateFinancialAccountBalanceResponses,
    CreateFinancialAccountData,
    CreateFinancialAccountErrors,
    CreateFinancialAccountResponses,
    CreateImportData,
    CreateImportErrors,
    CreateImportResponses,
    CreateImportTemplateData,
    CreateImportTemplateErrors,
    CreateImportTemplateResponses,
    CreateMarketableAssetData,
    CreateMarketableAssetErrors,
    CreateMarketableAssetResponses,
    CreateOtherAssetData,
    CreateOtherAssetErrors,
    CreateOtherAssetResponses,
    CreateRealEstateAssetData,
    CreateRealEstateAssetErrors,
    CreateRealEstateAssetResponses,
    CreateSubcategoryData,
    CreateSubcategoryErrors,
    CreateSubcategoryResponses,
    CreateSubscriptionData,
    CreateSubscriptionErrors,
    CreateSubscriptionResponses,
    CreateTransactionData,
    CreateTransactionErrors,
    CreateTransactionResponses,
    CreateVehicleAssetData,
    CreateVehicleAssetErrors,
    CreateVehicleAssetResponses,
    DeleteAssetData,
    DeleteAssetErrors,
    DeleteAssetResponses,
    DeleteAssetsData,
    DeleteAssetsErrors,
    DeleteAssetsResponses,
    DeleteAssetTransactionData,
    DeleteAssetTransactionErrors,
    DeleteAssetTransactionResponses,
    DeleteAssetTransactionsData,
    DeleteAssetTransactionsErrors,
    DeleteAssetTransactionsResponses,
    DeleteCategoriesData,
    DeleteCategoriesErrors,
    DeleteCategoriesResponses,
    DeleteCategoryData,
    DeleteCategoryErrors,
    DeleteCategoryResponses,
    DeleteFinancialAccountData,
    DeleteFinancialAccountErrors,
    DeleteFinancialAccountResponses,
    DeleteFinancialAccountsData,
    DeleteFinancialAccountsErrors,
    DeleteFinancialAccountsResponses,
    DeleteImportData,
    DeleteImportErrors,
    DeleteImportResponses,
    DeleteImportsData,
    DeleteImportsErrors,
    DeleteImportsResponses,
    DeleteMarketDataProviderCredentialData,
    DeleteMarketDataProviderCredentialErrors,
    DeleteMarketDataProviderCredentialResponses,
    DeleteSubcategoriesData,
    DeleteSubcategoriesErrors,
    DeleteSubcategoriesResponses,
    DeleteSubcategoryData,
    DeleteSubcategoryErrors,
    DeleteSubcategoryResponses,
    DeleteSubscriptionData,
    DeleteSubscriptionErrors,
    DeleteSubscriptionResponses,
    DeleteSubscriptionsData,
    DeleteSubscriptionsErrors,
    DeleteSubscriptionsResponses,
    DeleteTransactionData,
    DeleteTransactionErrors,
    DeleteTransactionResponses,
    DeleteTransactionsData,
    DeleteTransactionsErrors,
    DeleteTransactionsResponses,
    DeleteUserData,
    DeleteUserErrors,
    DeleteUserResponses,
    GetAssetByIdData,
    GetAssetByIdErrors,
    GetAssetByIdResponses,
    GetAssetsData,
    GetAssetsErrors,
    GetAssetsResponses,
    GetAssetTransactionByIdData,
    GetAssetTransactionByIdErrors,
    GetAssetTransactionByIdResponses,
    GetAssetTransactionsData,
    GetAssetTransactionsErrors,
    GetAssetTransactionsResponses,
    GetAuthAccountInfoData,
    GetAuthAccountInfoErrors,
    GetAuthAccountInfoResponses,
    GetAuthCallbackByIdData,
    GetAuthCallbackByIdErrors,
    GetAuthDeleteUserCallbackData,
    GetAuthDeleteUserCallbackErrors,
    GetAuthDeleteUserCallbackResponses,
    GetAuthenticatedUserActivitiesData,
    GetAuthenticatedUserActivitiesErrors,
    GetAuthenticatedUserActivitiesResponses,
    GetAuthenticatedUserData,
    GetAuthenticatedUserErrors,
    GetAuthenticatedUserPreferencesData,
    GetAuthenticatedUserPreferencesErrors,
    GetAuthenticatedUserPreferencesResponses,
    GetAuthenticatedUserResponses,
    GetAuthErrorData,
    GetAuthErrorErrors,
    GetAuthErrorResponses,
    GetAuthOkData,
    GetAuthOkErrors,
    GetAuthOkResponses,
    GetAuthVerifyEmailData,
    GetAuthVerifyEmailErrors,
    GetAuthVerifyEmailResponses,
    GetCategoriesData,
    GetCategoriesErrors,
    GetCategoriesResponses,
    GetCategoryByIdData,
    GetCategoryByIdErrors,
    GetCategoryByIdResponses,
    GetDashboardLayoutData,
    GetDashboardLayoutErrors,
    GetDashboardLayoutResponses,
    GetFinancialAccountBalanceSeriesData,
    GetFinancialAccountBalanceSeriesErrors,
    GetFinancialAccountBalanceSeriesResponses,
    GetFinancialAccountByIdData,
    GetFinancialAccountByIdErrors,
    GetFinancialAccountByIdResponses,
    GetFinancialAccountsData,
    GetFinancialAccountsErrors,
    GetFinancialAccountsResponses,
    GetFinancialAccountSummaryData,
    GetFinancialAccountSummaryErrors,
    GetFinancialAccountSummaryResponses,
    GetImportByIdData,
    GetImportByIdErrors,
    GetImportByIdResponses,
    GetImportsData,
    GetImportsErrors,
    GetImportsResponses,
    GetImportTransactionsByIdData,
    GetImportTransactionsByIdErrors,
    GetImportTransactionsByIdResponses,
    GetMarketDataProvidersData,
    GetMarketDataProvidersErrors,
    GetMarketDataProvidersResponses,
    GetMarketQuotesData,
    GetMarketQuotesErrors,
    GetMarketQuotesResponses,
    GetRootStatusData,
    GetRootStatusErrors,
    GetRootStatusResponses,
    GetSessionData,
    GetSessionErrors,
    GetSessionPostData,
    GetSessionPostErrors,
    GetSessionPostResponses,
    GetSessionResponses,
    GetStatusData,
    GetStatusErrors,
    GetStatusResponses,
    GetSubcategoriesData,
    GetSubcategoriesErrors,
    GetSubcategoriesResponses,
    GetSubcategoryByIdData,
    GetSubcategoryByIdErrors,
    GetSubcategoryByIdResponses,
    GetSubscriptionByIdData,
    GetSubscriptionByIdErrors,
    GetSubscriptionByIdResponses,
    GetSubscriptionsData,
    GetSubscriptionsErrors,
    GetSubscriptionsResponses,
    GetTransactionByIdData,
    GetTransactionByIdErrors,
    GetTransactionByIdResponses,
    GetTransactionsData,
    GetTransactionsErrors,
    GetTransactionsResponses,
    GetTrendReportData,
    GetTrendReportErrors,
    GetTrendReportResponses,
    LinkSocialAccountData,
    LinkSocialAccountErrors,
    LinkSocialAccountResponses,
    ListUserAccountsData,
    ListUserAccountsErrors,
    ListUserAccountsResponses,
    ListUserSessionsData,
    ListUserSessionsErrors,
    ListUserSessionsResponses,
    PostAuthCallbackByIdData,
    PostAuthCallbackByIdErrors,
    PostAuthGetAccessTokenData,
    PostAuthGetAccessTokenErrors,
    PostAuthGetAccessTokenResponses,
    PostAuthRefreshTokenData,
    PostAuthRefreshTokenErrors,
    PostAuthRefreshTokenResponses,
    PostAuthRevokeOtherSessionsData,
    PostAuthRevokeOtherSessionsErrors,
    PostAuthRevokeOtherSessionsResponses,
    PostAuthRevokeSessionData,
    PostAuthRevokeSessionErrors,
    PostAuthRevokeSessionResponses,
    PostAuthRevokeSessionsData,
    PostAuthRevokeSessionsErrors,
    PostAuthRevokeSessionsResponses,
    PostAuthUnlinkAccountData,
    PostAuthUnlinkAccountErrors,
    PostAuthUnlinkAccountResponses,
    RequestPasswordResetData,
    RequestPasswordResetErrors,
    RequestPasswordResetResponses,
    ResetPasswordCallbackData,
    ResetPasswordCallbackErrors,
    ResetPasswordCallbackResponses,
    ResetPasswordData,
    ResetPasswordErrors,
    ResetPasswordResponses,
    RollbackImportData,
    RollbackImportErrors,
    RollbackImportResponses,
    SaveMarketDataProviderCredentialData,
    SaveMarketDataProviderCredentialErrors,
    SaveMarketDataProviderCredentialResponses,
    SearchMarketInstrumentsData,
    SearchMarketInstrumentsErrors,
    SearchMarketInstrumentsResponses,
    SendVerificationEmailData,
    SendVerificationEmailErrors,
    SendVerificationEmailResponses,
    SignInEmailData,
    SignInEmailErrors,
    SignInEmailResponses,
    SignOutData,
    SignOutErrors,
    SignOutResponses,
    SignUpWithEmailAndPasswordData,
    SignUpWithEmailAndPasswordErrors,
    SignUpWithEmailAndPasswordResponses,
    SocialSignInData,
    SocialSignInErrors,
    SocialSignInResponses,
    UpdateAssetTransactionData,
    UpdateAssetTransactionErrors,
    UpdateAssetTransactionResponses,
    UpdateAuthenticatedUserData,
    UpdateAuthenticatedUserErrors,
    UpdateAuthenticatedUserPreferencesData,
    UpdateAuthenticatedUserPreferencesErrors,
    UpdateAuthenticatedUserPreferencesResponses,
    UpdateAuthenticatedUserResponses,
    UpdateCategoryData,
    UpdateCategoryErrors,
    UpdateCategoryResponses,
    UpdateCollectibleAssetData,
    UpdateCollectibleAssetErrors,
    UpdateCollectibleAssetResponses,
    UpdateDashboardLayoutData,
    UpdateDashboardLayoutErrors,
    UpdateDashboardLayoutResponses,
    UpdateFinancialAccountData,
    UpdateFinancialAccountErrors,
    UpdateFinancialAccountResponses,
    UpdateImportData,
    UpdateImportErrors,
    UpdateImportResponses,
    UpdateMarketableAssetData,
    UpdateMarketableAssetErrors,
    UpdateMarketableAssetResponses,
    UpdateOtherAssetData,
    UpdateOtherAssetErrors,
    UpdateOtherAssetResponses,
    UpdateRealEstateAssetData,
    UpdateRealEstateAssetErrors,
    UpdateRealEstateAssetResponses,
    UpdateSessionData,
    UpdateSessionErrors,
    UpdateSessionResponses,
    UpdateSubcategoryData,
    UpdateSubcategoryErrors,
    UpdateSubcategoryResponses,
    UpdateSubscriptionData,
    UpdateSubscriptionErrors,
    UpdateSubscriptionResponses,
    UpdateTransactionData,
    UpdateTransactionErrors,
    UpdateTransactionResponses,
    UpdateUserData,
    UpdateUserErrors,
    UpdateUserResponses,
    UpdateVehicleAssetData,
    UpdateVehicleAssetErrors,
    UpdateVehicleAssetResponses,
    VerifyPasswordData,
    VerifyPasswordErrors,
    VerifyPasswordResponses
} from './types.gen'

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Healthcheck
 */
export const getRootStatus = <ThrowOnError extends boolean = false>(
    options?: Options<GetRootStatusData, ThrowOnError>
): RequestResult<GetRootStatusResponses, GetRootStatusErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetRootStatusResponses, GetRootStatusErrors, ThrowOnError>({ url: '/', ...options })

/**
 * Healthcheck
 */
export const getStatus = <ThrowOnError extends boolean = false>(
    options?: Options<GetStatusData, ThrowOnError>
): RequestResult<GetStatusResponses, GetStatusErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetStatusResponses, GetStatusErrors, ThrowOnError>({ url: '/status', ...options })

/**
 * Get authenticated user
 *
 * Get authenticated user information and preferences
 */
export const getAuthenticatedUser = <ThrowOnError extends boolean = false>(
    options?: Options<GetAuthenticatedUserData, ThrowOnError>
): RequestResult<GetAuthenticatedUserResponses, GetAuthenticatedUserErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetAuthenticatedUserResponses, GetAuthenticatedUserErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/user/me',
        ...options
    })

/**
 * Update authenticated user
 *
 * Updates the authenticated user's profile. Email changes require verification and may be subject to additional security checks.
 */
export const updateAuthenticatedUser = <ThrowOnError extends boolean = false>(
    options?: Options<UpdateAuthenticatedUserData, ThrowOnError>
): RequestResult<UpdateAuthenticatedUserResponses, UpdateAuthenticatedUserErrors, ThrowOnError> =>
    (options?.client ?? client).patch<UpdateAuthenticatedUserResponses, UpdateAuthenticatedUserErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/user/me',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Get authenticated user preferences
 *
 * Get the preferences for the authenticated user. Creates defaults if none exist.
 */
export const getAuthenticatedUserPreferences = <ThrowOnError extends boolean = false>(
    options?: Options<GetAuthenticatedUserPreferencesData, ThrowOnError>
): RequestResult<GetAuthenticatedUserPreferencesResponses, GetAuthenticatedUserPreferencesErrors, ThrowOnError> =>
    (options?.client ?? client).get<
        GetAuthenticatedUserPreferencesResponses,
        GetAuthenticatedUserPreferencesErrors,
        ThrowOnError
    >({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/user/me/preferences',
        ...options
    })

/**
 * Update authenticated user preferences
 *
 * Updates the authenticated user's preferences. Creates defaults if none exist.
 */
export const updateAuthenticatedUserPreferences = <ThrowOnError extends boolean = false>(
    options?: Options<UpdateAuthenticatedUserPreferencesData, ThrowOnError>
): RequestResult<UpdateAuthenticatedUserPreferencesResponses, UpdateAuthenticatedUserPreferencesErrors, ThrowOnError> =>
    (options?.client ?? client).patch<
        UpdateAuthenticatedUserPreferencesResponses,
        UpdateAuthenticatedUserPreferencesErrors,
        ThrowOnError
    >({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/user/me/preferences',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Get authenticated user activities
 *
 * Returns the audit-log activities recorded for the authenticated user, ordered by most recent.
 */
export const getAuthenticatedUserActivities = <ThrowOnError extends boolean = false>(
    options?: Options<GetAuthenticatedUserActivitiesData, ThrowOnError>
): RequestResult<GetAuthenticatedUserActivitiesResponses, GetAuthenticatedUserActivitiesErrors, ThrowOnError> =>
    (options?.client ?? client).get<
        GetAuthenticatedUserActivitiesResponses,
        GetAuthenticatedUserActivitiesErrors,
        ThrowOnError
    >({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/user/me/activities',
        ...options
    })

/**
 * Delete all assets
 *
 * Soft delete all assets for the authenticated user
 */
export const deleteAssets = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteAssetsData, ThrowOnError>
): RequestResult<DeleteAssetsResponses, DeleteAssetsErrors, ThrowOnError> =>
    (options?.client ?? client).delete<DeleteAssetsResponses, DeleteAssetsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets',
        ...options
    })

/**
 * Get all assets
 *
 * Retrieve the investment assets associated with the authenticated user
 */
export const getAssets = <ThrowOnError extends boolean = false>(
    options?: Options<GetAssetsData, ThrowOnError>
): RequestResult<GetAssetsResponses, GetAssetsErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetAssetsResponses, GetAssetsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets',
        ...options
    })

/**
 * Delete asset
 *
 * Soft delete an asset
 */
export const deleteAsset = <ThrowOnError extends boolean = false>(
    options: Options<DeleteAssetData, ThrowOnError>
): RequestResult<DeleteAssetResponses, DeleteAssetErrors, ThrowOnError> =>
    (options.client ?? client).delete<DeleteAssetResponses, DeleteAssetErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/{id}',
        ...options
    })

/**
 * Get asset by ID
 *
 * Retrieve a single asset and its normalized subtype data
 */
export const getAssetById = <ThrowOnError extends boolean = false>(
    options: Options<GetAssetByIdData, ThrowOnError>
): RequestResult<GetAssetByIdResponses, GetAssetByIdErrors, ThrowOnError> =>
    (options.client ?? client).get<GetAssetByIdResponses, GetAssetByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/{id}',
        ...options
    })

/**
 * Create marketable asset
 *
 * Create a marketable asset with its opening transaction
 */
export const createMarketableAsset = <ThrowOnError extends boolean = false>(
    options: Options<CreateMarketableAssetData, ThrowOnError>
): RequestResult<CreateMarketableAssetResponses, CreateMarketableAssetErrors, ThrowOnError> =>
    (options.client ?? client).post<CreateMarketableAssetResponses, CreateMarketableAssetErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/marketable',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Update marketable asset
 *
 * Update marketable asset metadata without creating transactions
 */
export const updateMarketableAsset = <ThrowOnError extends boolean = false>(
    options: Options<UpdateMarketableAssetData, ThrowOnError>
): RequestResult<UpdateMarketableAssetResponses, UpdateMarketableAssetErrors, ThrowOnError> =>
    (options.client ?? client).patch<UpdateMarketableAssetResponses, UpdateMarketableAssetErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/{id}/marketable',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Create real estate asset
 *
 * Create a real estate asset together with its parent asset record
 */
export const createRealEstateAsset = <ThrowOnError extends boolean = false>(
    options: Options<CreateRealEstateAssetData, ThrowOnError>
): RequestResult<CreateRealEstateAssetResponses, CreateRealEstateAssetErrors, ThrowOnError> =>
    (options.client ?? client).post<CreateRealEstateAssetResponses, CreateRealEstateAssetErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/real-estate',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Update real estate asset
 *
 * Update real estate asset details and its parent asset value
 */
export const updateRealEstateAsset = <ThrowOnError extends boolean = false>(
    options: Options<UpdateRealEstateAssetData, ThrowOnError>
): RequestResult<UpdateRealEstateAssetResponses, UpdateRealEstateAssetErrors, ThrowOnError> =>
    (options.client ?? client).patch<UpdateRealEstateAssetResponses, UpdateRealEstateAssetErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/{id}/real-estate',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Create vehicle asset
 *
 * Create a vehicle asset together with its parent asset record and an optional brand logo
 */
export const createVehicleAsset = <ThrowOnError extends boolean = false>(
    options: Options<CreateVehicleAssetData, ThrowOnError>
): RequestResult<CreateVehicleAssetResponses, CreateVehicleAssetErrors, ThrowOnError> =>
    (options.client ?? client).post<CreateVehicleAssetResponses, CreateVehicleAssetErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/vehicle',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    })

/**
 * Update vehicle asset
 *
 * Update vehicle asset details, its parent asset value and an optional brand logo
 */
export const updateVehicleAsset = <ThrowOnError extends boolean = false>(
    options: Options<UpdateVehicleAssetData, ThrowOnError>
): RequestResult<UpdateVehicleAssetResponses, UpdateVehicleAssetErrors, ThrowOnError> =>
    (options.client ?? client).patch<UpdateVehicleAssetResponses, UpdateVehicleAssetErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/{id}/vehicle',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    })

/**
 * Create collectible asset
 *
 * Create a collectible asset together with its parent asset record
 */
export const createCollectibleAsset = <ThrowOnError extends boolean = false>(
    options: Options<CreateCollectibleAssetData, ThrowOnError>
): RequestResult<CreateCollectibleAssetResponses, CreateCollectibleAssetErrors, ThrowOnError> =>
    (options.client ?? client).post<CreateCollectibleAssetResponses, CreateCollectibleAssetErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/collectible',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Update collectible asset
 *
 * Update collectible asset details and its parent asset value
 */
export const updateCollectibleAsset = <ThrowOnError extends boolean = false>(
    options: Options<UpdateCollectibleAssetData, ThrowOnError>
): RequestResult<UpdateCollectibleAssetResponses, UpdateCollectibleAssetErrors, ThrowOnError> =>
    (options.client ?? client).patch<UpdateCollectibleAssetResponses, UpdateCollectibleAssetErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/{id}/collectible',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Create other asset
 *
 * Create an other asset together with its parent asset record
 */
export const createOtherAsset = <ThrowOnError extends boolean = false>(
    options: Options<CreateOtherAssetData, ThrowOnError>
): RequestResult<CreateOtherAssetResponses, CreateOtherAssetErrors, ThrowOnError> =>
    (options.client ?? client).post<CreateOtherAssetResponses, CreateOtherAssetErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/other',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Update other asset
 *
 * Update other asset details and its parent asset value
 */
export const updateOtherAsset = <ThrowOnError extends boolean = false>(
    options: Options<UpdateOtherAssetData, ThrowOnError>
): RequestResult<UpdateOtherAssetResponses, UpdateOtherAssetErrors, ThrowOnError> =>
    (options.client ?? client).patch<UpdateOtherAssetResponses, UpdateOtherAssetErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/{id}/other',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Delete all asset transactions
 *
 * Soft delete all asset transactions for the authenticated user
 */
export const deleteAssetTransactions = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteAssetTransactionsData, ThrowOnError>
): RequestResult<DeleteAssetTransactionsResponses, DeleteAssetTransactionsErrors, ThrowOnError> =>
    (options?.client ?? client).delete<DeleteAssetTransactionsResponses, DeleteAssetTransactionsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/transactions',
        ...options
    })

/**
 * Get asset transactions
 *
 * Retrieve the asset transactions associated with the authenticated user
 */
export const getAssetTransactions = <ThrowOnError extends boolean = false>(
    options?: Options<GetAssetTransactionsData, ThrowOnError>
): RequestResult<GetAssetTransactionsResponses, GetAssetTransactionsErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetAssetTransactionsResponses, GetAssetTransactionsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/transactions',
        ...options
    })

/**
 * Create asset transaction
 *
 * Create a new transaction for an asset
 */
export const createAssetTransaction = <ThrowOnError extends boolean = false>(
    options: Options<CreateAssetTransactionData, ThrowOnError>
): RequestResult<CreateAssetTransactionResponses, CreateAssetTransactionErrors, ThrowOnError> =>
    (options.client ?? client).post<CreateAssetTransactionResponses, CreateAssetTransactionErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/transactions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Delete asset transaction
 *
 * Soft delete an asset transaction
 */
export const deleteAssetTransaction = <ThrowOnError extends boolean = false>(
    options: Options<DeleteAssetTransactionData, ThrowOnError>
): RequestResult<DeleteAssetTransactionResponses, DeleteAssetTransactionErrors, ThrowOnError> =>
    (options.client ?? client).delete<DeleteAssetTransactionResponses, DeleteAssetTransactionErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/transactions/{id}',
        ...options
    })

/**
 * Get asset transaction by ID
 *
 * Retrieve a single asset transaction
 */
export const getAssetTransactionById = <ThrowOnError extends boolean = false>(
    options: Options<GetAssetTransactionByIdData, ThrowOnError>
): RequestResult<GetAssetTransactionByIdResponses, GetAssetTransactionByIdErrors, ThrowOnError> =>
    (options.client ?? client).get<GetAssetTransactionByIdResponses, GetAssetTransactionByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/transactions/{id}',
        ...options
    })

/**
 * Update asset transaction
 *
 * Update an existing transaction for an asset
 */
export const updateAssetTransaction = <ThrowOnError extends boolean = false>(
    options: Options<UpdateAssetTransactionData, ThrowOnError>
): RequestResult<UpdateAssetTransactionResponses, UpdateAssetTransactionErrors, ThrowOnError> =>
    (options.client ?? client).patch<UpdateAssetTransactionResponses, UpdateAssetTransactionErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/assets/transactions/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Delete all categories
 *
 * Delete all categories associated with the user
 */
export const deleteCategories = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteCategoriesData, ThrowOnError>
): RequestResult<DeleteCategoriesResponses, DeleteCategoriesErrors, ThrowOnError> =>
    (options?.client ?? client).delete<DeleteCategoriesResponses, DeleteCategoriesErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/categories',
        ...options
    })

/**
 * Get all categories
 *
 * Retrieve a list of all categories associated with the user
 */
export const getCategories = <ThrowOnError extends boolean = false>(
    options?: Options<GetCategoriesData, ThrowOnError>
): RequestResult<GetCategoriesResponses, GetCategoriesErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetCategoriesResponses, GetCategoriesErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/categories',
        ...options
    })

/**
 * Create category
 *
 * Create a new category with the provided data
 */
export const createCategory = <ThrowOnError extends boolean = false>(
    options: Options<CreateCategoryData, ThrowOnError>
): RequestResult<CreateCategoryResponses, CreateCategoryErrors, ThrowOnError> =>
    (options.client ?? client).post<CreateCategoryResponses, CreateCategoryErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/categories',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Delete category
 *
 * Delete an existing category with the provided ID
 */
export const deleteCategory = <ThrowOnError extends boolean = false>(
    options: Options<DeleteCategoryData, ThrowOnError>
): RequestResult<DeleteCategoryResponses, DeleteCategoryErrors, ThrowOnError> =>
    (options.client ?? client).delete<DeleteCategoryResponses, DeleteCategoryErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/categories/{id}',
        ...options
    })

/**
 * Get category by ID
 *
 * Retrieve a specific category by its ID
 */
export const getCategoryById = <ThrowOnError extends boolean = false>(
    options: Options<GetCategoryByIdData, ThrowOnError>
): RequestResult<GetCategoryByIdResponses, GetCategoryByIdErrors, ThrowOnError> =>
    (options.client ?? client).get<GetCategoryByIdResponses, GetCategoryByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/categories/{id}',
        ...options
    })

/**
 * Update category
 *
 * Update an existing category with the provided data
 */
export const updateCategory = <ThrowOnError extends boolean = false>(
    options: Options<UpdateCategoryData, ThrowOnError>
): RequestResult<UpdateCategoryResponses, UpdateCategoryErrors, ThrowOnError> =>
    (options.client ?? client).patch<UpdateCategoryResponses, UpdateCategoryErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/categories/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Delete all subcategories
 *
 * Delete all subcategories associated with the user
 */
export const deleteSubcategories = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteSubcategoriesData, ThrowOnError>
): RequestResult<DeleteSubcategoriesResponses, DeleteSubcategoriesErrors, ThrowOnError> =>
    (options?.client ?? client).delete<DeleteSubcategoriesResponses, DeleteSubcategoriesErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subcategories',
        ...options
    })

/**
 * Get all subcategories
 *
 * Retrieve a list of all subcategories associated with the user
 */
export const getSubcategories = <ThrowOnError extends boolean = false>(
    options?: Options<GetSubcategoriesData, ThrowOnError>
): RequestResult<GetSubcategoriesResponses, GetSubcategoriesErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetSubcategoriesResponses, GetSubcategoriesErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subcategories',
        ...options
    })

/**
 * Create subcategory
 *
 * Create a new subcategory with the provided data
 */
export const createSubcategory = <ThrowOnError extends boolean = false>(
    options: Options<CreateSubcategoryData, ThrowOnError>
): RequestResult<CreateSubcategoryResponses, CreateSubcategoryErrors, ThrowOnError> =>
    (options.client ?? client).post<CreateSubcategoryResponses, CreateSubcategoryErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subcategories',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Delete subcategory
 *
 * Delete an existing subcategory with the provided ID
 */
export const deleteSubcategory = <ThrowOnError extends boolean = false>(
    options: Options<DeleteSubcategoryData, ThrowOnError>
): RequestResult<DeleteSubcategoryResponses, DeleteSubcategoryErrors, ThrowOnError> =>
    (options.client ?? client).delete<DeleteSubcategoryResponses, DeleteSubcategoryErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subcategories/{id}',
        ...options
    })

/**
 * Get subcategory by ID
 *
 * Retrieve a specific subcategory by its ID
 */
export const getSubcategoryById = <ThrowOnError extends boolean = false>(
    options: Options<GetSubcategoryByIdData, ThrowOnError>
): RequestResult<GetSubcategoryByIdResponses, GetSubcategoryByIdErrors, ThrowOnError> =>
    (options.client ?? client).get<GetSubcategoryByIdResponses, GetSubcategoryByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subcategories/{id}',
        ...options
    })

/**
 * Update subcategory
 *
 * Update an existing subcategory with the provided data
 */
export const updateSubcategory = <ThrowOnError extends boolean = false>(
    options: Options<UpdateSubcategoryData, ThrowOnError>
): RequestResult<UpdateSubcategoryResponses, UpdateSubcategoryErrors, ThrowOnError> =>
    (options.client ?? client).patch<UpdateSubcategoryResponses, UpdateSubcategoryErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subcategories/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Delete all transactions
 *
 * Delete all transactions associated with the user
 */
export const deleteTransactions = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteTransactionsData, ThrowOnError>
): RequestResult<DeleteTransactionsResponses, DeleteTransactionsErrors, ThrowOnError> =>
    (options?.client ?? client).delete<DeleteTransactionsResponses, DeleteTransactionsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/transactions',
        ...options
    })

/**
 * Get all transactions
 *
 * Retrieve a list of all transactions associated with the user
 */
export const getTransactions = <ThrowOnError extends boolean = false>(
    options?: Options<GetTransactionsData, ThrowOnError>
): RequestResult<GetTransactionsResponses, GetTransactionsErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetTransactionsResponses, GetTransactionsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/transactions',
        ...options
    })

/**
 * Create transaction
 *
 * Create a new transaction with the provided data
 */
export const createTransaction = <ThrowOnError extends boolean = false>(
    options: Options<CreateTransactionData, ThrowOnError>
): RequestResult<CreateTransactionResponses, CreateTransactionErrors, ThrowOnError> =>
    (options.client ?? client).post<CreateTransactionResponses, CreateTransactionErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/transactions',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    })

/**
 * Delete transaction
 *
 * Delete an existing transaction with the provided ID
 */
export const deleteTransaction = <ThrowOnError extends boolean = false>(
    options: Options<DeleteTransactionData, ThrowOnError>
): RequestResult<DeleteTransactionResponses, DeleteTransactionErrors, ThrowOnError> =>
    (options.client ?? client).delete<DeleteTransactionResponses, DeleteTransactionErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/transactions/{id}',
        ...options
    })

/**
 * Get transaction by ID
 *
 * Retrieve a specific transaction by its ID
 */
export const getTransactionById = <ThrowOnError extends boolean = false>(
    options: Options<GetTransactionByIdData, ThrowOnError>
): RequestResult<GetTransactionByIdResponses, GetTransactionByIdErrors, ThrowOnError> =>
    (options.client ?? client).get<GetTransactionByIdResponses, GetTransactionByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/transactions/{id}',
        ...options
    })

/**
 * Update transaction
 *
 * Update an existing transaction with the provided data
 */
export const updateTransaction = <ThrowOnError extends boolean = false>(
    options: Options<UpdateTransactionData, ThrowOnError>
): RequestResult<UpdateTransactionResponses, UpdateTransactionErrors, ThrowOnError> =>
    (options.client ?? client).patch<UpdateTransactionResponses, UpdateTransactionErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/transactions/{id}',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    })

/**
 * Delete all subscriptions
 *
 * Delete all subscriptions associated with the user
 */
export const deleteSubscriptions = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteSubscriptionsData, ThrowOnError>
): RequestResult<DeleteSubscriptionsResponses, DeleteSubscriptionsErrors, ThrowOnError> =>
    (options?.client ?? client).delete<DeleteSubscriptionsResponses, DeleteSubscriptionsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subscriptions',
        ...options
    })

/**
 * Get all subscriptions
 *
 * Retrieve a list of all subscriptions associated with the user
 */
export const getSubscriptions = <ThrowOnError extends boolean = false>(
    options?: Options<GetSubscriptionsData, ThrowOnError>
): RequestResult<GetSubscriptionsResponses, GetSubscriptionsErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetSubscriptionsResponses, GetSubscriptionsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subscriptions',
        ...options
    })

/**
 * Create subscription
 *
 * Create a new subscription with the provided data
 */
export const createSubscription = <ThrowOnError extends boolean = false>(
    options: Options<CreateSubscriptionData, ThrowOnError>
): RequestResult<CreateSubscriptionResponses, CreateSubscriptionErrors, ThrowOnError> =>
    (options.client ?? client).post<CreateSubscriptionResponses, CreateSubscriptionErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subscriptions',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    })

/**
 * Delete subscription
 *
 * Delete an existing subscription with the provided ID
 */
export const deleteSubscription = <ThrowOnError extends boolean = false>(
    options: Options<DeleteSubscriptionData, ThrowOnError>
): RequestResult<DeleteSubscriptionResponses, DeleteSubscriptionErrors, ThrowOnError> =>
    (options.client ?? client).delete<DeleteSubscriptionResponses, DeleteSubscriptionErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subscriptions/{id}',
        ...options
    })

/**
 * Get subscription by ID
 *
 * Retrieve a specific subscription by its ID
 */
export const getSubscriptionById = <ThrowOnError extends boolean = false>(
    options: Options<GetSubscriptionByIdData, ThrowOnError>
): RequestResult<GetSubscriptionByIdResponses, GetSubscriptionByIdErrors, ThrowOnError> =>
    (options.client ?? client).get<GetSubscriptionByIdResponses, GetSubscriptionByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subscriptions/{id}',
        ...options
    })

/**
 * Update subscription
 *
 * Update an existing subscription with the provided data
 */
export const updateSubscription = <ThrowOnError extends boolean = false>(
    options: Options<UpdateSubscriptionData, ThrowOnError>
): RequestResult<UpdateSubscriptionResponses, UpdateSubscriptionErrors, ThrowOnError> =>
    (options.client ?? client).patch<UpdateSubscriptionResponses, UpdateSubscriptionErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subscriptions/{id}',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    })

/**
 * Delete all financial accounts
 *
 * Delete all financial accounts associated with the user
 */
export const deleteFinancialAccounts = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteFinancialAccountsData, ThrowOnError>
): RequestResult<DeleteFinancialAccountsResponses, DeleteFinancialAccountsErrors, ThrowOnError> =>
    (options?.client ?? client).delete<DeleteFinancialAccountsResponses, DeleteFinancialAccountsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/financial-accounts',
        ...options
    })

/**
 * Get all financial accounts
 *
 * Retrieve a list of all financial accounts associated with the user
 */
export const getFinancialAccounts = <ThrowOnError extends boolean = false>(
    options?: Options<GetFinancialAccountsData, ThrowOnError>
): RequestResult<GetFinancialAccountsResponses, GetFinancialAccountsErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetFinancialAccountsResponses, GetFinancialAccountsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/financial-accounts',
        ...options
    })

/**
 * Create financial account
 *
 * Create a new financial account with the provided data
 */
export const createFinancialAccount = <ThrowOnError extends boolean = false>(
    options: Options<CreateFinancialAccountData, ThrowOnError>
): RequestResult<CreateFinancialAccountResponses, CreateFinancialAccountErrors, ThrowOnError> =>
    (options.client ?? client).post<CreateFinancialAccountResponses, CreateFinancialAccountErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/financial-accounts',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    })

/**
 * Delete financial account
 *
 * Delete an existing financial account with the provided ID
 */
export const deleteFinancialAccount = <ThrowOnError extends boolean = false>(
    options: Options<DeleteFinancialAccountData, ThrowOnError>
): RequestResult<DeleteFinancialAccountResponses, DeleteFinancialAccountErrors, ThrowOnError> =>
    (options.client ?? client).delete<DeleteFinancialAccountResponses, DeleteFinancialAccountErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/financial-accounts/{id}',
        ...options
    })

/**
 * Get financial account by ID
 *
 * Retrieve a specific financial account by its ID
 */
export const getFinancialAccountById = <ThrowOnError extends boolean = false>(
    options: Options<GetFinancialAccountByIdData, ThrowOnError>
): RequestResult<GetFinancialAccountByIdResponses, GetFinancialAccountByIdErrors, ThrowOnError> =>
    (options.client ?? client).get<GetFinancialAccountByIdResponses, GetFinancialAccountByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/financial-accounts/{id}',
        ...options
    })

/**
 * Update financial account
 *
 * Update an existing financial account with the provided data
 */
export const updateFinancialAccount = <ThrowOnError extends boolean = false>(
    options: Options<UpdateFinancialAccountData, ThrowOnError>
): RequestResult<UpdateFinancialAccountResponses, UpdateFinancialAccountErrors, ThrowOnError> =>
    (options.client ?? client).patch<UpdateFinancialAccountResponses, UpdateFinancialAccountErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/financial-accounts/{id}',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    })

/**
 * Create a manual financial account balance entry
 *
 * Records a manual balance anchor for a financial account at a given date and recomputes the subsequent balance time-series
 */
export const createFinancialAccountBalance = <ThrowOnError extends boolean = false>(
    options: Options<CreateFinancialAccountBalanceData, ThrowOnError>
): RequestResult<CreateFinancialAccountBalanceResponses, CreateFinancialAccountBalanceErrors, ThrowOnError> =>
    (options.client ?? client).post<
        CreateFinancialAccountBalanceResponses,
        CreateFinancialAccountBalanceErrors,
        ThrowOnError
    >({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/financial-accounts/balance',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Get a financial account balance time-series
 *
 * Retrieve the daily balance time-series of a financial account within an optional date range
 */
export const getFinancialAccountBalanceSeries = <ThrowOnError extends boolean = false>(
    options: Options<GetFinancialAccountBalanceSeriesData, ThrowOnError>
): RequestResult<GetFinancialAccountBalanceSeriesResponses, GetFinancialAccountBalanceSeriesErrors, ThrowOnError> =>
    (options.client ?? client).get<
        GetFinancialAccountBalanceSeriesResponses,
        GetFinancialAccountBalanceSeriesErrors,
        ThrowOnError
    >({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/financial-accounts/{id}/balance-series',
        ...options
    })

/**
 * Get a financial account period summary
 *
 * Retrieve the aggregated income, expenses and transaction count of a financial account within an optional date range
 */
export const getFinancialAccountSummary = <ThrowOnError extends boolean = false>(
    options: Options<GetFinancialAccountSummaryData, ThrowOnError>
): RequestResult<GetFinancialAccountSummaryResponses, GetFinancialAccountSummaryErrors, ThrowOnError> =>
    (options.client ?? client).get<GetFinancialAccountSummaryResponses, GetFinancialAccountSummaryErrors, ThrowOnError>(
        {
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/financial-accounts/{id}/summary',
            ...options
        }
    )

/**
 * Delete all imports
 *
 * Delete all imports associated with the user
 */
export const deleteImports = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteImportsData, ThrowOnError>
): RequestResult<DeleteImportsResponses, DeleteImportsErrors, ThrowOnError> =>
    (options?.client ?? client).delete<DeleteImportsResponses, DeleteImportsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports',
        ...options
    })

/**
 * Get all imports
 *
 * Retrieve a list of all imports associated with the user
 */
export const getImports = <ThrowOnError extends boolean = false>(
    options?: Options<GetImportsData, ThrowOnError>
): RequestResult<GetImportsResponses, GetImportsErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetImportsResponses, GetImportsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports',
        ...options
    })

/**
 * Create import
 *
 * Create a new import with the provided data
 */
export const createImport = <ThrowOnError extends boolean = false>(
    options: Options<CreateImportData, ThrowOnError>
): RequestResult<CreateImportResponses, CreateImportErrors, ThrowOnError> =>
    (options.client ?? client).post<CreateImportResponses, CreateImportErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    })

/**
 * Delete import
 *
 * Delete an existing import with the provided ID
 */
export const deleteImport = <ThrowOnError extends boolean = false>(
    options: Options<DeleteImportData, ThrowOnError>
): RequestResult<DeleteImportResponses, DeleteImportErrors, ThrowOnError> =>
    (options.client ?? client).delete<DeleteImportResponses, DeleteImportErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports/{id}',
        ...options
    })

/**
 * Get import by ID
 *
 * Retrieve a specific import by its ID
 */
export const getImportById = <ThrowOnError extends boolean = false>(
    options: Options<GetImportByIdData, ThrowOnError>
): RequestResult<GetImportByIdResponses, GetImportByIdErrors, ThrowOnError> =>
    (options.client ?? client).get<GetImportByIdResponses, GetImportByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports/{id}',
        ...options
    })

/**
 * Update import
 *
 * Update an existing import with the provided data
 */
export const updateImport = <ThrowOnError extends boolean = false>(
    options: Options<UpdateImportData, ThrowOnError>
): RequestResult<UpdateImportResponses, UpdateImportErrors, ThrowOnError> =>
    (options.client ?? client).put<UpdateImportResponses, UpdateImportErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Get import transactions by ID
 *
 * Retrieve transactions for a specific import by its ID
 */
export const getImportTransactionsById = <ThrowOnError extends boolean = false>(
    options: Options<GetImportTransactionsByIdData, ThrowOnError>
): RequestResult<GetImportTransactionsByIdResponses, GetImportTransactionsByIdErrors, ThrowOnError> =>
    (options.client ?? client).get<GetImportTransactionsByIdResponses, GetImportTransactionsByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports/{id}/transactions',
        ...options
    })

/**
 * Approve or reject import transactions
 *
 * Bulk approve or reject transactions for a specific import
 */
export const approveImportTransactions = <ThrowOnError extends boolean = false>(
    options: Options<ApproveImportTransactionsData, ThrowOnError>
): RequestResult<ApproveImportTransactionsResponses, ApproveImportTransactionsErrors, ThrowOnError> =>
    (options.client ?? client).patch<ApproveImportTransactionsResponses, ApproveImportTransactionsErrors, ThrowOnError>(
        {
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/imports/{id}/transactions/approve',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        }
    )

/**
 * Create import template
 *
 * Create a new import template with the provided data
 */
export const createImportTemplate = <ThrowOnError extends boolean = false>(
    options: Options<CreateImportTemplateData, ThrowOnError>
): RequestResult<CreateImportTemplateResponses, CreateImportTemplateErrors, ThrowOnError> =>
    (options.client ?? client).post<CreateImportTemplateResponses, CreateImportTemplateErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports/template/{action}',
        ...options
    })

/**
 * Complete import
 *
 * Mark an existing import as complete
 */
export const completeImport = <ThrowOnError extends boolean = false>(
    options: Options<CompleteImportData, ThrowOnError>
): RequestResult<CompleteImportResponses, CompleteImportErrors, ThrowOnError> =>
    (options.client ?? client).patch<CompleteImportResponses, CompleteImportErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports/complete/{id}',
        ...options
    })

/**
 * Rollback import
 *
 * Rollback a completed import: moves the import and its approved transactions back to pending and reverts balance changes
 */
export const rollbackImport = <ThrowOnError extends boolean = false>(
    options: Options<RollbackImportData, ThrowOnError>
): RequestResult<RollbackImportResponses, RollbackImportErrors, ThrowOnError> =>
    (options.client ?? client).patch<RollbackImportResponses, RollbackImportErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports/rollback/{id}',
        ...options
    })

/**
 * Get market data providers
 *
 * List the enabled raw market data providers and their capabilities
 */
export const getMarketDataProviders = <ThrowOnError extends boolean = false>(
    options?: Options<GetMarketDataProvidersData, ThrowOnError>
): RequestResult<GetMarketDataProvidersResponses, GetMarketDataProvidersErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetMarketDataProvidersResponses, GetMarketDataProvidersErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/market-data/providers',
        ...options
    })

/**
 * Delete market data provider credential
 *
 * Delete the authenticated users encrypted provider API key
 */
export const deleteMarketDataProviderCredential = <ThrowOnError extends boolean = false>(
    options: Options<DeleteMarketDataProviderCredentialData, ThrowOnError>
): RequestResult<DeleteMarketDataProviderCredentialResponses, DeleteMarketDataProviderCredentialErrors, ThrowOnError> =>
    (options.client ?? client).delete<
        DeleteMarketDataProviderCredentialResponses,
        DeleteMarketDataProviderCredentialErrors,
        ThrowOnError
    >({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/market-data/providers/{providerId}/credential',
        ...options
    })

/**
 * Save market data provider credential
 *
 * Encrypt and store the authenticated users provider API key server-side
 */
export const saveMarketDataProviderCredential = <ThrowOnError extends boolean = false>(
    options: Options<SaveMarketDataProviderCredentialData, ThrowOnError>
): RequestResult<SaveMarketDataProviderCredentialResponses, SaveMarketDataProviderCredentialErrors, ThrowOnError> =>
    (options.client ?? client).put<
        SaveMarketDataProviderCredentialResponses,
        SaveMarketDataProviderCredentialErrors,
        ThrowOnError
    >({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/market-data/providers/{providerId}/credential',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Search instruments
 *
 * Search provider instruments and return a normalized instrument list
 */
export const searchMarketInstruments = <ThrowOnError extends boolean = false>(
    options: Options<SearchMarketInstrumentsData, ThrowOnError>
): RequestResult<SearchMarketInstrumentsResponses, SearchMarketInstrumentsErrors, ThrowOnError> =>
    (options.client ?? client).get<SearchMarketInstrumentsResponses, SearchMarketInstrumentsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/market-data/instruments',
        ...options
    })

/**
 * Get quotes
 *
 * Fetch normalized live quotes using the selected provider
 */
export const getMarketQuotes = <ThrowOnError extends boolean = false>(
    options: Options<GetMarketQuotesData, ThrowOnError>
): RequestResult<GetMarketQuotesResponses, GetMarketQuotesErrors, ThrowOnError> =>
    (options.client ?? client).get<GetMarketQuotesResponses, GetMarketQuotesErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/market-data/quotes',
        ...options
    })

/**
 * Get dashboard layout
 *
 * Retrieve a specific dashboard layout
 */
export const getDashboardLayout = <ThrowOnError extends boolean = false>(
    options?: Options<GetDashboardLayoutData, ThrowOnError>
): RequestResult<GetDashboardLayoutResponses, GetDashboardLayoutErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetDashboardLayoutResponses, GetDashboardLayoutErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/dashboard',
        ...options
    })

/**
 * Update dashboard layout
 *
 * Update a specific dashboard layout
 */
export const updateDashboardLayout = <ThrowOnError extends boolean = false>(
    options: Options<UpdateDashboardLayoutData, ThrowOnError>
): RequestResult<UpdateDashboardLayoutResponses, UpdateDashboardLayoutErrors, ThrowOnError> =>
    (options.client ?? client).put<UpdateDashboardLayoutResponses, UpdateDashboardLayoutErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/dashboard',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Get trend report
 *
 * Retrieve a trend report based on the users imports
 */
export const getTrendReport = <ThrowOnError extends boolean = false>(
    options?: Options<GetTrendReportData, ThrowOnError>
): RequestResult<GetTrendReportResponses, GetTrendReportErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetTrendReportResponses, GetTrendReportErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/reports/trend',
        ...options
    })

/**
 * Sign in with a social provider
 */
export const socialSignIn = <ThrowOnError extends boolean = false>(
    options: Options<SocialSignInData, ThrowOnError>
): RequestResult<SocialSignInResponses, SocialSignInErrors, ThrowOnError> =>
    (options.client ?? client).post<SocialSignInResponses, SocialSignInErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/sign-in/social',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

export const getAuthCallbackById = <ThrowOnError extends boolean = false>(
    options: Options<GetAuthCallbackByIdData, ThrowOnError>
): RequestResult<unknown, GetAuthCallbackByIdErrors, ThrowOnError> =>
    (options.client ?? client).get<unknown, GetAuthCallbackByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/callback/{id}',
        ...options
    })

export const postAuthCallbackById = <ThrowOnError extends boolean = false>(
    options: Options<PostAuthCallbackByIdData, ThrowOnError>
): RequestResult<unknown, PostAuthCallbackByIdErrors, ThrowOnError> =>
    (options.client ?? client).post<unknown, PostAuthCallbackByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/callback/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Get the current session
 */
export const getSession = <ThrowOnError extends boolean = false>(
    options?: Options<GetSessionData, ThrowOnError>
): RequestResult<GetSessionResponses, GetSessionErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetSessionResponses, GetSessionErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/get-session',
        ...options
    })

/**
 * Get the current session
 */
export const getSessionPost = <ThrowOnError extends boolean = false>(
    options?: Options<GetSessionPostData, ThrowOnError>
): RequestResult<GetSessionPostResponses, GetSessionPostErrors, ThrowOnError> =>
    (options?.client ?? client).post<GetSessionPostResponses, GetSessionPostErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/get-session',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Sign out the current user
 */
export const signOut = <ThrowOnError extends boolean = false>(
    options?: Options<SignOutData, ThrowOnError>
): RequestResult<SignOutResponses, SignOutErrors, ThrowOnError> =>
    (options?.client ?? client).post<SignOutResponses, SignOutErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/sign-out',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Sign up a user using email and password
 */
export const signUpWithEmailAndPassword = <ThrowOnError extends boolean = false>(
    options?: Options<SignUpWithEmailAndPasswordData, ThrowOnError>
): RequestResult<SignUpWithEmailAndPasswordResponses, SignUpWithEmailAndPasswordErrors, ThrowOnError> =>
    (options?.client ?? client).post<
        SignUpWithEmailAndPasswordResponses,
        SignUpWithEmailAndPasswordErrors,
        ThrowOnError
    >({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/sign-up/email',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Sign in with email and password
 */
export const signInEmail = <ThrowOnError extends boolean = false>(
    options: Options<SignInEmailData, ThrowOnError>
): RequestResult<SignInEmailResponses, SignInEmailErrors, ThrowOnError> =>
    (options.client ?? client).post<SignInEmailResponses, SignInEmailErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/sign-in/email',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Reset the password for a user
 */
export const resetPassword = <ThrowOnError extends boolean = false>(
    options: Options<ResetPasswordData, ThrowOnError>
): RequestResult<ResetPasswordResponses, ResetPasswordErrors, ThrowOnError> =>
    (options.client ?? client).post<ResetPasswordResponses, ResetPasswordErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/reset-password',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Verify the current user's password
 */
export const verifyPassword = <ThrowOnError extends boolean = false>(
    options: Options<VerifyPasswordData, ThrowOnError>
): RequestResult<VerifyPasswordResponses, VerifyPasswordErrors, ThrowOnError> =>
    (options.client ?? client).post<VerifyPasswordResponses, VerifyPasswordErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/verify-password',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Verify the email of the user
 */
export const getAuthVerifyEmail = <ThrowOnError extends boolean = false>(
    options: Options<GetAuthVerifyEmailData, ThrowOnError>
): RequestResult<GetAuthVerifyEmailResponses, GetAuthVerifyEmailErrors, ThrowOnError> =>
    (options.client ?? client).get<GetAuthVerifyEmailResponses, GetAuthVerifyEmailErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/verify-email',
        ...options
    })

/**
 * Send a verification email to the user
 */
export const sendVerificationEmail = <ThrowOnError extends boolean = false>(
    options?: Options<SendVerificationEmailData, ThrowOnError>
): RequestResult<SendVerificationEmailResponses, SendVerificationEmailErrors, ThrowOnError> =>
    (options?.client ?? client).post<SendVerificationEmailResponses, SendVerificationEmailErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/send-verification-email',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

export const changeEmail = <ThrowOnError extends boolean = false>(
    options: Options<ChangeEmailData, ThrowOnError>
): RequestResult<ChangeEmailResponses, ChangeEmailErrors, ThrowOnError> =>
    (options.client ?? client).post<ChangeEmailResponses, ChangeEmailErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/change-email',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Change the password of the user
 */
export const changePassword = <ThrowOnError extends boolean = false>(
    options: Options<ChangePasswordData, ThrowOnError>
): RequestResult<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError> =>
    (options.client ?? client).post<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/change-password',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Update the current session
 */
export const updateSession = <ThrowOnError extends boolean = false>(
    options: Options<UpdateSessionData, ThrowOnError>
): RequestResult<UpdateSessionResponses, UpdateSessionErrors, ThrowOnError> =>
    (options.client ?? client).post<UpdateSessionResponses, UpdateSessionErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/update-session',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Update the current user
 */
export const updateUser = <ThrowOnError extends boolean = false>(
    options?: Options<UpdateUserData, ThrowOnError>
): RequestResult<UpdateUserResponses, UpdateUserErrors, ThrowOnError> =>
    (options?.client ?? client).post<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/update-user',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Delete the user
 */
export const deleteUser = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteUserData, ThrowOnError>
): RequestResult<DeleteUserResponses, DeleteUserErrors, ThrowOnError> =>
    (options?.client ?? client).post<DeleteUserResponses, DeleteUserErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/delete-user',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Send a password reset email to the user
 */
export const requestPasswordReset = <ThrowOnError extends boolean = false>(
    options: Options<RequestPasswordResetData, ThrowOnError>
): RequestResult<RequestPasswordResetResponses, RequestPasswordResetErrors, ThrowOnError> =>
    (options.client ?? client).post<RequestPasswordResetResponses, RequestPasswordResetErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/request-password-reset',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Redirects the user to the callback URL with the token
 */
export const resetPasswordCallback = <ThrowOnError extends boolean = false>(
    options: Options<ResetPasswordCallbackData, ThrowOnError>
): RequestResult<ResetPasswordCallbackResponses, ResetPasswordCallbackErrors, ThrowOnError> =>
    (options.client ?? client).get<ResetPasswordCallbackResponses, ResetPasswordCallbackErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/reset-password/{token}',
        ...options
    })

/**
 * List all active sessions for the user
 */
export const listUserSessions = <ThrowOnError extends boolean = false>(
    options?: Options<ListUserSessionsData, ThrowOnError>
): RequestResult<ListUserSessionsResponses, ListUserSessionsErrors, ThrowOnError> =>
    (options?.client ?? client).get<ListUserSessionsResponses, ListUserSessionsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/list-sessions',
        ...options
    })

/**
 * Revoke a single session
 */
export const postAuthRevokeSession = <ThrowOnError extends boolean = false>(
    options?: Options<PostAuthRevokeSessionData, ThrowOnError>
): RequestResult<PostAuthRevokeSessionResponses, PostAuthRevokeSessionErrors, ThrowOnError> =>
    (options?.client ?? client).post<PostAuthRevokeSessionResponses, PostAuthRevokeSessionErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/revoke-session',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Revoke all sessions for the user
 */
export const postAuthRevokeSessions = <ThrowOnError extends boolean = false>(
    options?: Options<PostAuthRevokeSessionsData, ThrowOnError>
): RequestResult<PostAuthRevokeSessionsResponses, PostAuthRevokeSessionsErrors, ThrowOnError> =>
    (options?.client ?? client).post<PostAuthRevokeSessionsResponses, PostAuthRevokeSessionsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/revoke-sessions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Revoke all other sessions for the user except the current one
 */
export const postAuthRevokeOtherSessions = <ThrowOnError extends boolean = false>(
    options?: Options<PostAuthRevokeOtherSessionsData, ThrowOnError>
): RequestResult<PostAuthRevokeOtherSessionsResponses, PostAuthRevokeOtherSessionsErrors, ThrowOnError> =>
    (options?.client ?? client).post<
        PostAuthRevokeOtherSessionsResponses,
        PostAuthRevokeOtherSessionsErrors,
        ThrowOnError
    >({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/revoke-other-sessions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Link a social account to the user
 */
export const linkSocialAccount = <ThrowOnError extends boolean = false>(
    options: Options<LinkSocialAccountData, ThrowOnError>
): RequestResult<LinkSocialAccountResponses, LinkSocialAccountErrors, ThrowOnError> =>
    (options.client ?? client).post<LinkSocialAccountResponses, LinkSocialAccountErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/link-social',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * List all accounts linked to the user
 */
export const listUserAccounts = <ThrowOnError extends boolean = false>(
    options?: Options<ListUserAccountsData, ThrowOnError>
): RequestResult<ListUserAccountsResponses, ListUserAccountsErrors, ThrowOnError> =>
    (options?.client ?? client).get<ListUserAccountsResponses, ListUserAccountsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/list-accounts',
        ...options
    })

/**
 * Callback to complete user deletion with verification token
 */
export const getAuthDeleteUserCallback = <ThrowOnError extends boolean = false>(
    options?: Options<GetAuthDeleteUserCallbackData, ThrowOnError>
): RequestResult<GetAuthDeleteUserCallbackResponses, GetAuthDeleteUserCallbackErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetAuthDeleteUserCallbackResponses, GetAuthDeleteUserCallbackErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/delete-user/callback',
        ...options
    })

/**
 * Unlink an account
 */
export const postAuthUnlinkAccount = <ThrowOnError extends boolean = false>(
    options: Options<PostAuthUnlinkAccountData, ThrowOnError>
): RequestResult<PostAuthUnlinkAccountResponses, PostAuthUnlinkAccountErrors, ThrowOnError> =>
    (options.client ?? client).post<PostAuthUnlinkAccountResponses, PostAuthUnlinkAccountErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/unlink-account',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Refresh the access token using a refresh token
 */
export const postAuthRefreshToken = <ThrowOnError extends boolean = false>(
    options: Options<PostAuthRefreshTokenData, ThrowOnError>
): RequestResult<PostAuthRefreshTokenResponses, PostAuthRefreshTokenErrors, ThrowOnError> =>
    (options.client ?? client).post<PostAuthRefreshTokenResponses, PostAuthRefreshTokenErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/refresh-token',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Get a valid access token, doing a refresh if needed
 */
export const postAuthGetAccessToken = <ThrowOnError extends boolean = false>(
    options: Options<PostAuthGetAccessTokenData, ThrowOnError>
): RequestResult<PostAuthGetAccessTokenResponses, PostAuthGetAccessTokenErrors, ThrowOnError> =>
    (options.client ?? client).post<PostAuthGetAccessTokenResponses, PostAuthGetAccessTokenErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/get-access-token',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Get the account info provided by the provider
 */
export const getAuthAccountInfo = <ThrowOnError extends boolean = false>(
    options?: Options<GetAuthAccountInfoData, ThrowOnError>
): RequestResult<GetAuthAccountInfoResponses, GetAuthAccountInfoErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetAuthAccountInfoResponses, GetAuthAccountInfoErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/account-info',
        ...options
    })

/**
 * Check if the API is working
 */
export const getAuthOk = <ThrowOnError extends boolean = false>(
    options?: Options<GetAuthOkData, ThrowOnError>
): RequestResult<GetAuthOkResponses, GetAuthOkErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetAuthOkResponses, GetAuthOkErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/ok',
        ...options
    })

/**
 * Displays an error page
 */
export const getAuthError = <ThrowOnError extends boolean = false>(
    options?: Options<GetAuthErrorData, ThrowOnError>
): RequestResult<GetAuthErrorResponses, GetAuthErrorErrors, ThrowOnError> =>
    (options?.client ?? client).get<GetAuthErrorResponses, GetAuthErrorErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/auth/error',
        ...options
    })
