// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js'
import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client/index.js'
import type {
    ChangeEmailData,
    ChangeEmailErrors,
    ChangeEmailResponses,
    ChangePasswordData,
    ChangePasswordErrors,
    ChangePasswordResponses,
    CompleteImportData,
    CompleteImportErrors,
    CompleteImportResponses,
    CreateCategoryData,
    CreateCategoryErrors,
    CreateCategoryResponses,
    CreateFinancialAccountData,
    CreateFinancialAccountErrors,
    CreateFinancialAccountResponses,
    CreateImportData,
    CreateImportErrors,
    CreateImportResponses,
    CreateSnapshotAccountBalanceData,
    CreateSnapshotAccountBalanceErrors,
    CreateSnapshotAccountBalanceResponses,
    CreateSubcategoryData,
    CreateSubcategoryErrors,
    CreateSubcategoryResponses,
    CreateSubscriptionData,
    CreateSubscriptionErrors,
    CreateSubscriptionResponses,
    CreateTransactionData,
    CreateTransactionErrors,
    CreateTransactionResponses,
    DeleteCategoriesData,
    DeleteCategoriesErrors,
    DeleteCategoriesResponses,
    DeleteCategoryData,
    DeleteCategoryErrors,
    DeleteCategoryResponses,
    DeleteFinancialAccountData,
    DeleteFinancialAccountErrors,
    DeleteFinancialAccountResponses,
    DeleteFinancialAccountsData,
    DeleteFinancialAccountsErrors,
    DeleteFinancialAccountsResponses,
    DeleteImportData,
    DeleteImportErrors,
    DeleteImportResponses,
    DeleteImportsData,
    DeleteImportsErrors,
    DeleteImportsResponses,
    DeleteSubcategoriesData,
    DeleteSubcategoriesErrors,
    DeleteSubcategoriesResponses,
    DeleteSubcategoryData,
    DeleteSubcategoryErrors,
    DeleteSubcategoryResponses,
    DeleteSubscriptionData,
    DeleteSubscriptionErrors,
    DeleteSubscriptionResponses,
    DeleteSubscriptionsData,
    DeleteSubscriptionsErrors,
    DeleteSubscriptionsResponses,
    DeleteTransactionData,
    DeleteTransactionErrors,
    DeleteTransactionResponses,
    DeleteTransactionsData,
    DeleteTransactionsErrors,
    DeleteTransactionsResponses,
    DeleteUserData,
    DeleteUserErrors,
    DeleteUserResponses,
    GetAccountInfoData,
    GetAccountInfoErrors,
    GetAccountInfoResponses,
    GetAuthenticatedUserData,
    GetAuthenticatedUserErrors,
    GetAuthenticatedUserResponses,
    GetCallbackByIdData,
    GetCallbackByIdErrors,
    GetCategoriesData,
    GetCategoriesErrors,
    GetCategoriesResponses,
    GetCategoryByIdData,
    GetCategoryByIdErrors,
    GetCategoryByIdResponses,
    GetDashboardLayoutData,
    GetDashboardLayoutErrors,
    GetDashboardLayoutResponses,
    GetDeleteUserCallbackData,
    GetDeleteUserCallbackErrors,
    GetDeleteUserCallbackResponses,
    GetErrorData,
    GetErrorErrors,
    GetErrorResponses,
    GetFinancialAccountByIdData,
    GetFinancialAccountByIdErrors,
    GetFinancialAccountByIdResponses,
    GetFinancialAccountsData,
    GetFinancialAccountsErrors,
    GetFinancialAccountsResponses,
    GetImportByIdData,
    GetImportByIdErrors,
    GetImportByIdResponses,
    GetImportsData,
    GetImportsErrors,
    GetImportsResponses,
    GetImportTransactionsByIdData,
    GetImportTransactionsByIdErrors,
    GetImportTransactionsByIdResponses,
    GetOkData,
    GetOkErrors,
    GetOkResponses,
    GetRootStatusData,
    GetRootStatusErrors,
    GetRootStatusResponses,
    GetSession2Data,
    GetSession2Errors,
    GetSession2Responses,
    GetSessionData,
    GetSessionErrors,
    GetSessionResponses,
    GetStatusData,
    GetStatusErrors,
    GetStatusResponses,
    GetSubcategoriesData,
    GetSubcategoriesErrors,
    GetSubcategoriesResponses,
    GetSubcategoryByIdData,
    GetSubcategoryByIdErrors,
    GetSubcategoryByIdResponses,
    GetSubscriptionByIdData,
    GetSubscriptionByIdErrors,
    GetSubscriptionByIdResponses,
    GetSubscriptionsData,
    GetSubscriptionsErrors,
    GetSubscriptionsResponses,
    GetTransactionByIdData,
    GetTransactionByIdErrors,
    GetTransactionByIdResponses,
    GetTransactionsData,
    GetTransactionsErrors,
    GetTransactionsResponses,
    GetTrendReportData,
    GetTrendReportErrors,
    GetTrendReportResponses,
    GetVerifyEmailData,
    GetVerifyEmailErrors,
    GetVerifyEmailResponses,
    LinkSocialAccountData,
    LinkSocialAccountErrors,
    LinkSocialAccountResponses,
    ListUserAccountsData,
    ListUserAccountsErrors,
    ListUserAccountsResponses,
    ListUserSessionsData,
    ListUserSessionsErrors,
    ListUserSessionsResponses,
    PostCallbackByIdData,
    PostCallbackByIdErrors,
    PostGetAccessTokenData,
    PostGetAccessTokenErrors,
    PostGetAccessTokenResponses,
    PostRefreshTokenData,
    PostRefreshTokenErrors,
    PostRefreshTokenResponses,
    PostRevokeOtherSessionsData,
    PostRevokeOtherSessionsErrors,
    PostRevokeOtherSessionsResponses,
    PostRevokeSessionData,
    PostRevokeSessionErrors,
    PostRevokeSessionResponses,
    PostRevokeSessionsData,
    PostRevokeSessionsErrors,
    PostRevokeSessionsResponses,
    PostUnlinkAccountData,
    PostUnlinkAccountErrors,
    PostUnlinkAccountResponses,
    RequestPasswordResetData,
    RequestPasswordResetErrors,
    RequestPasswordResetResponses,
    ResetPasswordCallbackData,
    ResetPasswordCallbackErrors,
    ResetPasswordCallbackResponses,
    ResetPasswordData,
    ResetPasswordErrors,
    ResetPasswordResponses,
    SendVerificationEmailData,
    SendVerificationEmailErrors,
    SendVerificationEmailResponses,
    SignInEmailData,
    SignInEmailErrors,
    SignInEmailResponses,
    SignOutData,
    SignOutErrors,
    SignOutResponses,
    SignUpWithEmailAndPasswordData,
    SignUpWithEmailAndPasswordErrors,
    SignUpWithEmailAndPasswordResponses,
    SocialSignInData,
    SocialSignInErrors,
    SocialSignInResponses,
    UpdateAuthenticatedUserData,
    UpdateAuthenticatedUserErrors,
    UpdateAuthenticatedUserResponses,
    UpdateCategoryData,
    UpdateCategoryErrors,
    UpdateCategoryResponses,
    UpdateDashboardLayoutData,
    UpdateDashboardLayoutErrors,
    UpdateDashboardLayoutResponses,
    UpdateFinancialAccountData,
    UpdateFinancialAccountErrors,
    UpdateFinancialAccountResponses,
    UpdateImportData,
    UpdateImportErrors,
    UpdateImportResponses,
    UpdateSessionData,
    UpdateSessionErrors,
    UpdateSessionResponses,
    UpdateSubcategoryData,
    UpdateSubcategoryErrors,
    UpdateSubcategoryResponses,
    UpdateSubscriptionData,
    UpdateSubscriptionErrors,
    UpdateSubscriptionResponses,
    UpdateTransactionData,
    UpdateTransactionErrors,
    UpdateTransactionResponses,
    UpdateUserData,
    UpdateUserErrors,
    UpdateUserResponses,
    VerifyPasswordData,
    VerifyPasswordErrors,
    VerifyPasswordResponses
} from './types.gen.js'

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
    TData,
    ThrowOnError
> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>
}

/**
 * Delete all categories
 *
 * Delete all categories associated with the user
 */
export const deleteCategories = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteCategoriesData, ThrowOnError>
) =>
    (options?.client ?? client).delete<DeleteCategoriesResponses, DeleteCategoriesErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/categories',
        ...options
    })

/**
 * Get all categories
 *
 * Retrieve a list of all categories associated with the user
 */
export const getCategories = <ThrowOnError extends boolean = false>(
    options?: Options<GetCategoriesData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetCategoriesResponses, GetCategoriesErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/categories',
        ...options
    })

/**
 * Create category
 *
 * Create a new category with the provided data
 */
export const createCategory = <ThrowOnError extends boolean = false>(
    options: Options<CreateCategoryData, ThrowOnError>
) =>
    (options.client ?? client).post<CreateCategoryResponses, CreateCategoryErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/categories',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    })

/**
 * Delete category
 *
 * Delete an existing category with the provided ID
 */
export const deleteCategory = <ThrowOnError extends boolean = false>(
    options: Options<DeleteCategoryData, ThrowOnError>
) =>
    (options.client ?? client).delete<DeleteCategoryResponses, DeleteCategoryErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/categories/{id}',
        ...options
    })

/**
 * Get category by ID
 *
 * Retrieve a specific category by its ID
 */
export const getCategoryById = <ThrowOnError extends boolean = false>(
    options: Options<GetCategoryByIdData, ThrowOnError>
) =>
    (options.client ?? client).get<GetCategoryByIdResponses, GetCategoryByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/categories/{id}',
        ...options
    })

/**
 * Update category
 *
 * Update an existing category with the provided data
 */
export const updateCategory = <ThrowOnError extends boolean = false>(
    options: Options<UpdateCategoryData, ThrowOnError>
) =>
    (options.client ?? client).patch<UpdateCategoryResponses, UpdateCategoryErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/categories/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Get dashboard layout
 *
 * Retrieve a specific dashboard layout
 */
export const getDashboardLayout = <ThrowOnError extends boolean = false>(
    options?: Options<GetDashboardLayoutData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetDashboardLayoutResponses, GetDashboardLayoutErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/dashboard',
        ...options
    })

/**
 * Update dashboard layout
 *
 * Update a specific dashboard layout
 */
export const updateDashboardLayout = <ThrowOnError extends boolean = false>(
    options: Options<UpdateDashboardLayoutData, ThrowOnError>
) =>
    (options.client ?? client).put<UpdateDashboardLayoutResponses, UpdateDashboardLayoutErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/dashboard',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Delete all financial accounts
 *
 * Delete all financial accounts associated with the user
 */
export const deleteFinancialAccounts = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteFinancialAccountsData, ThrowOnError>
) =>
    (options?.client ?? client).delete<DeleteFinancialAccountsResponses, DeleteFinancialAccountsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/financial-account',
        ...options
    })

/**
 * Get all financial accounts
 *
 * Retrieve a list of all financial accounts associated with the user
 */
export const getFinancialAccounts = <ThrowOnError extends boolean = false>(
    options?: Options<GetFinancialAccountsData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetFinancialAccountsResponses, GetFinancialAccountsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/financial-account',
        ...options
    })

/**
 * Create financial account
 *
 * Create a new financial account with the provided data
 */
export const createFinancialAccount = <ThrowOnError extends boolean = false>(
    options: Options<CreateFinancialAccountData, ThrowOnError>
) =>
    (options.client ?? client).post<CreateFinancialAccountResponses, CreateFinancialAccountErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/financial-account',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    })

/**
 * Get financial account by ID
 *
 * Retrieve a specific financial account by its ID
 */
export const getFinancialAccountById = <ThrowOnError extends boolean = false>(
    options: Options<GetFinancialAccountByIdData, ThrowOnError>
) =>
    (options.client ?? client).get<GetFinancialAccountByIdResponses, GetFinancialAccountByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/financial-accounts/{id}',
        ...options
    })

/**
 * Delete financial account
 *
 * Delete an existing financial account with the provided ID
 */
export const deleteFinancialAccount = <ThrowOnError extends boolean = false>(
    options: Options<DeleteFinancialAccountData, ThrowOnError>
) =>
    (options.client ?? client).delete<DeleteFinancialAccountResponses, DeleteFinancialAccountErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/financial-account/{id}',
        ...options
    })

/**
 * Update financial account
 *
 * Update an existing financial account with the provided data
 */
export const updateFinancialAccount = <ThrowOnError extends boolean = false>(
    options: Options<UpdateFinancialAccountData, ThrowOnError>
) =>
    (options.client ?? client).patch<UpdateFinancialAccountResponses, UpdateFinancialAccountErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/financial-account/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Delete all imports
 *
 * Delete all imports associated with the user
 */
export const deleteImports = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteImportsData, ThrowOnError>
) =>
    (options?.client ?? client).delete<DeleteImportsResponses, DeleteImportsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports',
        ...options
    })

/**
 * Get all imports
 *
 * Retrieve a list of all imports associated with the user
 */
export const getImports = <ThrowOnError extends boolean = false>(options?: Options<GetImportsData, ThrowOnError>) =>
    (options?.client ?? client).get<GetImportsResponses, GetImportsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports',
        ...options
    })

/**
 * Create import
 *
 * Create a new import with the provided data
 */
export const createImport = <ThrowOnError extends boolean = false>(options: Options<CreateImportData, ThrowOnError>) =>
    (options.client ?? client).post<CreateImportResponses, CreateImportErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    })

/**
 * Delete import
 *
 * Delete an existing import with the provided ID
 */
export const deleteImport = <ThrowOnError extends boolean = false>(options: Options<DeleteImportData, ThrowOnError>) =>
    (options.client ?? client).delete<DeleteImportResponses, DeleteImportErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports/{id}',
        ...options
    })

/**
 * Get import by ID
 *
 * Retrieve a specific import by its ID
 */
export const getImportById = <ThrowOnError extends boolean = false>(
    options: Options<GetImportByIdData, ThrowOnError>
) =>
    (options.client ?? client).get<GetImportByIdResponses, GetImportByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports/{id}',
        ...options
    })

/**
 * Update import
 *
 * Update an existing import with the provided data
 */
export const updateImport = <ThrowOnError extends boolean = false>(options: Options<UpdateImportData, ThrowOnError>) =>
    (options.client ?? client).put<UpdateImportResponses, UpdateImportErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Complete import
 *
 * Mark an existing import as complete
 */
export const completeImport = <ThrowOnError extends boolean = false>(
    options: Options<CompleteImportData, ThrowOnError>
) =>
    (options.client ?? client).patch<CompleteImportResponses, CompleteImportErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports/complete/{id}',
        ...options
    })

/**
 * Get trend report
 *
 * Retrieve a trend report based on the users imports
 */
export const getTrendReport = <ThrowOnError extends boolean = false>(
    options?: Options<GetTrendReportData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetTrendReportResponses, GetTrendReportErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/report/trend',
        ...options
    })

/**
 * Create snapshot account balance
 *
 * Create a new snapshot account balance with the provided data
 */
export const createSnapshotAccountBalance = <ThrowOnError extends boolean = false>(
    options: Options<CreateSnapshotAccountBalanceData, ThrowOnError>
) =>
    (options.client ?? client).post<
        CreateSnapshotAccountBalanceResponses,
        CreateSnapshotAccountBalanceErrors,
        ThrowOnError
    >({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/account-balance',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Healthcheck
 */
export const getRootStatus = <ThrowOnError extends boolean = false>(
    options?: Options<GetRootStatusData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetRootStatusResponses, GetRootStatusErrors, ThrowOnError>({ url: '/', ...options })

/**
 * Healthcheck
 */
export const getStatus = <ThrowOnError extends boolean = false>(options?: Options<GetStatusData, ThrowOnError>) =>
    (options?.client ?? client).get<GetStatusResponses, GetStatusErrors, ThrowOnError>({ url: '/status', ...options })

/**
 * Delete all subcategories
 *
 * Delete all subcategories associated with the user
 */
export const deleteSubcategories = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteSubcategoriesData, ThrowOnError>
) =>
    (options?.client ?? client).delete<DeleteSubcategoriesResponses, DeleteSubcategoriesErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subcategories',
        ...options
    })

/**
 * Get all subcategories
 *
 * Retrieve a list of all subcategories associated with the user
 */
export const getSubcategories = <ThrowOnError extends boolean = false>(
    options?: Options<GetSubcategoriesData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetSubcategoriesResponses, GetSubcategoriesErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subcategories',
        ...options
    })

/**
 * Create subcategory
 *
 * Create a new subcategory with the provided data
 */
export const createSubcategory = <ThrowOnError extends boolean = false>(
    options: Options<CreateSubcategoryData, ThrowOnError>
) =>
    (options.client ?? client).post<CreateSubcategoryResponses, CreateSubcategoryErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subcategories',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    })

/**
 * Delete subcategory
 *
 * Delete an existing subcategory with the provided ID
 */
export const deleteSubcategory = <ThrowOnError extends boolean = false>(
    options: Options<DeleteSubcategoryData, ThrowOnError>
) =>
    (options.client ?? client).delete<DeleteSubcategoryResponses, DeleteSubcategoryErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subcategories/{id}',
        ...options
    })

/**
 * Get subcategory by ID
 *
 * Retrieve a specific subcategory by its ID
 */
export const getSubcategoryById = <ThrowOnError extends boolean = false>(
    options: Options<GetSubcategoryByIdData, ThrowOnError>
) =>
    (options.client ?? client).get<GetSubcategoryByIdResponses, GetSubcategoryByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subcategories/{id}',
        ...options
    })

/**
 * Update subcategory
 *
 * Update an existing subcategory with the provided data
 */
export const updateSubcategory = <ThrowOnError extends boolean = false>(
    options: Options<UpdateSubcategoryData, ThrowOnError>
) =>
    (options.client ?? client).patch<UpdateSubcategoryResponses, UpdateSubcategoryErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subcategories/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Delete all subscriptions
 *
 * Delete all subscriptions associated with the user
 */
export const deleteSubscriptions = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteSubscriptionsData, ThrowOnError>
) =>
    (options?.client ?? client).delete<DeleteSubscriptionsResponses, DeleteSubscriptionsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subscriptions',
        ...options
    })

/**
 * Get all subscriptions
 *
 * Retrieve a list of all subscriptions associated with the user
 */
export const getSubscriptions = <ThrowOnError extends boolean = false>(
    options?: Options<GetSubscriptionsData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetSubscriptionsResponses, GetSubscriptionsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subscriptions',
        ...options
    })

/**
 * Create subscription
 *
 * Create a new subscription with the provided data
 */
export const createSubscription = <ThrowOnError extends boolean = false>(
    options: Options<CreateSubscriptionData, ThrowOnError>
) =>
    (options.client ?? client).post<CreateSubscriptionResponses, CreateSubscriptionErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subscriptions',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    })

/**
 * Delete subscription
 *
 * Delete an existing subscription with the provided ID
 */
export const deleteSubscription = <ThrowOnError extends boolean = false>(
    options: Options<DeleteSubscriptionData, ThrowOnError>
) =>
    (options.client ?? client).delete<DeleteSubscriptionResponses, DeleteSubscriptionErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subscriptions/{id}',
        ...options
    })

/**
 * Get subscription by ID
 *
 * Retrieve a specific subscription by its ID
 */
export const getSubscriptionById = <ThrowOnError extends boolean = false>(
    options: Options<GetSubscriptionByIdData, ThrowOnError>
) =>
    (options.client ?? client).get<GetSubscriptionByIdResponses, GetSubscriptionByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subscriptions/{id}',
        ...options
    })

/**
 * Update subscription
 *
 * Update an existing subscription with the provided data
 */
export const updateSubscription = <ThrowOnError extends boolean = false>(
    options: Options<UpdateSubscriptionData, ThrowOnError>
) =>
    (options.client ?? client).patch<UpdateSubscriptionResponses, UpdateSubscriptionErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/subscriptions/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Delete all transactions
 *
 * Delete all transactions associated with the user
 */
export const deleteTransactions = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteTransactionsData, ThrowOnError>
) =>
    (options?.client ?? client).delete<DeleteTransactionsResponses, DeleteTransactionsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/transactions',
        ...options
    })

/**
 * Get all transactions
 *
 * Retrieve a list of all transactions associated with the user
 */
export const getTransactions = <ThrowOnError extends boolean = false>(
    options?: Options<GetTransactionsData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetTransactionsResponses, GetTransactionsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/transactions',
        ...options
    })

/**
 * Create transaction
 *
 * Create a new transaction with the provided data
 */
export const createTransaction = <ThrowOnError extends boolean = false>(
    options: Options<CreateTransactionData, ThrowOnError>
) =>
    (options.client ?? client).post<CreateTransactionResponses, CreateTransactionErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/transactions',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    })

/**
 * Delete transaction
 *
 * Delete an existing transaction with the provided ID
 */
export const deleteTransaction = <ThrowOnError extends boolean = false>(
    options: Options<DeleteTransactionData, ThrowOnError>
) =>
    (options.client ?? client).delete<DeleteTransactionResponses, DeleteTransactionErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/transactions/{id}',
        ...options
    })

/**
 * Get transaction by ID
 *
 * Retrieve a specific transaction by its ID
 */
export const getTransactionById = <ThrowOnError extends boolean = false>(
    options: Options<GetTransactionByIdData, ThrowOnError>
) =>
    (options.client ?? client).get<GetTransactionByIdResponses, GetTransactionByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/transactions/{id}',
        ...options
    })

/**
 * Update transaction
 *
 * Update an existing transaction with the provided data
 */
export const updateTransaction = <ThrowOnError extends boolean = false>(
    options: Options<UpdateTransactionData, ThrowOnError>
) =>
    (options.client ?? client).patch<UpdateTransactionResponses, UpdateTransactionErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/transactions/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Get authenticated user
 *
 * Get authenticated user information and preferences
 */
export const getAuthenticatedUser = <ThrowOnError extends boolean = false>(
    options?: Options<GetAuthenticatedUserData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetAuthenticatedUserResponses, GetAuthenticatedUserErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/me',
        ...options
    })

/**
 * Update authenticated user
 *
 * Updates the authenticated user's profile. Email changes require verification and may be subject to additional security checks.
 */
export const updateAuthenticatedUser = <ThrowOnError extends boolean = false>(
    options?: Options<UpdateAuthenticatedUserData, ThrowOnError>
) =>
    (options?.client ?? client).patch<UpdateAuthenticatedUserResponses, UpdateAuthenticatedUserErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/me',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Get import transactions by ID
 *
 * Retrieve transactions for a specific import by its ID
 */
export const getImportTransactionsById = <ThrowOnError extends boolean = false>(
    options: Options<GetImportTransactionsByIdData, ThrowOnError>
) =>
    (options.client ?? client).get<GetImportTransactionsByIdResponses, GetImportTransactionsByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/imports/{id}/transactions',
        ...options
    })

/**
 * Sign in with a social provider
 */
export const socialSignIn = <ThrowOnError extends boolean = false>(options: Options<SocialSignInData, ThrowOnError>) =>
    (options.client ?? client).post<SocialSignInResponses, SocialSignInErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/sign-in/social',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Get the current session
 */
export const getSession = <ThrowOnError extends boolean = false>(options?: Options<GetSessionData, ThrowOnError>) =>
    (options?.client ?? client).get<GetSessionResponses, GetSessionErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/get-session',
        ...options
    })

/**
 * Get the current session
 */
export const getSession2 = <ThrowOnError extends boolean = false>(options?: Options<GetSession2Data, ThrowOnError>) =>
    (options?.client ?? client).post<GetSession2Responses, GetSession2Errors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/get-session',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Sign out the current user
 */
export const signOut = <ThrowOnError extends boolean = false>(options?: Options<SignOutData, ThrowOnError>) =>
    (options?.client ?? client).post<SignOutResponses, SignOutErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/sign-out',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Sign up a user using email and password
 */
export const signUpWithEmailAndPassword = <ThrowOnError extends boolean = false>(
    options?: Options<SignUpWithEmailAndPasswordData, ThrowOnError>
) =>
    (options?.client ?? client).post<
        SignUpWithEmailAndPasswordResponses,
        SignUpWithEmailAndPasswordErrors,
        ThrowOnError
    >({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/sign-up/email',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Sign in with email and password
 */
export const signInEmail = <ThrowOnError extends boolean = false>(options: Options<SignInEmailData, ThrowOnError>) =>
    (options.client ?? client).post<SignInEmailResponses, SignInEmailErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/sign-in/email',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Reset the password for a user
 */
export const resetPassword = <ThrowOnError extends boolean = false>(
    options: Options<ResetPasswordData, ThrowOnError>
) =>
    (options.client ?? client).post<ResetPasswordResponses, ResetPasswordErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/reset-password',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Verify the current user's password
 */
export const verifyPassword = <ThrowOnError extends boolean = false>(
    options: Options<VerifyPasswordData, ThrowOnError>
) =>
    (options.client ?? client).post<VerifyPasswordResponses, VerifyPasswordErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/verify-password',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Verify the email of the user
 */
export const getVerifyEmail = <ThrowOnError extends boolean = false>(
    options: Options<GetVerifyEmailData, ThrowOnError>
) =>
    (options.client ?? client).get<GetVerifyEmailResponses, GetVerifyEmailErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/verify-email',
        ...options
    })

/**
 * Send a verification email to the user
 */
export const sendVerificationEmail = <ThrowOnError extends boolean = false>(
    options?: Options<SendVerificationEmailData, ThrowOnError>
) =>
    (options?.client ?? client).post<SendVerificationEmailResponses, SendVerificationEmailErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/send-verification-email',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

export const changeEmail = <ThrowOnError extends boolean = false>(options: Options<ChangeEmailData, ThrowOnError>) =>
    (options.client ?? client).post<ChangeEmailResponses, ChangeEmailErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/change-email',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Change the password of the user
 */
export const changePassword = <ThrowOnError extends boolean = false>(
    options: Options<ChangePasswordData, ThrowOnError>
) =>
    (options.client ?? client).post<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/change-password',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Update the current user
 */
export const updateUser = <ThrowOnError extends boolean = false>(options?: Options<UpdateUserData, ThrowOnError>) =>
    (options?.client ?? client).post<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/update-user',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Delete the user
 */
export const deleteUser = <ThrowOnError extends boolean = false>(options?: Options<DeleteUserData, ThrowOnError>) =>
    (options?.client ?? client).post<DeleteUserResponses, DeleteUserErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/delete-user',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Send a password reset email to the user
 */
export const requestPasswordReset = <ThrowOnError extends boolean = false>(
    options: Options<RequestPasswordResetData, ThrowOnError>
) =>
    (options.client ?? client).post<RequestPasswordResetResponses, RequestPasswordResetErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/request-password-reset',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Redirects the user to the callback URL with the token
 */
export const resetPasswordCallback = <ThrowOnError extends boolean = false>(
    options: Options<ResetPasswordCallbackData, ThrowOnError>
) =>
    (options.client ?? client).get<ResetPasswordCallbackResponses, ResetPasswordCallbackErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/reset-password/{token}',
        ...options
    })

/**
 * List all active sessions for the user
 */
export const listUserSessions = <ThrowOnError extends boolean = false>(
    options?: Options<ListUserSessionsData, ThrowOnError>
) =>
    (options?.client ?? client).get<ListUserSessionsResponses, ListUserSessionsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/list-sessions',
        ...options
    })

/**
 * Revoke a single session
 */
export const postRevokeSession = <ThrowOnError extends boolean = false>(
    options?: Options<PostRevokeSessionData, ThrowOnError>
) =>
    (options?.client ?? client).post<PostRevokeSessionResponses, PostRevokeSessionErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/revoke-session',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Revoke all sessions for the user
 */
export const postRevokeSessions = <ThrowOnError extends boolean = false>(
    options?: Options<PostRevokeSessionsData, ThrowOnError>
) =>
    (options?.client ?? client).post<PostRevokeSessionsResponses, PostRevokeSessionsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/revoke-sessions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Revoke all other sessions for the user except the current one
 */
export const postRevokeOtherSessions = <ThrowOnError extends boolean = false>(
    options?: Options<PostRevokeOtherSessionsData, ThrowOnError>
) =>
    (options?.client ?? client).post<PostRevokeOtherSessionsResponses, PostRevokeOtherSessionsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/revoke-other-sessions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Link a social account to the user
 */
export const linkSocialAccount = <ThrowOnError extends boolean = false>(
    options: Options<LinkSocialAccountData, ThrowOnError>
) =>
    (options.client ?? client).post<LinkSocialAccountResponses, LinkSocialAccountErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/link-social',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * List all accounts linked to the user
 */
export const listUserAccounts = <ThrowOnError extends boolean = false>(
    options?: Options<ListUserAccountsData, ThrowOnError>
) =>
    (options?.client ?? client).get<ListUserAccountsResponses, ListUserAccountsErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/list-accounts',
        ...options
    })

/**
 * Callback to complete user deletion with verification token
 */
export const getDeleteUserCallback = <ThrowOnError extends boolean = false>(
    options?: Options<GetDeleteUserCallbackData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetDeleteUserCallbackResponses, GetDeleteUserCallbackErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/delete-user/callback',
        ...options
    })

/**
 * Unlink an account
 */
export const postUnlinkAccount = <ThrowOnError extends boolean = false>(
    options: Options<PostUnlinkAccountData, ThrowOnError>
) =>
    (options.client ?? client).post<PostUnlinkAccountResponses, PostUnlinkAccountErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/unlink-account',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Refresh the access token using a refresh token
 */
export const postRefreshToken = <ThrowOnError extends boolean = false>(
    options: Options<PostRefreshTokenData, ThrowOnError>
) =>
    (options.client ?? client).post<PostRefreshTokenResponses, PostRefreshTokenErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/refresh-token',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Get a valid access token, doing a refresh if needed
 */
export const postGetAccessToken = <ThrowOnError extends boolean = false>(
    options: Options<PostGetAccessTokenData, ThrowOnError>
) =>
    (options.client ?? client).post<PostGetAccessTokenResponses, PostGetAccessTokenErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/get-access-token',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    })

/**
 * Get the account info provided by the provider
 */
export const getAccountInfo = <ThrowOnError extends boolean = false>(
    options?: Options<GetAccountInfoData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetAccountInfoResponses, GetAccountInfoErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/account-info',
        ...options
    })

/**
 * Check if the API is working
 */
export const getOk = <ThrowOnError extends boolean = false>(options?: Options<GetOkData, ThrowOnError>) =>
    (options?.client ?? client).get<GetOkResponses, GetOkErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/ok',
        ...options
    })

/**
 * Displays an error page
 */
export const getError = <ThrowOnError extends boolean = false>(options?: Options<GetErrorData, ThrowOnError>) =>
    (options?.client ?? client).get<GetErrorResponses, GetErrorErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/error',
        ...options
    })

export const getCallbackById = <ThrowOnError extends boolean = false>(
    options?: Options<GetCallbackByIdData, ThrowOnError>
) =>
    (options?.client ?? client).get<unknown, GetCallbackByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/callback/{id}',
        ...options
    })

export const postCallbackById = <ThrowOnError extends boolean = false>(
    options?: Options<PostCallbackByIdData, ThrowOnError>
) =>
    (options?.client ?? client).post<unknown, PostCallbackByIdErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/callback/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })

/**
 * Update the current session
 */
export const updateSession = <ThrowOnError extends boolean = false>(
    options?: Options<UpdateSessionData, ThrowOnError>
) =>
    (options?.client ?? client).post<UpdateSessionResponses, UpdateSessionErrors, ThrowOnError>({
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/update-session',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })
