// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js'
import type { Client, Options as Options2, TDataShape } from './client/index.js'
import type {
    DeleteAccountsByIdData,
    DeleteAccountsByIdResponses,
    DeleteCategoriesByIdData,
    DeleteCategoriesByIdResponses,
    DeleteSessionsByIdData,
    DeleteSessionsByIdResponses,
    DeleteSnapshotsByIdData,
    DeleteSnapshotsByIdResponses,
    DeleteSubcategoriesByIdData,
    DeleteSubcategoriesByIdResponses,
    DeleteTransactionsByIdData,
    DeleteTransactionsByIdResponses,
    DeleteUsersByIdData,
    DeleteUsersByIdResponses,
    GetAccountsByIdData,
    GetAccountsByIdErrors,
    GetAccountsByIdResponses,
    GetAccountsData,
    GetAccountsResponses,
    GetCategoriesByIdData,
    GetCategoriesByIdErrors,
    GetCategoriesByIdResponses,
    GetCategoriesData,
    GetCategoriesResponses,
    GetRootStatusData,
    GetRootStatusErrors,
    GetRootStatusResponses,
    GetSessionsByIdData,
    GetSessionsByIdErrors,
    GetSessionsByIdResponses,
    GetSessionsData,
    GetSessionsResponses,
    GetSnapshotsByIdData,
    GetSnapshotsByIdErrors,
    GetSnapshotsByIdResponses,
    GetSnapshotsData,
    GetSnapshotsResponses,
    GetStatusData,
    GetStatusErrors,
    GetStatusResponses,
    GetSubcategoriesByIdData,
    GetSubcategoriesByIdErrors,
    GetSubcategoriesByIdResponses,
    GetSubcategoriesData,
    GetSubcategoriesResponses,
    GetTransactionsByIdData,
    GetTransactionsByIdErrors,
    GetTransactionsByIdResponses,
    GetTransactionsData,
    GetTransactionsResponses,
    GetUserData,
    GetUserErrors,
    GetUserResponses,
    GetUsersByIdData,
    GetUsersByIdErrors,
    GetUsersByIdResponses,
    GetUsersData,
    GetUsersResponses,
    PostAccountsData,
    PostAccountsResponses,
    PostCategoriesData,
    PostCategoriesResponses,
    PostSessionsData,
    PostSessionsResponses,
    PostSnapshotsData,
    PostSnapshotsResponses,
    PostSubcategoriesData,
    PostSubcategoriesResponses,
    PostTransactionsData,
    PostTransactionsResponses,
    PostUsersData,
    PostUsersResponses,
    PutAccountsByIdData,
    PutAccountsByIdResponses,
    PutCategoriesByIdData,
    PutCategoriesByIdResponses,
    PutSessionsByIdData,
    PutSessionsByIdResponses,
    PutSnapshotsByIdData,
    PutSnapshotsByIdResponses,
    PutSubcategoriesByIdData,
    PutSubcategoriesByIdResponses,
    PutTransactionsByIdData,
    PutTransactionsByIdResponses,
    PutUserData,
    PutUserErrors,
    PutUserResponses,
    PutUsersByIdData,
    PutUsersByIdResponses
} from './types.gen.js'

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
    TData,
    ThrowOnError
> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>
}

/**
 * Healthcheck
 */
export const getRootStatus = <ThrowOnError extends boolean = false>(
    options?: Options<GetRootStatusData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetRootStatusResponses, GetRootStatusErrors, ThrowOnError>({ url: '/', ...options })

/**
 * Healthcheck
 */
export const getStatus = <ThrowOnError extends boolean = false>(options?: Options<GetStatusData, ThrowOnError>) =>
    (options?.client ?? client).get<GetStatusResponses, GetStatusErrors, ThrowOnError>({ url: '/status', ...options })

/**
 * Get all users
 */
export const getUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>) =>
    (options?.client ?? client).get<GetUsersResponses, unknown, ThrowOnError>({ url: '/users', ...options })

/**
 * Create user
 */
export const postUsers = <ThrowOnError extends boolean = false>(options?: Options<PostUsersData, ThrowOnError>) =>
    (options?.client ?? client).post<PostUsersResponses, unknown, ThrowOnError>({ url: '/users', ...options })

/**
 * Delete user
 */
export const deleteUsersById = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteUsersByIdData, ThrowOnError>
) =>
    (options?.client ?? client).delete<DeleteUsersByIdResponses, unknown, ThrowOnError>({
        url: '/users/{id}',
        ...options
    })

/**
 * Get user by ID
 */
export const getUsersById = <ThrowOnError extends boolean = false>(options?: Options<GetUsersByIdData, ThrowOnError>) =>
    (options?.client ?? client).get<GetUsersByIdResponses, GetUsersByIdErrors, ThrowOnError>({
        url: '/users/{id}',
        ...options
    })

/**
 * Update user
 */
export const putUsersById = <ThrowOnError extends boolean = false>(options?: Options<PutUsersByIdData, ThrowOnError>) =>
    (options?.client ?? client).put<PutUsersByIdResponses, unknown, ThrowOnError>({ url: '/users/{id}', ...options })

/**
 * Get all transactions
 */
export const getTransactions = <ThrowOnError extends boolean = false>(
    options?: Options<GetTransactionsData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetTransactionsResponses, unknown, ThrowOnError>({
        url: '/transactions',
        ...options
    })

/**
 * Create transaction
 */
export const postTransactions = <ThrowOnError extends boolean = false>(
    options?: Options<PostTransactionsData, ThrowOnError>
) =>
    (options?.client ?? client).post<PostTransactionsResponses, unknown, ThrowOnError>({
        url: '/transactions',
        ...options
    })

/**
 * Delete transaction
 */
export const deleteTransactionsById = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteTransactionsByIdData, ThrowOnError>
) =>
    (options?.client ?? client).delete<DeleteTransactionsByIdResponses, unknown, ThrowOnError>({
        url: '/transactions/{id}',
        ...options
    })

/**
 * Get transaction by ID
 */
export const getTransactionsById = <ThrowOnError extends boolean = false>(
    options?: Options<GetTransactionsByIdData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetTransactionsByIdResponses, GetTransactionsByIdErrors, ThrowOnError>({
        url: '/transactions/{id}',
        ...options
    })

/**
 * Update transaction
 */
export const putTransactionsById = <ThrowOnError extends boolean = false>(
    options?: Options<PutTransactionsByIdData, ThrowOnError>
) =>
    (options?.client ?? client).put<PutTransactionsByIdResponses, unknown, ThrowOnError>({
        url: '/transactions/{id}',
        ...options
    })

/**
 * Get all accounts
 */
export const getAccounts = <ThrowOnError extends boolean = false>(options?: Options<GetAccountsData, ThrowOnError>) =>
    (options?.client ?? client).get<GetAccountsResponses, unknown, ThrowOnError>({ url: '/accounts', ...options })

/**
 * Create account
 */
export const postAccounts = <ThrowOnError extends boolean = false>(options?: Options<PostAccountsData, ThrowOnError>) =>
    (options?.client ?? client).post<PostAccountsResponses, unknown, ThrowOnError>({ url: '/accounts', ...options })

/**
 * Delete account
 */
export const deleteAccountsById = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteAccountsByIdData, ThrowOnError>
) =>
    (options?.client ?? client).delete<DeleteAccountsByIdResponses, unknown, ThrowOnError>({
        url: '/accounts/{id}',
        ...options
    })

/**
 * Get account by ID
 */
export const getAccountsById = <ThrowOnError extends boolean = false>(
    options?: Options<GetAccountsByIdData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetAccountsByIdResponses, GetAccountsByIdErrors, ThrowOnError>({
        url: '/accounts/{id}',
        ...options
    })

/**
 * Update account
 */
export const putAccountsById = <ThrowOnError extends boolean = false>(
    options?: Options<PutAccountsByIdData, ThrowOnError>
) =>
    (options?.client ?? client).put<PutAccountsByIdResponses, unknown, ThrowOnError>({
        url: '/accounts/{id}',
        ...options
    })

/**
 * Get all categories
 */
export const getCategories = <ThrowOnError extends boolean = false>(
    options?: Options<GetCategoriesData, ThrowOnError>
) => (options?.client ?? client).get<GetCategoriesResponses, unknown, ThrowOnError>({ url: '/categories', ...options })

/**
 * Create category
 */
export const postCategories = <ThrowOnError extends boolean = false>(
    options?: Options<PostCategoriesData, ThrowOnError>
) =>
    (options?.client ?? client).post<PostCategoriesResponses, unknown, ThrowOnError>({ url: '/categories', ...options })

/**
 * Delete category
 */
export const deleteCategoriesById = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteCategoriesByIdData, ThrowOnError>
) =>
    (options?.client ?? client).delete<DeleteCategoriesByIdResponses, unknown, ThrowOnError>({
        url: '/categories/{id}',
        ...options
    })

/**
 * Get category by ID
 */
export const getCategoriesById = <ThrowOnError extends boolean = false>(
    options?: Options<GetCategoriesByIdData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetCategoriesByIdResponses, GetCategoriesByIdErrors, ThrowOnError>({
        url: '/categories/{id}',
        ...options
    })

/**
 * Update category
 */
export const putCategoriesById = <ThrowOnError extends boolean = false>(
    options?: Options<PutCategoriesByIdData, ThrowOnError>
) =>
    (options?.client ?? client).put<PutCategoriesByIdResponses, unknown, ThrowOnError>({
        url: '/categories/{id}',
        ...options
    })

/**
 * Get all subcategories
 */
export const getSubcategories = <ThrowOnError extends boolean = false>(
    options?: Options<GetSubcategoriesData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetSubcategoriesResponses, unknown, ThrowOnError>({
        url: '/subcategories',
        ...options
    })

/**
 * Create subcategory
 */
export const postSubcategories = <ThrowOnError extends boolean = false>(
    options?: Options<PostSubcategoriesData, ThrowOnError>
) =>
    (options?.client ?? client).post<PostSubcategoriesResponses, unknown, ThrowOnError>({
        url: '/subcategories',
        ...options
    })

/**
 * Delete subcategory
 */
export const deleteSubcategoriesById = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteSubcategoriesByIdData, ThrowOnError>
) =>
    (options?.client ?? client).delete<DeleteSubcategoriesByIdResponses, unknown, ThrowOnError>({
        url: '/subcategories/{id}',
        ...options
    })

/**
 * Get subcategory by ID
 */
export const getSubcategoriesById = <ThrowOnError extends boolean = false>(
    options?: Options<GetSubcategoriesByIdData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetSubcategoriesByIdResponses, GetSubcategoriesByIdErrors, ThrowOnError>({
        url: '/subcategories/{id}',
        ...options
    })

/**
 * Update subcategory
 */
export const putSubcategoriesById = <ThrowOnError extends boolean = false>(
    options?: Options<PutSubcategoriesByIdData, ThrowOnError>
) =>
    (options?.client ?? client).put<PutSubcategoriesByIdResponses, unknown, ThrowOnError>({
        url: '/subcategories/{id}',
        ...options
    })

/**
 * Get all snapshots
 */
export const getSnapshots = <ThrowOnError extends boolean = false>(options?: Options<GetSnapshotsData, ThrowOnError>) =>
    (options?.client ?? client).get<GetSnapshotsResponses, unknown, ThrowOnError>({ url: '/snapshots', ...options })

/**
 * Create snapshot
 */
export const postSnapshots = <ThrowOnError extends boolean = false>(
    options?: Options<PostSnapshotsData, ThrowOnError>
) => (options?.client ?? client).post<PostSnapshotsResponses, unknown, ThrowOnError>({ url: '/snapshots', ...options })

/**
 * Delete snapshot
 */
export const deleteSnapshotsById = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteSnapshotsByIdData, ThrowOnError>
) =>
    (options?.client ?? client).delete<DeleteSnapshotsByIdResponses, unknown, ThrowOnError>({
        url: '/snapshots/{id}',
        ...options
    })

/**
 * Get snapshot by ID
 */
export const getSnapshotsById = <ThrowOnError extends boolean = false>(
    options?: Options<GetSnapshotsByIdData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetSnapshotsByIdResponses, GetSnapshotsByIdErrors, ThrowOnError>({
        url: '/snapshots/{id}',
        ...options
    })

/**
 * Update snapshot
 */
export const putSnapshotsById = <ThrowOnError extends boolean = false>(
    options?: Options<PutSnapshotsByIdData, ThrowOnError>
) =>
    (options?.client ?? client).put<PutSnapshotsByIdResponses, unknown, ThrowOnError>({
        url: '/snapshots/{id}',
        ...options
    })

/**
 * Get all sessions
 */
export const getSessions = <ThrowOnError extends boolean = false>(options?: Options<GetSessionsData, ThrowOnError>) =>
    (options?.client ?? client).get<GetSessionsResponses, unknown, ThrowOnError>({ url: '/sessions', ...options })

/**
 * Create session
 */
export const postSessions = <ThrowOnError extends boolean = false>(options?: Options<PostSessionsData, ThrowOnError>) =>
    (options?.client ?? client).post<PostSessionsResponses, unknown, ThrowOnError>({ url: '/sessions', ...options })

/**
 * Delete session
 */
export const deleteSessionsById = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteSessionsByIdData, ThrowOnError>
) =>
    (options?.client ?? client).delete<DeleteSessionsByIdResponses, unknown, ThrowOnError>({
        url: '/sessions/{id}',
        ...options
    })

/**
 * Get session by ID
 */
export const getSessionsById = <ThrowOnError extends boolean = false>(
    options?: Options<GetSessionsByIdData, ThrowOnError>
) =>
    (options?.client ?? client).get<GetSessionsByIdResponses, GetSessionsByIdErrors, ThrowOnError>({
        url: '/sessions/{id}',
        ...options
    })

/**
 * Update session
 */
export const putSessionsById = <ThrowOnError extends boolean = false>(
    options?: Options<PutSessionsByIdData, ThrowOnError>
) =>
    (options?.client ?? client).put<PutSessionsByIdResponses, unknown, ThrowOnError>({
        url: '/sessions/{id}',
        ...options
    })

/**
 * Get user
 *
 * Get user information and preferences
 */
export const getUser = <ThrowOnError extends boolean = false>(options?: Options<GetUserData, ThrowOnError>) =>
    (options?.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({ url: '/user', ...options })

/**
 * Update user
 *
 * Update user preferences and information
 */
export const putUser = <ThrowOnError extends boolean = false>(options?: Options<PutUserData, ThrowOnError>) =>
    (options?.client ?? client).put<PutUserResponses, PutUserErrors, ThrowOnError>({
        url: '/user',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    })
