// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3001/v1' | 'http://api.poveroh.local/v1' | 'http://api.poveroh.com/v1' | (string & {})
}

export type TimezoneEnum =
    | 'AFRICA_ALGIERS'
    | 'AFRICA_CAIRO'
    | 'AFRICA_CASABLANCA'
    | 'AFRICA_HARARE'
    | 'AFRICA_JOHANNESBURG'
    | 'AFRICA_MONROVIA'
    | 'AFRICA_NAIROBI'
    | 'AFRICA_WEST_CENTRAL'
    | 'AMERICA_ARGENTINA_BUENOS_AIRES'
    | 'AMERICA_BOGOTA'
    | 'AMERICA_CARACAS'
    | 'AMERICA_CHICAGO'
    | 'AMERICA_CHIHUAHUA'
    | 'AMERICA_DENVER'
    | 'AMERICA_GUATEMALA'
    | 'AMERICA_GUYANA'
    | 'AMERICA_HALIFAX'
    | 'AMERICA_INDIANA_INDIANAPOLIS'
    | 'AMERICA_JUNEAU'
    | 'AMERICA_LA_PAZ'
    | 'AMERICA_LIMA'
    | 'AMERICA_QUITO'
    | 'AMERICA_LOS_ANGELES'
    | 'AMERICA_MAZATLAN'
    | 'AMERICA_MEXICO_CITY'
    | 'AMERICA_GUADALAJARA'
    | 'AMERICA_MONTERREY'
    | 'AMERICA_MONTEVIDEO'
    | 'AMERICA_NEW_YORK'
    | 'AMERICA_PHOENIX'
    | 'AMERICA_PUERTO_RICO'
    | 'AMERICA_REGINA'
    | 'AMERICA_SANTIAGO'
    | 'AMERICA_SAO_PAULO'
    | 'AMERICA_ST_JOHNS'
    | 'AMERICA_TIJUANA'
    | 'ASIA_ALMATY'
    | 'ASIA_ASTANA'
    | 'ASIA_BAGHDAD'
    | 'ASIA_BAKU'
    | 'ASIA_BANGKOK'
    | 'ASIA_CHENNAI'
    | 'ASIA_HANOI'
    | 'ASIA_CHONGQING'
    | 'ASIA_COLOMBO'
    | 'ASIA_DHAKA'
    | 'ASIA_HONG_KONG'
    | 'ASIA_IRKUTSK'
    | 'ASIA_JAKARTA'
    | 'ASIA_JERUSALEM'
    | 'ASIA_KABUL'
    | 'ASIA_KAMCHATKA'
    | 'ASIA_KARACHI'
    | 'ASIA_ISLAMABAD'
    | 'ASIA_KATHMANDU'
    | 'ASIA_KOLKATA'
    | 'ASIA_MUMBAI'
    | 'ASIA_NEW_DELHI'
    | 'ASIA_KRASNOYARSK'
    | 'ASIA_KUALA_LUMPUR'
    | 'ASIA_KUWAIT'
    | 'ASIA_MAGADAN'
    | 'ASIA_MUSCAT'
    | 'ASIA_ABU_DHABI'
    | 'ASIA_NOVOSIBIRSK'
    | 'ASIA_RIYADH'
    | 'ASIA_SEOUL'
    | 'ASIA_SHANGHAI'
    | 'ASIA_SINGAPORE'
    | 'ASIA_SREDNEKOLYMSK'
    | 'ASIA_TAIPEI'
    | 'ASIA_TASHKENT'
    | 'ASIA_TBILISI'
    | 'ASIA_TEHRAN'
    | 'ASIA_TOKYO'
    | 'ASIA_OSAKA'
    | 'ASIA_SAPPORO'
    | 'ASIA_ULAANBAATAR'
    | 'ASIA_URUMQI'
    | 'ASIA_VLADIVOSTOK'
    | 'ASIA_YAKUTSK'
    | 'ASIA_YEKATERINBURG'
    | 'ASIA_YEREVAN'
    | 'ATLANTIC_AZORES'
    | 'ATLANTIC_CAPE_VERDE'
    | 'ATLANTIC_SOUTH_GEORGIA'
    | 'AUSTRALIA_ADELAIDE'
    | 'AUSTRALIA_BRISBANE'
    | 'AUSTRALIA_CANBERRA'
    | 'AUSTRALIA_DARWIN'
    | 'AUSTRALIA_HOBART'
    | 'AUSTRALIA_MELBOURNE'
    | 'AUSTRALIA_PERTH'
    | 'AUSTRALIA_SYDNEY'
    | 'ETC_GMT_PLUS_12'
    | 'ETC_UTC'
    | 'EUROPE_AMSTERDAM'
    | 'EUROPE_ATHENS'
    | 'EUROPE_BELGRADE'
    | 'EUROPE_BERN'
    | 'EUROPE_BERLIN'
    | 'EUROPE_BRATISLAVA'
    | 'EUROPE_BRUSSELS'
    | 'EUROPE_BUCHAREST'
    | 'EUROPE_BUDAPEST'
    | 'EUROPE_COPENHAGEN'
    | 'EUROPE_DUBLIN'
    | 'EUROPE_HELSINKI'
    | 'EUROPE_ISTANBUL'
    | 'EUROPE_KALININGRAD'
    | 'EUROPE_LISBON'
    | 'EUROPE_LJUBLJANA'
    | 'EUROPE_LONDON'
    | 'EUROPE_EDINBURGH'
    | 'EUROPE_MADRID'
    | 'EUROPE_MINSK'
    | 'EUROPE_MOSCOW'
    | 'EUROPE_ST_PETERSBURG'
    | 'EUROPE_PARIS'
    | 'EUROPE_PRAGUE'
    | 'EUROPE_RIGA'
    | 'EUROPE_ROME'
    | 'EUROPE_SAMARA'
    | 'EUROPE_SARAJEVO'
    | 'EUROPE_SKOPJE'
    | 'EUROPE_SOFIA'
    | 'EUROPE_STOCKHOLM'
    | 'EUROPE_TALLINN'
    | 'EUROPE_VIENNA'
    | 'EUROPE_VILNIUS'
    | 'EUROPE_VOLGOGRAD'
    | 'EUROPE_WARSAW'
    | 'EUROPE_ZAGREB'
    | 'EUROPE_ZURICH'
    | 'PACIFIC_APIA'
    | 'PACIFIC_AUCKLAND'
    | 'PACIFIC_WELLINGTON'
    | 'PACIFIC_CHATHAM'
    | 'PACIFIC_FAKAOFO'
    | 'PACIFIC_FIJI'
    | 'PACIFIC_GUADALCANAL'
    | 'PACIFIC_GUAM'
    | 'PACIFIC_HONOLULU'
    | 'PACIFIC_MAJURO'
    | 'PACIFIC_MIDWAY'
    | 'PACIFIC_NOUMEA'
    | 'PACIFIC_PAGO_PAGO'
    | 'PACIFIC_PORT_MORESBY'
    | 'PACIFIC_TONGATAPU'

export type SnapshotFrequencyEnum = 'NONE' | 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'QUARTERLY' | 'SEMIANNUAL' | 'ANNUAL'

export type AssetTypeEnum =
    | 'STOCK'
    | 'BOND'
    | 'ETF'
    | 'MUTUAL_FUND'
    | 'CRYPTOCURRENCY'
    | 'REAL_ESTATE'
    | 'COLLECTIBLE'
    | 'PRIVATE_EQUITY'
    | 'VENTURE_CAPITAL'
    | 'PRIVATE_DEBT'
    | 'P2P_LENDING'
    | 'INSURANCE_POLICY'
    | 'AGRICULTURAL_LAND'
    | 'OTHER'

export type FinancialAccountTypeEnum =
    | 'ONLINE_BANK'
    | 'BANK_ACCOUNT'
    | 'CIRCUIT'
    | 'DEPOSIT_BANK'
    | 'BROKER'
    | 'WALLET'
    | 'CASH'
    | 'CREDIT_CARD'
    | 'OTHER'

export type TransactionActionEnum = 'EXPENSES' | 'INCOME' | 'TRANSFER'

export type TransactionStatusEnum = 'APPROVED' | 'REJECTED' | 'IMPORT_PENDING' | 'IMPORT_REJECTED' | 'IMPORT_APPROVED'

export type CurrencyEnum =
    | 'USD'
    | 'EUR'
    | 'GBP'
    | 'JPY'
    | 'CNY'
    | 'INR'
    | 'AUD'
    | 'CAD'
    | 'CHF'
    | 'SEK'
    | 'NZD'
    | 'MXN'
    | 'SGD'
    | 'HKD'
    | 'NOK'
    | 'KRW'
    | 'TRY'
    | 'UNKNOWN'

export type RememberPeriodEnum =
    | 'SAME_DAY'
    | 'THREE_DAYS'
    | 'SEVEN_DAYS'
    | 'FOURTEEN_DAYS'
    | 'THIRTY_DAYS'
    | 'NINETY_DAYS'

export type AppearanceModeEnum = 'LOGO' | 'ICON'

export type FileTypeEnum = 'CSV' | 'PDF'

export type LanguageEnum =
    | 'EN'
    | 'ES'
    | 'FR'
    | 'DE'
    | 'IT'
    | 'PT'
    | 'NL'
    | 'RU'
    | 'ZH'
    | 'JA'
    | 'KO'
    | 'AR'
    | 'HI'
    | 'TH'
    | 'VI'
    | 'TR'
    | 'PL'
    | 'CS'
    | 'HU'
    | 'RO'
    | 'BG'
    | 'HR'
    | 'SK'
    | 'SL'
    | 'ET'
    | 'LV'
    | 'LT'
    | 'MT'
    | 'FI'
    | 'SV'
    | 'DA'
    | 'NO'
    | 'IS'
    | 'EL'
    | 'HE'
    | 'FA'
    | 'UR'
    | 'BN'
    | 'TA'
    | 'TE'
    | 'ML'
    | 'KN'
    | 'GU'
    | 'MR'
    | 'PA'
    | 'OR'
    | 'AS'
    | 'NE'
    | 'SI'
    | 'MY'
    | 'KH'
    | 'LO'
    | 'KA'
    | 'AM'
    | 'TI'
    | 'SW'
    | 'ZU'
    | 'AF'
    | 'XH'
    | 'ST'
    | 'TN'
    | 'SS'
    | 'VE'
    | 'TS'
    | 'NR'
    | 'IG'
    | 'YO'
    | 'HA'
    | 'FF'
    | 'WO'
    | 'BM'
    | 'DY'
    | 'SN'

export type DateFormatEnum =
    | 'DD_MM_YYYY'
    | 'MM_DD_YYYY'
    | 'YYYY_MM_DD'
    | 'DD_MM_YY'
    | 'MM_DD_YY'
    | 'YY_MM_DD'
    | 'DD_MMMM_YYYY'
    | 'MMMM_DD_YYYY'
    | 'YYYY_MMMM_DD'

export type OnBoardingStepEnum = 'EMAIL' | 'GENERALITES' | 'PREFERENCES' | 'COMPLETED'

export type CountriesEnum =
    | 'AFGHANISTAN'
    | 'ALBANIA'
    | 'ALGERIA'
    | 'ANDORRA'
    | 'ANGOLA'
    | 'ANTIGUA_AND_BARBUDA'
    | 'ARGENTINA'
    | 'ARMENIA'
    | 'AUSTRALIA'
    | 'AUSTRIA'
    | 'AZERBAIJAN'
    | 'BAHAMAS'
    | 'BAHRAIN'
    | 'BANGLADESH'
    | 'BARBADOS'
    | 'BELARUS'
    | 'BELGIUM'
    | 'BELIZE'
    | 'BENIN'
    | 'BHUTAN'
    | 'BOLIVIA'
    | 'BOSNIA_AND_HERZEGOVINA'
    | 'BOTSWANA'
    | 'BRAZIL'
    | 'BRUNEI'
    | 'BULGARIA'
    | 'BURKINA_FASO'
    | 'BURUNDI'
    | 'CABO_VERDE'
    | 'CAMBODIA'
    | 'CAMEROON'
    | 'CANADA'
    | 'CENTRAL_AFRICAN_REPUBLIC'
    | 'CHAD'
    | 'CHILE'
    | 'CHINA'
    | 'COLOMBIA'
    | 'COMOROS'
    | 'CONGO_DEMOCRATIC_REPUBLIC'
    | 'CONGO_REPUBLIC'
    | 'COSTA_RICA'
    | 'CROATIA'
    | 'CUBA'
    | 'CYPRUS'
    | 'CZECH_REPUBLIC'
    | 'DENMARK'
    | 'DJIBOUTI'
    | 'DOMINICA'
    | 'DOMINICAN_REPUBLIC'
    | 'ECUADOR'
    | 'EGYPT'
    | 'EL_SALVADOR'
    | 'EQUATORIAL_GUINEA'
    | 'ERITREA'
    | 'ESTONIA'
    | 'ESWATINI'
    | 'ETHIOPIA'
    | 'FIJI'
    | 'FINLAND'
    | 'FRANCE'
    | 'GABON'
    | 'GAMBIA'
    | 'GEORGIA'
    | 'GERMANY'
    | 'GHANA'
    | 'GREECE'
    | 'GRENADA'
    | 'GUATEMALA'
    | 'GUINEA'
    | 'GUINEA_BISSAU'
    | 'GUYANA'
    | 'HAITI'
    | 'HONDURAS'
    | 'HUNGARY'
    | 'ICELAND'
    | 'INDIA'
    | 'INDONESIA'
    | 'IRAN'
    | 'IRAQ'
    | 'IRELAND'
    | 'ISRAEL'
    | 'ITALY'
    | 'JAMAICA'
    | 'JAPAN'
    | 'JORDAN'
    | 'KAZAKHSTAN'
    | 'KENYA'
    | 'KIRIBATI'
    | 'KOREA_NORTH'
    | 'KOREA_SOUTH'
    | 'KUWAIT'
    | 'KYRGYZSTAN'
    | 'LAOS'
    | 'LATVIA'
    | 'LEBANON'
    | 'LESOTHO'
    | 'LIBERIA'
    | 'LIBYA'
    | 'LIECHTENSTEIN'
    | 'LITHUANIA'
    | 'LUXEMBOURG'
    | 'MADAGASCAR'
    | 'MALAWI'
    | 'MALAYSIA'
    | 'MALDIVES'
    | 'MALI'
    | 'MALTA'
    | 'MARSHALL_ISLANDS'
    | 'MAURITANIA'
    | 'MAURITIUS'
    | 'MEXICO'
    | 'MICRONESIA'
    | 'MOLDOVA'
    | 'MONACO'
    | 'MONGOLIA'
    | 'MONTENEGRO'
    | 'MOROCCO'
    | 'MOZAMBIQUE'
    | 'MYANMAR'
    | 'NAMIBIA'
    | 'NAURU'
    | 'NEPAL'
    | 'NETHERLANDS'
    | 'NEW_ZEALAND'
    | 'NICARAGUA'
    | 'NIGER'
    | 'NIGERIA'
    | 'NORTH_MACEDONIA'
    | 'NORWAY'
    | 'OMAN'
    | 'PAKISTAN'
    | 'PALAU'
    | 'PALESTINE'
    | 'PANAMA'
    | 'PAPUA_NEW_GUINEA'
    | 'PARAGUAY'
    | 'PERU'
    | 'PHILIPPINES'
    | 'POLAND'
    | 'PORTUGAL'
    | 'QATAR'
    | 'ROMANIA'
    | 'RUSSIA'
    | 'RWANDA'
    | 'SAINT_KITTS_AND_NEVIS'
    | 'SAINT_LUCIA'
    | 'SAINT_VINCENT_AND_GRENADINES'
    | 'SAMOA'
    | 'SAN_MARINO'
    | 'SAO_TOME_AND_PRINCIPE'
    | 'SAUDI_ARABIA'
    | 'SENEGAL'
    | 'SERBIA'
    | 'SEYCHELLES'
    | 'SIERRA_LEONE'
    | 'SINGAPORE'
    | 'SLOVAKIA'
    | 'SLOVENIA'
    | 'SOLOMON_ISLANDS'
    | 'SOMALIA'
    | 'SOUTH_AFRICA'
    | 'SOUTH_SUDAN'
    | 'SPAIN'
    | 'SRI_LANKA'
    | 'SUDAN'
    | 'SURINAME'
    | 'SWEDEN'
    | 'SWITZERLAND'
    | 'SYRIA'
    | 'TAIWAN'
    | 'TAJIKISTAN'
    | 'TANZANIA'
    | 'THAILAND'
    | 'TIMOR_LESTE'
    | 'TOGO'
    | 'TONGA'
    | 'TRINIDAD_AND_TOBAGO'
    | 'TUNISIA'
    | 'TURKEY'
    | 'TURKMENISTAN'
    | 'TUVALU'
    | 'UGANDA'
    | 'UKRAINE'
    | 'UNITED_ARAB_EMIRATES'
    | 'UNITED_KINGDOM'
    | 'UNITED_STATES'
    | 'URUGUAY'
    | 'UZBEKISTAN'
    | 'VANUATU'
    | 'VATICAN_CITY'
    | 'VENEZUELA'
    | 'VIETNAM'
    | 'YEMEN'
    | 'ZAMBIA'
    | 'ZIMBABWE'

export type UserPreferences = {
    snapshotFrequency: SnapshotFrequencyEnum
    preferredCurrency: CurrencyEnum
    preferredLanguage: LanguageEnum
    dateFormat: DateFormatEnum
    country: CountriesEnum
    timezone: TimezoneEnum
}

export type User = {
    id: string
    name: string
    surname: string
    email: string
    emailVerified?: boolean
    onBoardingStep?: OnBoardingStepEnum & unknown
    onBoardingAt: string | null
    image: string | null
    createdAt: string
    updatedAt: string
    snapshotFrequency: SnapshotFrequencyEnum
    preferredCurrency: CurrencyEnum
    preferredLanguage: LanguageEnum
    dateFormat: DateFormatEnum
    country: CountriesEnum
    timezone: TimezoneEnum
}

export type UpdateUserRequest = {
    id?: string
    name?: string
    surname?: string
    email?: string
    emailVerified?: boolean
    onBoardingStep?: OnBoardingStepEnum & unknown
    onBoardingAt?: string | null
    image?: string | null
    createdAt?: string
    updatedAt?: string
    snapshotFrequency?: SnapshotFrequencyEnum
    preferredCurrency?: CurrencyEnum
    preferredLanguage?: LanguageEnum
    dateFormat?: DateFormatEnum
    country?: CountriesEnum
    timezone?: TimezoneEnum
}

export type UserSession = {
    session: {
        id: string
        createdAt: string
        updatedAt: string
        userId: string
        expiresAt: string
        token: string
        ipAddress: string | null
        userAgent: string | null
    }
    user: User
}

export type UserLogin = {
    email: string
    password: string
}

export type Transaction = {
    id: string
    userId: string
    title: string
    action: string
    categoryId: string | null
    subcategoryId: string | null
    icon: string | null
    date: string
    note: string | null
    ignore: boolean
    createdAt: string
    status: string
    importId: string | null
    updatedAt: string
    amounts: Array<unknown>
    media: Array<unknown>
    transferId: string | null
    transferHash: string | null
}

export type TransactionRequest = {
    title: string
    date: string
    action: string
    categoryId?: string | null
    subcategoryId?: string | null
    icon?: string | null
    note?: string | null
    ignore?: boolean
    importId?: string | null
    amounts?: Array<unknown>
    media?: Array<unknown>
    transferId?: string | null
}

export type TransactionResponse = {
    data: Transaction
}

export type StringFilter = {
    equals?: string
    contains?: string
}

export type FilterOptions = {
    skip?: number
    take?: number
    sortBy?: string
    sortOrder?: 'asc' | 'desc'
}

export type FinancialAccount = {
    id: string
    userId: string
    title: string
    description: string
    balance: number
    type: FinancialAccountTypeEnum
    logoIcon: string
    createdAt: string
    updatedAt: string
}

export type CreateFinancialAccountRequest = {
    title: string
    description: string
    balance: number
    type: FinancialAccountTypeEnum
    logoIcon: string
}

export type CreateFinancialAccountMultipartRequest = {
    data: CreateFinancialAccountRequest
    /**
     * Optional file upload for the financial account logo icon
     */
    file?: Blob | File
}

export type UpdateFinancialAccountRequest = {
    id?: string
    title?: string
    description?: string
    balance?: number
    type?: FinancialAccountTypeEnum
    logoIcon?: string
}

export type FinancialAccountParamsId = {
    id: string
}

export type FinancialAccountFilters = {
    id?: string
    title?: StringFilter
    description?: StringFilter
    type?: FinancialAccountTypeEnum
    [key: string]:
        | string
        | StringFilter
        | FinancialAccountTypeEnum
        | string
        | StringFilter
        | FinancialAccountTypeEnum
        | undefined
}

export type Category = {
    id: string
    userId: string
    title: string
    description: string | null
    for: string
    logoIcon: string
    color: string
    subcategories: Array<unknown>
    createdAt: string
}

export type CategoryRequest = {
    title: string
    description: string | null
    for: string
    logoIcon: string
    color: string
    subcategories?: Array<unknown>
}

export type CategoryResponse = Category & {
    [key: string]: unknown
}

export type Subcategory = {
    id: string
    categoryId: string
    title: string
    description: string | null
    logoIcon: string
    createdAt: string
}

export type SubcategoryRequest = {
    categoryId: string
    title: string
    description?: string | null
    logoIcon?: string
}

export type SubcategoryResponse = {
    data: Subcategory
}

export type Snapshot = {
    id: string
    snapshotDate: string
    note: string | null
    totalCash: number
    totalInvestments: number
    totalNetWorth: number
    userId: string
}

export type SnapshotRequest = {
    snapshotDate: string
    note?: string | null
    totalCash?: number
    totalInvestments?: number
    totalNetWorth?: number
}

export type SnapshotResponse = {
    data: Snapshot
}

export type Session = {
    id: string
    userId: string
    createdAt: string
    updatedAt: string
}

export type SessionRequest = {
    token?: string
    expiresAt?: string
}

export type SessionResponse = {
    data: Session
}

export type ErrorResponse = {
    /**
     * Always false for error responses
     */
    success: false
    /**
     * Error message describing what went wrong
     */
    message: string
    /**
     * Optional additional error details or context
     */
    error?: unknown
}

export type SimpleSuccessResponse = {
    /**
     * Always true for success responses
     */
    success: true
    /**
     * Optional success message
     */
    message?: string
}

export type StatusResponse = {
    status: string
    uptime: number
    version: string
    timestamp: string
}

export type DashboardLayout = {
    id: string
    userId: string
    version: number
    layout?: unknown
    createdAt: string
    updatedAt: string
}

export type DashboardLayoutRequest = {
    version?: number
    layout?: unknown
}

export type DashboardLayoutResponse = {
    data: DashboardLayout
}

export type ImportFile = {
    id: string
    importId: string
    filename: string
    filetype: string
    path: string
    createdAt: string
}

export type Import = {
    id: string
    userId: string
    title: string
    financialAccountId: string
    status: string
    createdAt: string
    transactions?: Array<unknown>
    files?: Array<ImportFile>
}

export type ImportRequest = {
    title: string
    financialAccountId: string
    files?: Array<{
        filename: string
        filetype: string
        path: string
    }>
}

export type ImportResponse = {
    data: Import
}

export type Subscription = {
    id: string
    userId: string
    title: string
    description: string | null
    amount: number
    currency: string
    appearanceMode: string
    appearanceLogoIcon: string
    firstPayment: string
    cycleNumber: string
    cyclePeriod: string
    rememberPeriod: string
    financialAccountId: string
    isEnabled: boolean
    createdAt: string
}

export type SubscriptionRequest = {
    title: string
    description?: string | null
    amount: number
    currency: string
    appearanceMode: string
    appearanceLogoIcon: string
    firstPayment: string
    cycleNumber: string
    cyclePeriod: string
    rememberPeriod: string
    financialAccountId: string
    isEnabled?: boolean
}

export type SubscriptionResponse = {
    data: Subscription
}

export type ReportRequest = {
    from: string
    to: string
    type?: string
}

export type ReportResponse = {
    reportType: string
    totals: {
        [key: string]: number
    }
    metadata?: unknown
}

export type GetRootStatusData = {
    body?: never
    path?: never
    query?: never
    url: '/'
}

export type GetRootStatusErrors = {
    /**
     * Error
     */
    500: ErrorResponse
}

export type GetRootStatusError = GetRootStatusErrors[keyof GetRootStatusErrors]

export type GetRootStatusResponses = {
    /**
     * OK
     */
    200: StatusResponse
}

export type GetRootStatusResponse = GetRootStatusResponses[keyof GetRootStatusResponses]

export type GetStatusData = {
    body?: never
    path?: never
    query?: never
    url: '/status'
}

export type GetStatusErrors = {
    /**
     * Error
     */
    500: ErrorResponse
}

export type GetStatusError = GetStatusErrors[keyof GetStatusErrors]

export type GetStatusResponses = {
    /**
     * OK
     */
    200: StatusResponse
}

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses]

export type GetMeData = {
    body?: never
    path?: never
    query?: never
    url: '/me'
}

export type GetMeErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse
    /**
     * Unauthorized
     */
    401: ErrorResponse
    /**
     * Authenticated user not found
     */
    404: ErrorResponse
    /**
     * Internal server error
     */
    500: ErrorResponse
}

export type GetMeError = GetMeErrors[keyof GetMeErrors]

export type GetMeResponses = {
    /**
     * User found
     */
    200: {
        /**
         * Always true for success responses
         */
        success: true
        /**
         * Optional success message
         */
        message?: string
        data?: User & {
            id: string
            name: string
            surname: string
            email: string
            emailVerified: boolean
            onBoardingStep: OnBoardingStepEnum
            onBoardingAt: string | null
            image: string | null
            createdAt: string
            updatedAt: string
            snapshotFrequency: SnapshotFrequencyEnum
            preferredCurrency: CurrencyEnum
            preferredLanguage: LanguageEnum
            dateFormat: DateFormatEnum
            country: CountriesEnum
            timezone: TimezoneEnum
        }
    }
}

export type GetMeResponse = GetMeResponses[keyof GetMeResponses]

export type PatchMeData = {
    body?: UpdateUserRequest
    path?: never
    query?: never
    url: '/me'
}

export type PatchMeErrors = {
    /**
     * Invalid request body
     */
    400: ErrorResponse
    /**
     * Unauthorized
     */
    401: ErrorResponse
    /**
     * Authenticated user not found
     */
    404: ErrorResponse
    /**
     * Internal server error
     */
    500: ErrorResponse
}

export type PatchMeError = PatchMeErrors[keyof PatchMeErrors]

export type PatchMeResponses = {
    /**
     * User updated
     */
    200: {
        /**
         * Always true for success responses
         */
        success: true
        /**
         * Optional success message
         */
        message?: string
        data?: User & {
            id: string
            name: string
            surname: string
            email: string
            emailVerified: boolean
            onBoardingStep: OnBoardingStepEnum
            onBoardingAt: string | null
            image: string | null
            createdAt: string
            updatedAt: string
            snapshotFrequency: SnapshotFrequencyEnum
            preferredCurrency: CurrencyEnum
            preferredLanguage: LanguageEnum
            dateFormat: DateFormatEnum
            country: CountriesEnum
            timezone: TimezoneEnum
        }
    }
}

export type PatchMeResponse = PatchMeResponses[keyof PatchMeResponses]

export type GetTransactionsData = {
    body?: never
    path?: never
    query?: never
    url: '/transactions'
}

export type GetTransactionsResponses = {
    /**
     * List of transactions
     */
    200: unknown
}

export type PostTransactionsData = {
    body?: never
    path?: never
    query?: never
    url: '/transactions'
}

export type PostTransactionsResponses = {
    /**
     * Transaction created
     */
    201: unknown
}

export type DeleteTransactionsByIdData = {
    body?: never
    path?: never
    query?: never
    url: '/transactions/{id}'
}

export type DeleteTransactionsByIdResponses = {
    /**
     * Transaction deleted
     */
    204: void
}

export type DeleteTransactionsByIdResponse = DeleteTransactionsByIdResponses[keyof DeleteTransactionsByIdResponses]

export type GetTransactionsByIdData = {
    body?: never
    path?: never
    query?: never
    url: '/transactions/{id}'
}

export type GetTransactionsByIdErrors = {
    /**
     * Transaction not found
     */
    404: unknown
}

export type GetTransactionsByIdResponses = {
    /**
     * Transaction found
     */
    200: unknown
}

export type PutTransactionsByIdData = {
    body?: never
    path?: never
    query?: never
    url: '/transactions/{id}'
}

export type PutTransactionsByIdResponses = {
    /**
     * Transaction updated
     */
    200: unknown
}

export type GetFinancialAccountData = {
    body?: never
    path?: never
    query?: {
        filter?: FinancialAccountFilters
        options?: FilterOptions
    }
    url: '/financial-account'
}

export type GetFinancialAccountErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse
    /**
     * Unauthorized
     */
    401: ErrorResponse
    /**
     * Account not found
     */
    404: ErrorResponse
    /**
     * Internal server error
     */
    500: ErrorResponse
}

export type GetFinancialAccountError = GetFinancialAccountErrors[keyof GetFinancialAccountErrors]

export type GetFinancialAccountResponses = {
    /**
     * List of financial accounts
     */
    200: {
        /**
         * Always true for success responses
         */
        success: true
        /**
         * Optional success message
         */
        message?: string
        /**
         * Response data
         */
        data?: Array<FinancialAccount>
    }
}

export type GetFinancialAccountResponse = GetFinancialAccountResponses[keyof GetFinancialAccountResponses]

export type PostFinancialAccountData = {
    /**
     * Financial account data to create
     */
    body: CreateFinancialAccountMultipartRequest
    path?: never
    query?: never
    url: '/financial-account'
}

export type PostFinancialAccountErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse
    /**
     * Unauthorized
     */
    401: ErrorResponse
    /**
     * Internal server error
     */
    500: ErrorResponse
}

export type PostFinancialAccountError = PostFinancialAccountErrors[keyof PostFinancialAccountErrors]

export type PostFinancialAccountResponses = {
    /**
     * Financial account created
     */
    200: {
        /**
         * Always true for success responses
         */
        success: true
        /**
         * Optional success message
         */
        message?: string
        data?: FinancialAccount & unknown
    }
}

export type PostFinancialAccountResponse = PostFinancialAccountResponses[keyof PostFinancialAccountResponses]

export type GetFinancialAccountsByIdData = {
    body?: never
    path: {
        id: string
    }
    query?: never
    url: '/financial-accounts/{id}'
}

export type GetFinancialAccountsByIdErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse
    /**
     * Unauthorized
     */
    401: ErrorResponse
    /**
     * Financial account not found
     */
    404: ErrorResponse
    /**
     * Internal server error
     */
    500: ErrorResponse
}

export type GetFinancialAccountsByIdError = GetFinancialAccountsByIdErrors[keyof GetFinancialAccountsByIdErrors]

export type GetFinancialAccountsByIdResponses = {
    /**
     * Financial account found
     */
    200: {
        /**
         * Always true for success responses
         */
        success: true
        /**
         * Optional success message
         */
        message?: string
        data?: FinancialAccount & unknown
    }
}

export type GetFinancialAccountsByIdResponse =
    GetFinancialAccountsByIdResponses[keyof GetFinancialAccountsByIdResponses]

export type DeleteFinancialAccountByIdData = {
    body?: never
    path: {
        id: string
    }
    query?: never
    url: '/financial-account/{id}'
}

export type DeleteFinancialAccountByIdErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse
    /**
     * Unauthorized
     */
    401: ErrorResponse
    /**
     * Financial account not found
     */
    404: ErrorResponse
    /**
     * Internal server error
     */
    500: ErrorResponse
}

export type DeleteFinancialAccountByIdError = DeleteFinancialAccountByIdErrors[keyof DeleteFinancialAccountByIdErrors]

export type DeleteFinancialAccountByIdResponses = {
    /**
     * Financial account deleted
     */
    200: {
        /**
         * Always true for success responses
         */
        success: true
        /**
         * Optional success message
         */
        message?: string
        /**
         * Response data
         */
        data?: unknown
    }
}

export type DeleteFinancialAccountByIdResponse =
    DeleteFinancialAccountByIdResponses[keyof DeleteFinancialAccountByIdResponses]

export type PatchFinancialAccountByIdData = {
    /**
     * Financial account data to update
     */
    body: UpdateFinancialAccountRequest
    path: {
        id: string
    }
    query?: never
    url: '/financial-account/{id}'
}

export type PatchFinancialAccountByIdErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse
    /**
     * Unauthorized
     */
    401: ErrorResponse
    /**
     * Financial account not found
     */
    404: ErrorResponse
    /**
     * Internal server error
     */
    500: ErrorResponse
}

export type PatchFinancialAccountByIdError = PatchFinancialAccountByIdErrors[keyof PatchFinancialAccountByIdErrors]

export type PatchFinancialAccountByIdResponses = {
    /**
     * Financial account updated
     */
    200: {
        /**
         * Always true for success responses
         */
        success: true
        /**
         * Optional success message
         */
        message?: string
        /**
         * Response data
         */
        data?: unknown
    }
}

export type PatchFinancialAccountByIdResponse =
    PatchFinancialAccountByIdResponses[keyof PatchFinancialAccountByIdResponses]

export type GetCategoriesData = {
    body?: never
    path?: never
    query?: never
    url: '/categories'
}

export type GetCategoriesResponses = {
    /**
     * List of categories
     */
    200: unknown
}

export type PostCategoriesData = {
    body?: never
    path?: never
    query?: never
    url: '/categories'
}

export type PostCategoriesResponses = {
    /**
     * Category created
     */
    201: unknown
}

export type DeleteCategoriesByIdData = {
    body?: never
    path?: never
    query?: never
    url: '/categories/{id}'
}

export type DeleteCategoriesByIdResponses = {
    /**
     * Category deleted
     */
    204: void
}

export type DeleteCategoriesByIdResponse = DeleteCategoriesByIdResponses[keyof DeleteCategoriesByIdResponses]

export type GetCategoriesByIdData = {
    body?: never
    path?: never
    query?: never
    url: '/categories/{id}'
}

export type GetCategoriesByIdErrors = {
    /**
     * Category not found
     */
    404: unknown
}

export type GetCategoriesByIdResponses = {
    /**
     * Category found
     */
    200: unknown
}

export type PutCategoriesByIdData = {
    body?: never
    path?: never
    query?: never
    url: '/categories/{id}'
}

export type PutCategoriesByIdResponses = {
    /**
     * Category updated
     */
    200: unknown
}

export type GetSubcategoriesData = {
    body?: never
    path?: never
    query?: never
    url: '/subcategories'
}

export type GetSubcategoriesResponses = {
    /**
     * List of subcategories
     */
    200: unknown
}

export type PostSubcategoriesData = {
    body?: never
    path?: never
    query?: never
    url: '/subcategories'
}

export type PostSubcategoriesResponses = {
    /**
     * Subcategory created
     */
    201: unknown
}

export type DeleteSubcategoriesByIdData = {
    body?: never
    path?: never
    query?: never
    url: '/subcategories/{id}'
}

export type DeleteSubcategoriesByIdResponses = {
    /**
     * Subcategory deleted
     */
    204: void
}

export type DeleteSubcategoriesByIdResponse = DeleteSubcategoriesByIdResponses[keyof DeleteSubcategoriesByIdResponses]

export type GetSubcategoriesByIdData = {
    body?: never
    path?: never
    query?: never
    url: '/subcategories/{id}'
}

export type GetSubcategoriesByIdErrors = {
    /**
     * Subcategory not found
     */
    404: unknown
}

export type GetSubcategoriesByIdResponses = {
    /**
     * Subcategory found
     */
    200: unknown
}

export type PutSubcategoriesByIdData = {
    body?: never
    path?: never
    query?: never
    url: '/subcategories/{id}'
}

export type PutSubcategoriesByIdResponses = {
    /**
     * Subcategory updated
     */
    200: unknown
}

export type GetSnapshotsData = {
    body?: never
    path?: never
    query?: never
    url: '/snapshots'
}

export type GetSnapshotsResponses = {
    /**
     * List of snapshots
     */
    200: unknown
}

export type PostSnapshotsData = {
    body?: never
    path?: never
    query?: never
    url: '/snapshots'
}

export type PostSnapshotsResponses = {
    /**
     * Snapshot created
     */
    201: unknown
}

export type DeleteSnapshotsByIdData = {
    body?: never
    path?: never
    query?: never
    url: '/snapshots/{id}'
}

export type DeleteSnapshotsByIdResponses = {
    /**
     * Snapshot deleted
     */
    204: void
}

export type DeleteSnapshotsByIdResponse = DeleteSnapshotsByIdResponses[keyof DeleteSnapshotsByIdResponses]

export type GetSnapshotsByIdData = {
    body?: never
    path?: never
    query?: never
    url: '/snapshots/{id}'
}

export type GetSnapshotsByIdErrors = {
    /**
     * Snapshot not found
     */
    404: unknown
}

export type GetSnapshotsByIdResponses = {
    /**
     * Snapshot found
     */
    200: unknown
}

export type PutSnapshotsByIdData = {
    body?: never
    path?: never
    query?: never
    url: '/snapshots/{id}'
}

export type PutSnapshotsByIdResponses = {
    /**
     * Snapshot updated
     */
    200: unknown
}

export type GetSessionsData = {
    body?: never
    path?: never
    query?: never
    url: '/sessions'
}

export type GetSessionsResponses = {
    /**
     * List of sessions
     */
    200: unknown
}

export type PostSessionsData = {
    body?: never
    path?: never
    query?: never
    url: '/sessions'
}

export type PostSessionsResponses = {
    /**
     * Session created
     */
    201: unknown
}

export type DeleteSessionsByIdData = {
    body?: never
    path?: never
    query?: never
    url: '/sessions/{id}'
}

export type DeleteSessionsByIdResponses = {
    /**
     * Session deleted
     */
    204: void
}

export type DeleteSessionsByIdResponse = DeleteSessionsByIdResponses[keyof DeleteSessionsByIdResponses]

export type GetSessionsByIdData = {
    body?: never
    path?: never
    query?: never
    url: '/sessions/{id}'
}

export type GetSessionsByIdErrors = {
    /**
     * Session not found
     */
    404: unknown
}

export type GetSessionsByIdResponses = {
    /**
     * Session found
     */
    200: unknown
}

export type PutSessionsByIdData = {
    body?: never
    path?: never
    query?: never
    url: '/sessions/{id}'
}

export type PutSessionsByIdResponses = {
    /**
     * Session updated
     */
    200: unknown
}
