// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query'

import { client } from '../client.gen.js'
import {
    deleteAccountsById,
    deleteCategoriesById,
    deleteFinancialAccountById,
    deleteSessionsById,
    deleteSnapshotsById,
    deleteSubcategoriesById,
    deleteTransactionsById,
    deleteUsersById,
    getAccounts,
    getAccountsById,
    getCategories,
    getCategoriesById,
    getFinancialAccount,
    getFinancialAccountsById,
    getMe,
    getRootStatus,
    getSessions,
    getSessionsById,
    getSnapshots,
    getSnapshotsById,
    getStatus,
    getSubcategories,
    getSubcategoriesById,
    getTransactions,
    getTransactionsById,
    getUser,
    getUsers,
    getUsersById,
    type Options,
    patchFinancialAccountById,
    patchMe,
    postAccounts,
    postCategories,
    postFinancialAccount,
    postSessions,
    postSnapshots,
    postSubcategories,
    postTransactions,
    postUsers,
    putAccountsById,
    putCategoriesById,
    putSessionsById,
    putSnapshotsById,
    putSubcategoriesById,
    putTransactionsById,
    putUser,
    putUsersById
} from '../sdk.gen.js'
import type {
    DeleteAccountsByIdData,
    DeleteAccountsByIdResponse,
    DeleteCategoriesByIdData,
    DeleteCategoriesByIdResponse,
    DeleteFinancialAccountByIdData,
    DeleteFinancialAccountByIdError,
    DeleteFinancialAccountByIdResponse,
    DeleteSessionsByIdData,
    DeleteSessionsByIdResponse,
    DeleteSnapshotsByIdData,
    DeleteSnapshotsByIdResponse,
    DeleteSubcategoriesByIdData,
    DeleteSubcategoriesByIdResponse,
    DeleteTransactionsByIdData,
    DeleteTransactionsByIdResponse,
    DeleteUsersByIdData,
    DeleteUsersByIdResponse,
    GetAccountsByIdData,
    GetAccountsData,
    GetCategoriesByIdData,
    GetCategoriesData,
    GetFinancialAccountData,
    GetFinancialAccountError,
    GetFinancialAccountResponse,
    GetFinancialAccountsByIdData,
    GetFinancialAccountsByIdError,
    GetFinancialAccountsByIdResponse,
    GetMeData,
    GetMeError,
    GetMeResponse,
    GetRootStatusData,
    GetRootStatusError,
    GetRootStatusResponse,
    GetSessionsByIdData,
    GetSessionsData,
    GetSnapshotsByIdData,
    GetSnapshotsData,
    GetStatusData,
    GetStatusError,
    GetStatusResponse,
    GetSubcategoriesByIdData,
    GetSubcategoriesData,
    GetTransactionsByIdData,
    GetTransactionsData,
    GetUserData,
    GetUserError,
    GetUserResponse,
    GetUsersByIdData,
    GetUsersData,
    PatchFinancialAccountByIdData,
    PatchFinancialAccountByIdError,
    PatchFinancialAccountByIdResponse,
    PatchMeData,
    PatchMeError,
    PatchMeResponse,
    PostAccountsData,
    PostCategoriesData,
    PostFinancialAccountData,
    PostFinancialAccountError,
    PostFinancialAccountResponse,
    PostSessionsData,
    PostSnapshotsData,
    PostSubcategoriesData,
    PostTransactionsData,
    PostUsersData,
    PutAccountsByIdData,
    PutCategoriesByIdData,
    PutSessionsByIdData,
    PutSnapshotsByIdData,
    PutSubcategoriesByIdData,
    PutTransactionsByIdData,
    PutUserData,
    PutUserError,
    PutUserResponse,
    PutUsersByIdData
} from '../types.gen.js'

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string
        _infinite?: boolean
        tags?: ReadonlyArray<string>
    }
]

const createQueryKey = <TOptions extends Options>(
    id: string,
    options?: TOptions,
    infinite?: boolean,
    tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
    const params: QueryKey<TOptions>[0] = {
        _id: id,
        baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl
    } as QueryKey<TOptions>[0]
    if (infinite) {
        params._infinite = infinite
    }
    if (tags) {
        params.tags = tags
    }
    if (options?.body) {
        params.body = options.body
    }
    if (options?.headers) {
        params.headers = options.headers
    }
    if (options?.path) {
        params.path = options.path
    }
    if (options?.query) {
        params.query = options.query
    }
    return [params]
}

export const getRootStatusQueryKey = (options?: Options<GetRootStatusData>) => createQueryKey('getRootStatus', options)

/**
 * Healthcheck
 */
export const getRootStatusOptions = (options?: Options<GetRootStatusData>) =>
    queryOptions<
        GetRootStatusResponse,
        GetRootStatusError,
        GetRootStatusResponse,
        ReturnType<typeof getRootStatusQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getRootStatus({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getRootStatusQueryKey(options)
    })

export const getStatusQueryKey = (options?: Options<GetStatusData>) => createQueryKey('getStatus', options)

/**
 * Healthcheck
 */
export const getStatusOptions = (options?: Options<GetStatusData>) =>
    queryOptions<GetStatusResponse, GetStatusError, GetStatusResponse, ReturnType<typeof getStatusQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getStatus({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getStatusQueryKey(options)
    })

export const getUsersQueryKey = (options?: Options<GetUsersData>) => createQueryKey('getUsers', options)

/**
 * Get all users
 */
export const getUsersOptions = (options?: Options<GetUsersData>) =>
    queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getUsersQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUsers({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getUsersQueryKey(options)
    })

/**
 * Create user
 */
export const postUsersMutation = (
    options?: Partial<Options<PostUsersData>>
): UseMutationOptions<unknown, DefaultError, Options<PostUsersData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostUsersData>> = {
        mutationFn: async fnOptions => {
            const { data } = await postUsers({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Delete user
 */
export const deleteUsersByIdMutation = (
    options?: Partial<Options<DeleteUsersByIdData>>
): UseMutationOptions<DeleteUsersByIdResponse, DefaultError, Options<DeleteUsersByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteUsersByIdResponse, DefaultError, Options<DeleteUsersByIdData>> = {
        mutationFn: async fnOptions => {
            const { data } = await deleteUsersById({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getUsersByIdQueryKey = (options?: Options<GetUsersByIdData>) => createQueryKey('getUsersById', options)

/**
 * Get user by ID
 */
export const getUsersByIdOptions = (options?: Options<GetUsersByIdData>) =>
    queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getUsersByIdQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUsersById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getUsersByIdQueryKey(options)
    })

/**
 * Update user
 */
export const putUsersByIdMutation = (
    options?: Partial<Options<PutUsersByIdData>>
): UseMutationOptions<unknown, DefaultError, Options<PutUsersByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PutUsersByIdData>> = {
        mutationFn: async fnOptions => {
            const { data } = await putUsersById({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getTransactionsQueryKey = (options?: Options<GetTransactionsData>) =>
    createQueryKey('getTransactions', options)

/**
 * Get all transactions
 */
export const getTransactionsOptions = (options?: Options<GetTransactionsData>) =>
    queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getTransactionsQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getTransactions({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getTransactionsQueryKey(options)
    })

/**
 * Create transaction
 */
export const postTransactionsMutation = (
    options?: Partial<Options<PostTransactionsData>>
): UseMutationOptions<unknown, DefaultError, Options<PostTransactionsData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostTransactionsData>> = {
        mutationFn: async fnOptions => {
            const { data } = await postTransactions({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Delete transaction
 */
export const deleteTransactionsByIdMutation = (
    options?: Partial<Options<DeleteTransactionsByIdData>>
): UseMutationOptions<DeleteTransactionsByIdResponse, DefaultError, Options<DeleteTransactionsByIdData>> => {
    const mutationOptions: UseMutationOptions<
        DeleteTransactionsByIdResponse,
        DefaultError,
        Options<DeleteTransactionsByIdData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await deleteTransactionsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getTransactionsByIdQueryKey = (options?: Options<GetTransactionsByIdData>) =>
    createQueryKey('getTransactionsById', options)

/**
 * Get transaction by ID
 */
export const getTransactionsByIdOptions = (options?: Options<GetTransactionsByIdData>) =>
    queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getTransactionsByIdQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getTransactionsById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getTransactionsByIdQueryKey(options)
    })

/**
 * Update transaction
 */
export const putTransactionsByIdMutation = (
    options?: Partial<Options<PutTransactionsByIdData>>
): UseMutationOptions<unknown, DefaultError, Options<PutTransactionsByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PutTransactionsByIdData>> = {
        mutationFn: async fnOptions => {
            const { data } = await putTransactionsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getAccountsQueryKey = (options?: Options<GetAccountsData>) => createQueryKey('getAccounts', options)

/**
 * Get all accounts
 */
export const getAccountsOptions = (options?: Options<GetAccountsData>) =>
    queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getAccountsQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAccounts({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getAccountsQueryKey(options)
    })

/**
 * Create account
 */
export const postAccountsMutation = (
    options?: Partial<Options<PostAccountsData>>
): UseMutationOptions<unknown, DefaultError, Options<PostAccountsData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostAccountsData>> = {
        mutationFn: async fnOptions => {
            const { data } = await postAccounts({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Delete account
 */
export const deleteAccountsByIdMutation = (
    options?: Partial<Options<DeleteAccountsByIdData>>
): UseMutationOptions<DeleteAccountsByIdResponse, DefaultError, Options<DeleteAccountsByIdData>> => {
    const mutationOptions: UseMutationOptions<
        DeleteAccountsByIdResponse,
        DefaultError,
        Options<DeleteAccountsByIdData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await deleteAccountsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getAccountsByIdQueryKey = (options?: Options<GetAccountsByIdData>) =>
    createQueryKey('getAccountsById', options)

/**
 * Get account by ID
 */
export const getAccountsByIdOptions = (options?: Options<GetAccountsByIdData>) =>
    queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getAccountsByIdQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAccountsById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getAccountsByIdQueryKey(options)
    })

/**
 * Update account
 */
export const putAccountsByIdMutation = (
    options?: Partial<Options<PutAccountsByIdData>>
): UseMutationOptions<unknown, DefaultError, Options<PutAccountsByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PutAccountsByIdData>> = {
        mutationFn: async fnOptions => {
            const { data } = await putAccountsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getCategoriesQueryKey = (options?: Options<GetCategoriesData>) => createQueryKey('getCategories', options)

/**
 * Get all categories
 */
export const getCategoriesOptions = (options?: Options<GetCategoriesData>) =>
    queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getCategoriesQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCategories({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getCategoriesQueryKey(options)
    })

/**
 * Create category
 */
export const postCategoriesMutation = (
    options?: Partial<Options<PostCategoriesData>>
): UseMutationOptions<unknown, DefaultError, Options<PostCategoriesData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostCategoriesData>> = {
        mutationFn: async fnOptions => {
            const { data } = await postCategories({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Delete category
 */
export const deleteCategoriesByIdMutation = (
    options?: Partial<Options<DeleteCategoriesByIdData>>
): UseMutationOptions<DeleteCategoriesByIdResponse, DefaultError, Options<DeleteCategoriesByIdData>> => {
    const mutationOptions: UseMutationOptions<
        DeleteCategoriesByIdResponse,
        DefaultError,
        Options<DeleteCategoriesByIdData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await deleteCategoriesById({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getCategoriesByIdQueryKey = (options?: Options<GetCategoriesByIdData>) =>
    createQueryKey('getCategoriesById', options)

/**
 * Get category by ID
 */
export const getCategoriesByIdOptions = (options?: Options<GetCategoriesByIdData>) =>
    queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getCategoriesByIdQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCategoriesById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getCategoriesByIdQueryKey(options)
    })

/**
 * Update category
 */
export const putCategoriesByIdMutation = (
    options?: Partial<Options<PutCategoriesByIdData>>
): UseMutationOptions<unknown, DefaultError, Options<PutCategoriesByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PutCategoriesByIdData>> = {
        mutationFn: async fnOptions => {
            const { data } = await putCategoriesById({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getSubcategoriesQueryKey = (options?: Options<GetSubcategoriesData>) =>
    createQueryKey('getSubcategories', options)

/**
 * Get all subcategories
 */
export const getSubcategoriesOptions = (options?: Options<GetSubcategoriesData>) =>
    queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getSubcategoriesQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSubcategories({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getSubcategoriesQueryKey(options)
    })

/**
 * Create subcategory
 */
export const postSubcategoriesMutation = (
    options?: Partial<Options<PostSubcategoriesData>>
): UseMutationOptions<unknown, DefaultError, Options<PostSubcategoriesData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostSubcategoriesData>> = {
        mutationFn: async fnOptions => {
            const { data } = await postSubcategories({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Delete subcategory
 */
export const deleteSubcategoriesByIdMutation = (
    options?: Partial<Options<DeleteSubcategoriesByIdData>>
): UseMutationOptions<DeleteSubcategoriesByIdResponse, DefaultError, Options<DeleteSubcategoriesByIdData>> => {
    const mutationOptions: UseMutationOptions<
        DeleteSubcategoriesByIdResponse,
        DefaultError,
        Options<DeleteSubcategoriesByIdData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await deleteSubcategoriesById({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getSubcategoriesByIdQueryKey = (options?: Options<GetSubcategoriesByIdData>) =>
    createQueryKey('getSubcategoriesById', options)

/**
 * Get subcategory by ID
 */
export const getSubcategoriesByIdOptions = (options?: Options<GetSubcategoriesByIdData>) =>
    queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getSubcategoriesByIdQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSubcategoriesById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getSubcategoriesByIdQueryKey(options)
    })

/**
 * Update subcategory
 */
export const putSubcategoriesByIdMutation = (
    options?: Partial<Options<PutSubcategoriesByIdData>>
): UseMutationOptions<unknown, DefaultError, Options<PutSubcategoriesByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PutSubcategoriesByIdData>> = {
        mutationFn: async fnOptions => {
            const { data } = await putSubcategoriesById({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getSnapshotsQueryKey = (options?: Options<GetSnapshotsData>) => createQueryKey('getSnapshots', options)

/**
 * Get all snapshots
 */
export const getSnapshotsOptions = (options?: Options<GetSnapshotsData>) =>
    queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getSnapshotsQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSnapshots({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getSnapshotsQueryKey(options)
    })

/**
 * Create snapshot
 */
export const postSnapshotsMutation = (
    options?: Partial<Options<PostSnapshotsData>>
): UseMutationOptions<unknown, DefaultError, Options<PostSnapshotsData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostSnapshotsData>> = {
        mutationFn: async fnOptions => {
            const { data } = await postSnapshots({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Delete snapshot
 */
export const deleteSnapshotsByIdMutation = (
    options?: Partial<Options<DeleteSnapshotsByIdData>>
): UseMutationOptions<DeleteSnapshotsByIdResponse, DefaultError, Options<DeleteSnapshotsByIdData>> => {
    const mutationOptions: UseMutationOptions<
        DeleteSnapshotsByIdResponse,
        DefaultError,
        Options<DeleteSnapshotsByIdData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await deleteSnapshotsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getSnapshotsByIdQueryKey = (options?: Options<GetSnapshotsByIdData>) =>
    createQueryKey('getSnapshotsById', options)

/**
 * Get snapshot by ID
 */
export const getSnapshotsByIdOptions = (options?: Options<GetSnapshotsByIdData>) =>
    queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getSnapshotsByIdQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSnapshotsById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getSnapshotsByIdQueryKey(options)
    })

/**
 * Update snapshot
 */
export const putSnapshotsByIdMutation = (
    options?: Partial<Options<PutSnapshotsByIdData>>
): UseMutationOptions<unknown, DefaultError, Options<PutSnapshotsByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PutSnapshotsByIdData>> = {
        mutationFn: async fnOptions => {
            const { data } = await putSnapshotsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getSessionsQueryKey = (options?: Options<GetSessionsData>) => createQueryKey('getSessions', options)

/**
 * Get all sessions
 */
export const getSessionsOptions = (options?: Options<GetSessionsData>) =>
    queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getSessionsQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSessions({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getSessionsQueryKey(options)
    })

/**
 * Create session
 */
export const postSessionsMutation = (
    options?: Partial<Options<PostSessionsData>>
): UseMutationOptions<unknown, DefaultError, Options<PostSessionsData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostSessionsData>> = {
        mutationFn: async fnOptions => {
            const { data } = await postSessions({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Delete session
 */
export const deleteSessionsByIdMutation = (
    options?: Partial<Options<DeleteSessionsByIdData>>
): UseMutationOptions<DeleteSessionsByIdResponse, DefaultError, Options<DeleteSessionsByIdData>> => {
    const mutationOptions: UseMutationOptions<
        DeleteSessionsByIdResponse,
        DefaultError,
        Options<DeleteSessionsByIdData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await deleteSessionsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getSessionsByIdQueryKey = (options?: Options<GetSessionsByIdData>) =>
    createQueryKey('getSessionsById', options)

/**
 * Get session by ID
 */
export const getSessionsByIdOptions = (options?: Options<GetSessionsByIdData>) =>
    queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getSessionsByIdQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSessionsById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getSessionsByIdQueryKey(options)
    })

/**
 * Update session
 */
export const putSessionsByIdMutation = (
    options?: Partial<Options<PutSessionsByIdData>>
): UseMutationOptions<unknown, DefaultError, Options<PutSessionsByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PutSessionsByIdData>> = {
        mutationFn: async fnOptions => {
            const { data } = await putSessionsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getUserQueryKey = (options?: Options<GetUserData>) => createQueryKey('getUser', options)

/**
 * Get user
 *
 * Get user information and preferences
 */
export const getUserOptions = (options?: Options<GetUserData>) =>
    queryOptions<GetUserResponse, GetUserError, GetUserResponse, ReturnType<typeof getUserQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUser({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getUserQueryKey(options)
    })

/**
 * Update user
 *
 * Update user preferences and information
 */
export const putUserMutation = (
    options?: Partial<Options<PutUserData>>
): UseMutationOptions<PutUserResponse, PutUserError, Options<PutUserData>> => {
    const mutationOptions: UseMutationOptions<PutUserResponse, PutUserError, Options<PutUserData>> = {
        mutationFn: async fnOptions => {
            const { data } = await putUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getMeQueryKey = (options?: Options<GetMeData>) => createQueryKey('getMe', options)

/**
 * Get authenticated user
 *
 * Get authenticated user information and preferences
 */
export const getMeOptions = (options?: Options<GetMeData>) =>
    queryOptions<GetMeResponse, GetMeError, GetMeResponse, ReturnType<typeof getMeQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getMe({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getMeQueryKey(options)
    })

/**
 * Update authenticated user
 *
 * Updates the authenticated user's profile. Email changes require verification and may be subject to additional security checks.
 */
export const patchMeMutation = (
    options?: Partial<Options<PatchMeData>>
): UseMutationOptions<PatchMeResponse, PatchMeError, Options<PatchMeData>> => {
    const mutationOptions: UseMutationOptions<PatchMeResponse, PatchMeError, Options<PatchMeData>> = {
        mutationFn: async fnOptions => {
            const { data } = await patchMe({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getFinancialAccountQueryKey = (options?: Options<GetFinancialAccountData>) =>
    createQueryKey('getFinancialAccount', options)

/**
 * Get all financial accounts
 *
 * Retrieve a list of all financial accounts associated with the user
 */
export const getFinancialAccountOptions = (options?: Options<GetFinancialAccountData>) =>
    queryOptions<
        GetFinancialAccountResponse,
        GetFinancialAccountError,
        GetFinancialAccountResponse,
        ReturnType<typeof getFinancialAccountQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getFinancialAccount({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getFinancialAccountQueryKey(options)
    })

/**
 * Create financial account
 *
 * Create a new financial account with the provided data
 */
export const postFinancialAccountMutation = (
    options?: Partial<Options<PostFinancialAccountData>>
): UseMutationOptions<PostFinancialAccountResponse, PostFinancialAccountError, Options<PostFinancialAccountData>> => {
    const mutationOptions: UseMutationOptions<
        PostFinancialAccountResponse,
        PostFinancialAccountError,
        Options<PostFinancialAccountData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await postFinancialAccount({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getFinancialAccountsByIdQueryKey = (options: Options<GetFinancialAccountsByIdData>) =>
    createQueryKey('getFinancialAccountsById', options)

/**
 * Get financial account by ID
 *
 * Retrieve a specific financial account by its ID
 */
export const getFinancialAccountsByIdOptions = (options: Options<GetFinancialAccountsByIdData>) =>
    queryOptions<
        GetFinancialAccountsByIdResponse,
        GetFinancialAccountsByIdError,
        GetFinancialAccountsByIdResponse,
        ReturnType<typeof getFinancialAccountsByIdQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getFinancialAccountsById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getFinancialAccountsByIdQueryKey(options)
    })

/**
 * Delete financial account
 *
 * Delete an existing financial account with the provided ID
 */
export const deleteFinancialAccountByIdMutation = (
    options?: Partial<Options<DeleteFinancialAccountByIdData>>
): UseMutationOptions<
    DeleteFinancialAccountByIdResponse,
    DeleteFinancialAccountByIdError,
    Options<DeleteFinancialAccountByIdData>
> => {
    const mutationOptions: UseMutationOptions<
        DeleteFinancialAccountByIdResponse,
        DeleteFinancialAccountByIdError,
        Options<DeleteFinancialAccountByIdData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await deleteFinancialAccountById({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Update financial account
 *
 * Update an existing financial account with the provided data
 */
export const patchFinancialAccountByIdMutation = (
    options?: Partial<Options<PatchFinancialAccountByIdData>>
): UseMutationOptions<
    PatchFinancialAccountByIdResponse,
    PatchFinancialAccountByIdError,
    Options<PatchFinancialAccountByIdData>
> => {
    const mutationOptions: UseMutationOptions<
        PatchFinancialAccountByIdResponse,
        PatchFinancialAccountByIdError,
        Options<PatchFinancialAccountByIdData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await patchFinancialAccountById({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}
