// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query'

import { client } from '../client.gen.js'
import {
    completeImport,
    createCategory,
    createFinancialAccount,
    createImport,
    createSnapshotAccountBalance,
    createSubcategory,
    createSubscription,
    createTransaction,
    deleteCategories,
    deleteCategory,
    deleteFinancialAccount,
    deleteFinancialAccounts,
    deleteImport,
    deleteImports,
    deleteSubcategories,
    deleteSubcategory,
    deleteSubscription,
    deleteSubscriptions,
    deleteTransaction,
    deleteTransactions,
    getAuthenticatedUser,
    getCategories,
    getCategoryById,
    getDashboardLayout,
    getFinancialAccountById,
    getFinancialAccounts,
    getImportById,
    getImports,
    getRootStatus,
    getStatus,
    getSubcategories,
    getSubcategoryById,
    getSubscriptionById,
    getSubscriptions,
    getTransactionById,
    getTransactions,
    getTrendReport,
    type Options,
    updateAuthenticatedUser,
    updateCategory,
    updateDashboardLayout,
    updateFinancialAccount,
    updateImport,
    updateSubcategory,
    updateSubscription,
    updateTransaction
} from '../sdk.gen.js'
import type {
    CompleteImportData,
    CompleteImportError,
    CompleteImportResponse,
    CreateCategoryData,
    CreateCategoryError,
    CreateCategoryResponse2,
    CreateFinancialAccountData,
    CreateFinancialAccountError,
    CreateFinancialAccountResponse2,
    CreateImportData,
    CreateImportError,
    CreateImportResponse2,
    CreateSnapshotAccountBalanceData,
    CreateSnapshotAccountBalanceError,
    CreateSnapshotAccountBalanceResponse2,
    CreateSubcategoryData,
    CreateSubcategoryError,
    CreateSubcategoryResponse2,
    CreateSubscriptionData,
    CreateSubscriptionError,
    CreateSubscriptionResponse2,
    CreateTransactionData,
    CreateTransactionError,
    CreateTransactionResponse2,
    DeleteCategoriesData,
    DeleteCategoriesError,
    DeleteCategoriesResponse,
    DeleteCategoryData,
    DeleteCategoryError,
    DeleteCategoryResponse2,
    DeleteFinancialAccountData,
    DeleteFinancialAccountError,
    DeleteFinancialAccountResponse2,
    DeleteFinancialAccountsData,
    DeleteFinancialAccountsError,
    DeleteFinancialAccountsResponse,
    DeleteImportData,
    DeleteImportError,
    DeleteImportResponse2,
    DeleteImportsData,
    DeleteImportsError,
    DeleteImportsResponse,
    DeleteSubcategoriesData,
    DeleteSubcategoriesError,
    DeleteSubcategoriesResponse,
    DeleteSubcategoryData,
    DeleteSubcategoryError,
    DeleteSubcategoryResponse2,
    DeleteSubscriptionData,
    DeleteSubscriptionError,
    DeleteSubscriptionResponse2,
    DeleteSubscriptionsData,
    DeleteSubscriptionsError,
    DeleteSubscriptionsResponse,
    DeleteTransactionData,
    DeleteTransactionError,
    DeleteTransactionResponse2,
    DeleteTransactionsData,
    DeleteTransactionsError,
    DeleteTransactionsResponse,
    GetAuthenticatedUserData,
    GetAuthenticatedUserError,
    GetAuthenticatedUserResponse,
    GetCategoriesData,
    GetCategoriesError,
    GetCategoriesResponse,
    GetCategoryByIdData,
    GetCategoryByIdError,
    GetCategoryByIdResponse,
    GetDashboardLayoutData,
    GetDashboardLayoutError,
    GetDashboardLayoutResponse2,
    GetFinancialAccountByIdData,
    GetFinancialAccountByIdError,
    GetFinancialAccountByIdResponse,
    GetFinancialAccountsData,
    GetFinancialAccountsError,
    GetFinancialAccountsResponse,
    GetImportByIdData,
    GetImportByIdError,
    GetImportByIdResponse,
    GetImportsData,
    GetImportsError,
    GetImportsResponse,
    GetRootStatusData,
    GetRootStatusError,
    GetRootStatusResponse,
    GetStatusData,
    GetStatusError,
    GetStatusResponse,
    GetSubcategoriesData,
    GetSubcategoriesError,
    GetSubcategoriesResponse,
    GetSubcategoryByIdData,
    GetSubcategoryByIdError,
    GetSubcategoryByIdResponse,
    GetSubscriptionByIdData,
    GetSubscriptionByIdError,
    GetSubscriptionByIdResponse,
    GetSubscriptionsData,
    GetSubscriptionsError,
    GetSubscriptionsResponse,
    GetTransactionByIdData,
    GetTransactionByIdError,
    GetTransactionByIdResponse,
    GetTransactionsData,
    GetTransactionsError,
    GetTransactionsResponse,
    GetTrendReportData,
    GetTrendReportError,
    GetTrendReportResponse,
    UpdateAuthenticatedUserData,
    UpdateAuthenticatedUserError,
    UpdateAuthenticatedUserResponse,
    UpdateCategoryData,
    UpdateCategoryError,
    UpdateCategoryResponse2,
    UpdateDashboardLayoutData,
    UpdateDashboardLayoutError,
    UpdateDashboardLayoutResponse2,
    UpdateFinancialAccountData,
    UpdateFinancialAccountError,
    UpdateFinancialAccountResponse2,
    UpdateImportData,
    UpdateImportError,
    UpdateImportResponse2,
    UpdateSubcategoryData,
    UpdateSubcategoryError,
    UpdateSubcategoryResponse2,
    UpdateSubscriptionData,
    UpdateSubscriptionError,
    UpdateSubscriptionResponse2,
    UpdateTransactionData,
    UpdateTransactionError,
    UpdateTransactionResponse2
} from '../types.gen.js'

/**
 * Delete all categories
 *
 * Delete all categories associated with the user
 */
export const deleteCategoriesMutation = (
    options?: Partial<Options<DeleteCategoriesData>>
): UseMutationOptions<DeleteCategoriesResponse, DeleteCategoriesError, Options<DeleteCategoriesData>> => {
    const mutationOptions: UseMutationOptions<
        DeleteCategoriesResponse,
        DeleteCategoriesError,
        Options<DeleteCategoriesData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await deleteCategories({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string
        _infinite?: boolean
        tags?: ReadonlyArray<string>
    }
]

const createQueryKey = <TOptions extends Options>(
    id: string,
    options?: TOptions,
    infinite?: boolean,
    tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
    const params: QueryKey<TOptions>[0] = {
        _id: id,
        baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl
    } as QueryKey<TOptions>[0]
    if (infinite) {
        params._infinite = infinite
    }
    if (tags) {
        params.tags = tags
    }
    if (options?.body) {
        params.body = options.body
    }
    if (options?.headers) {
        params.headers = options.headers
    }
    if (options?.path) {
        params.path = options.path
    }
    if (options?.query) {
        params.query = options.query
    }
    return [params]
}

export const getCategoriesQueryKey = (options?: Options<GetCategoriesData>) => createQueryKey('getCategories', options)

/**
 * Get all categories
 *
 * Retrieve a list of all categories associated with the user
 */
export const getCategoriesOptions = (options?: Options<GetCategoriesData>) =>
    queryOptions<
        GetCategoriesResponse,
        GetCategoriesError,
        GetCategoriesResponse,
        ReturnType<typeof getCategoriesQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCategories({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getCategoriesQueryKey(options)
    })

/**
 * Create category
 *
 * Create a new category with the provided data
 */
export const createCategoryMutation = (
    options?: Partial<Options<CreateCategoryData>>
): UseMutationOptions<CreateCategoryResponse2, CreateCategoryError, Options<CreateCategoryData>> => {
    const mutationOptions: UseMutationOptions<
        CreateCategoryResponse2,
        CreateCategoryError,
        Options<CreateCategoryData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await createCategory({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Delete category
 *
 * Delete an existing category with the provided ID
 */
export const deleteCategoryMutation = (
    options?: Partial<Options<DeleteCategoryData>>
): UseMutationOptions<DeleteCategoryResponse2, DeleteCategoryError, Options<DeleteCategoryData>> => {
    const mutationOptions: UseMutationOptions<
        DeleteCategoryResponse2,
        DeleteCategoryError,
        Options<DeleteCategoryData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await deleteCategory({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getCategoryByIdQueryKey = (options: Options<GetCategoryByIdData>) =>
    createQueryKey('getCategoryById', options)

/**
 * Get category by ID
 *
 * Retrieve a specific category by its ID
 */
export const getCategoryByIdOptions = (options: Options<GetCategoryByIdData>) =>
    queryOptions<
        GetCategoryByIdResponse,
        GetCategoryByIdError,
        GetCategoryByIdResponse,
        ReturnType<typeof getCategoryByIdQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCategoryById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getCategoryByIdQueryKey(options)
    })

/**
 * Update category
 *
 * Update an existing category with the provided data
 */
export const updateCategoryMutation = (
    options?: Partial<Options<UpdateCategoryData>>
): UseMutationOptions<UpdateCategoryResponse2, UpdateCategoryError, Options<UpdateCategoryData>> => {
    const mutationOptions: UseMutationOptions<
        UpdateCategoryResponse2,
        UpdateCategoryError,
        Options<UpdateCategoryData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await updateCategory({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getDashboardLayoutQueryKey = (options?: Options<GetDashboardLayoutData>) =>
    createQueryKey('getDashboardLayout', options)

/**
 * Get dashboard layout
 *
 * Retrieve a specific dashboard layout
 */
export const getDashboardLayoutOptions = (options?: Options<GetDashboardLayoutData>) =>
    queryOptions<
        GetDashboardLayoutResponse2,
        GetDashboardLayoutError,
        GetDashboardLayoutResponse2,
        ReturnType<typeof getDashboardLayoutQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getDashboardLayout({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getDashboardLayoutQueryKey(options)
    })

/**
 * Update dashboard layout
 *
 * Update a specific dashboard layout
 */
export const updateDashboardLayoutMutation = (
    options?: Partial<Options<UpdateDashboardLayoutData>>
): UseMutationOptions<
    UpdateDashboardLayoutResponse2,
    UpdateDashboardLayoutError,
    Options<UpdateDashboardLayoutData>
> => {
    const mutationOptions: UseMutationOptions<
        UpdateDashboardLayoutResponse2,
        UpdateDashboardLayoutError,
        Options<UpdateDashboardLayoutData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await updateDashboardLayout({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Delete all financial accounts
 *
 * Delete all financial accounts associated with the user
 */
export const deleteFinancialAccountsMutation = (
    options?: Partial<Options<DeleteFinancialAccountsData>>
): UseMutationOptions<
    DeleteFinancialAccountsResponse,
    DeleteFinancialAccountsError,
    Options<DeleteFinancialAccountsData>
> => {
    const mutationOptions: UseMutationOptions<
        DeleteFinancialAccountsResponse,
        DeleteFinancialAccountsError,
        Options<DeleteFinancialAccountsData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await deleteFinancialAccounts({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getFinancialAccountsQueryKey = (options?: Options<GetFinancialAccountsData>) =>
    createQueryKey('getFinancialAccounts', options)

/**
 * Get all financial accounts
 *
 * Retrieve a list of all financial accounts associated with the user
 */
export const getFinancialAccountsOptions = (options?: Options<GetFinancialAccountsData>) =>
    queryOptions<
        GetFinancialAccountsResponse,
        GetFinancialAccountsError,
        GetFinancialAccountsResponse,
        ReturnType<typeof getFinancialAccountsQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getFinancialAccounts({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getFinancialAccountsQueryKey(options)
    })

/**
 * Create financial account
 *
 * Create a new financial account with the provided data
 */
export const createFinancialAccountMutation = (
    options?: Partial<Options<CreateFinancialAccountData>>
): UseMutationOptions<
    CreateFinancialAccountResponse2,
    CreateFinancialAccountError,
    Options<CreateFinancialAccountData>
> => {
    const mutationOptions: UseMutationOptions<
        CreateFinancialAccountResponse2,
        CreateFinancialAccountError,
        Options<CreateFinancialAccountData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await createFinancialAccount({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getFinancialAccountByIdQueryKey = (options: Options<GetFinancialAccountByIdData>) =>
    createQueryKey('getFinancialAccountById', options)

/**
 * Get financial account by ID
 *
 * Retrieve a specific financial account by its ID
 */
export const getFinancialAccountByIdOptions = (options: Options<GetFinancialAccountByIdData>) =>
    queryOptions<
        GetFinancialAccountByIdResponse,
        GetFinancialAccountByIdError,
        GetFinancialAccountByIdResponse,
        ReturnType<typeof getFinancialAccountByIdQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getFinancialAccountById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getFinancialAccountByIdQueryKey(options)
    })

/**
 * Delete financial account
 *
 * Delete an existing financial account with the provided ID
 */
export const deleteFinancialAccountMutation = (
    options?: Partial<Options<DeleteFinancialAccountData>>
): UseMutationOptions<
    DeleteFinancialAccountResponse2,
    DeleteFinancialAccountError,
    Options<DeleteFinancialAccountData>
> => {
    const mutationOptions: UseMutationOptions<
        DeleteFinancialAccountResponse2,
        DeleteFinancialAccountError,
        Options<DeleteFinancialAccountData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await deleteFinancialAccount({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Update financial account
 *
 * Update an existing financial account with the provided data
 */
export const updateFinancialAccountMutation = (
    options?: Partial<Options<UpdateFinancialAccountData>>
): UseMutationOptions<
    UpdateFinancialAccountResponse2,
    UpdateFinancialAccountError,
    Options<UpdateFinancialAccountData>
> => {
    const mutationOptions: UseMutationOptions<
        UpdateFinancialAccountResponse2,
        UpdateFinancialAccountError,
        Options<UpdateFinancialAccountData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await updateFinancialAccount({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Delete all imports
 *
 * Delete all imports associated with the user
 */
export const deleteImportsMutation = (
    options?: Partial<Options<DeleteImportsData>>
): UseMutationOptions<DeleteImportsResponse, DeleteImportsError, Options<DeleteImportsData>> => {
    const mutationOptions: UseMutationOptions<DeleteImportsResponse, DeleteImportsError, Options<DeleteImportsData>> = {
        mutationFn: async fnOptions => {
            const { data } = await deleteImports({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getImportsQueryKey = (options?: Options<GetImportsData>) => createQueryKey('getImports', options)

/**
 * Get all imports
 *
 * Retrieve a list of all imports associated with the user
 */
export const getImportsOptions = (options?: Options<GetImportsData>) =>
    queryOptions<GetImportsResponse, GetImportsError, GetImportsResponse, ReturnType<typeof getImportsQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getImports({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getImportsQueryKey(options)
    })

/**
 * Create import
 *
 * Create a new import with the provided data
 */
export const createImportMutation = (
    options?: Partial<Options<CreateImportData>>
): UseMutationOptions<CreateImportResponse2, CreateImportError, Options<CreateImportData>> => {
    const mutationOptions: UseMutationOptions<CreateImportResponse2, CreateImportError, Options<CreateImportData>> = {
        mutationFn: async fnOptions => {
            const { data } = await createImport({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Delete import
 *
 * Delete an existing import with the provided ID
 */
export const deleteImportMutation = (
    options?: Partial<Options<DeleteImportData>>
): UseMutationOptions<DeleteImportResponse2, DeleteImportError, Options<DeleteImportData>> => {
    const mutationOptions: UseMutationOptions<DeleteImportResponse2, DeleteImportError, Options<DeleteImportData>> = {
        mutationFn: async fnOptions => {
            const { data } = await deleteImport({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getImportByIdQueryKey = (options: Options<GetImportByIdData>) => createQueryKey('getImportById', options)

/**
 * Get import by ID
 *
 * Retrieve a specific import by its ID
 */
export const getImportByIdOptions = (options: Options<GetImportByIdData>) =>
    queryOptions<
        GetImportByIdResponse,
        GetImportByIdError,
        GetImportByIdResponse,
        ReturnType<typeof getImportByIdQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getImportById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getImportByIdQueryKey(options)
    })

/**
 * Update import
 *
 * Update an existing import with the provided data
 */
export const updateImportMutation = (
    options?: Partial<Options<UpdateImportData>>
): UseMutationOptions<UpdateImportResponse2, UpdateImportError, Options<UpdateImportData>> => {
    const mutationOptions: UseMutationOptions<UpdateImportResponse2, UpdateImportError, Options<UpdateImportData>> = {
        mutationFn: async fnOptions => {
            const { data } = await updateImport({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Complete import
 *
 * Mark an existing import as complete
 */
export const completeImportMutation = (
    options?: Partial<Options<CompleteImportData>>
): UseMutationOptions<CompleteImportResponse, CompleteImportError, Options<CompleteImportData>> => {
    const mutationOptions: UseMutationOptions<
        CompleteImportResponse,
        CompleteImportError,
        Options<CompleteImportData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await completeImport({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getTrendReportQueryKey = (options?: Options<GetTrendReportData>) =>
    createQueryKey('getTrendReport', options)

/**
 * Get trend report
 *
 * Retrieve a trend report based on the users imports
 */
export const getTrendReportOptions = (options?: Options<GetTrendReportData>) =>
    queryOptions<
        GetTrendReportResponse,
        GetTrendReportError,
        GetTrendReportResponse,
        ReturnType<typeof getTrendReportQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getTrendReport({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getTrendReportQueryKey(options)
    })

/**
 * Create snapshot account balance
 *
 * Create a new snapshot account balance with the provided data
 */
export const createSnapshotAccountBalanceMutation = (
    options?: Partial<Options<CreateSnapshotAccountBalanceData>>
): UseMutationOptions<
    CreateSnapshotAccountBalanceResponse2,
    CreateSnapshotAccountBalanceError,
    Options<CreateSnapshotAccountBalanceData>
> => {
    const mutationOptions: UseMutationOptions<
        CreateSnapshotAccountBalanceResponse2,
        CreateSnapshotAccountBalanceError,
        Options<CreateSnapshotAccountBalanceData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await createSnapshotAccountBalance({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getRootStatusQueryKey = (options?: Options<GetRootStatusData>) => createQueryKey('getRootStatus', options)

/**
 * Healthcheck
 */
export const getRootStatusOptions = (options?: Options<GetRootStatusData>) =>
    queryOptions<
        GetRootStatusResponse,
        GetRootStatusError,
        GetRootStatusResponse,
        ReturnType<typeof getRootStatusQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getRootStatus({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getRootStatusQueryKey(options)
    })

export const getStatusQueryKey = (options?: Options<GetStatusData>) => createQueryKey('getStatus', options)

/**
 * Healthcheck
 */
export const getStatusOptions = (options?: Options<GetStatusData>) =>
    queryOptions<GetStatusResponse, GetStatusError, GetStatusResponse, ReturnType<typeof getStatusQueryKey>>({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getStatus({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getStatusQueryKey(options)
    })

/**
 * Delete all subcategories
 *
 * Delete all subcategories associated with the user
 */
export const deleteSubcategoriesMutation = (
    options?: Partial<Options<DeleteSubcategoriesData>>
): UseMutationOptions<DeleteSubcategoriesResponse, DeleteSubcategoriesError, Options<DeleteSubcategoriesData>> => {
    const mutationOptions: UseMutationOptions<
        DeleteSubcategoriesResponse,
        DeleteSubcategoriesError,
        Options<DeleteSubcategoriesData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await deleteSubcategories({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getSubcategoriesQueryKey = (options?: Options<GetSubcategoriesData>) =>
    createQueryKey('getSubcategories', options)

/**
 * Get all subcategories
 *
 * Retrieve a list of all subcategories associated with the user
 */
export const getSubcategoriesOptions = (options?: Options<GetSubcategoriesData>) =>
    queryOptions<
        GetSubcategoriesResponse,
        GetSubcategoriesError,
        GetSubcategoriesResponse,
        ReturnType<typeof getSubcategoriesQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSubcategories({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getSubcategoriesQueryKey(options)
    })

/**
 * Create subcategory
 *
 * Create a new subcategory with the provided data
 */
export const createSubcategoryMutation = (
    options?: Partial<Options<CreateSubcategoryData>>
): UseMutationOptions<CreateSubcategoryResponse2, CreateSubcategoryError, Options<CreateSubcategoryData>> => {
    const mutationOptions: UseMutationOptions<
        CreateSubcategoryResponse2,
        CreateSubcategoryError,
        Options<CreateSubcategoryData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await createSubcategory({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Delete subcategory
 *
 * Delete an existing subcategory with the provided ID
 */
export const deleteSubcategoryMutation = (
    options?: Partial<Options<DeleteSubcategoryData>>
): UseMutationOptions<DeleteSubcategoryResponse2, DeleteSubcategoryError, Options<DeleteSubcategoryData>> => {
    const mutationOptions: UseMutationOptions<
        DeleteSubcategoryResponse2,
        DeleteSubcategoryError,
        Options<DeleteSubcategoryData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await deleteSubcategory({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getSubcategoryByIdQueryKey = (options: Options<GetSubcategoryByIdData>) =>
    createQueryKey('getSubcategoryById', options)

/**
 * Get subcategory by ID
 *
 * Retrieve a specific subcategory by its ID
 */
export const getSubcategoryByIdOptions = (options: Options<GetSubcategoryByIdData>) =>
    queryOptions<
        GetSubcategoryByIdResponse,
        GetSubcategoryByIdError,
        GetSubcategoryByIdResponse,
        ReturnType<typeof getSubcategoryByIdQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSubcategoryById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getSubcategoryByIdQueryKey(options)
    })

/**
 * Update subcategory
 *
 * Update an existing subcategory with the provided data
 */
export const updateSubcategoryMutation = (
    options?: Partial<Options<UpdateSubcategoryData>>
): UseMutationOptions<UpdateSubcategoryResponse2, UpdateSubcategoryError, Options<UpdateSubcategoryData>> => {
    const mutationOptions: UseMutationOptions<
        UpdateSubcategoryResponse2,
        UpdateSubcategoryError,
        Options<UpdateSubcategoryData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await updateSubcategory({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Delete all subscriptions
 *
 * Delete all subscriptions associated with the user
 */
export const deleteSubscriptionsMutation = (
    options?: Partial<Options<DeleteSubscriptionsData>>
): UseMutationOptions<DeleteSubscriptionsResponse, DeleteSubscriptionsError, Options<DeleteSubscriptionsData>> => {
    const mutationOptions: UseMutationOptions<
        DeleteSubscriptionsResponse,
        DeleteSubscriptionsError,
        Options<DeleteSubscriptionsData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await deleteSubscriptions({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getSubscriptionsQueryKey = (options?: Options<GetSubscriptionsData>) =>
    createQueryKey('getSubscriptions', options)

/**
 * Get all subscriptions
 *
 * Retrieve a list of all subscriptions associated with the user
 */
export const getSubscriptionsOptions = (options?: Options<GetSubscriptionsData>) =>
    queryOptions<
        GetSubscriptionsResponse,
        GetSubscriptionsError,
        GetSubscriptionsResponse,
        ReturnType<typeof getSubscriptionsQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSubscriptions({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getSubscriptionsQueryKey(options)
    })

/**
 * Create subscription
 *
 * Create a new subscription with the provided data
 */
export const createSubscriptionMutation = (
    options?: Partial<Options<CreateSubscriptionData>>
): UseMutationOptions<CreateSubscriptionResponse2, CreateSubscriptionError, Options<CreateSubscriptionData>> => {
    const mutationOptions: UseMutationOptions<
        CreateSubscriptionResponse2,
        CreateSubscriptionError,
        Options<CreateSubscriptionData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await createSubscription({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Delete subscription
 *
 * Delete an existing subscription with the provided ID
 */
export const deleteSubscriptionMutation = (
    options?: Partial<Options<DeleteSubscriptionData>>
): UseMutationOptions<DeleteSubscriptionResponse2, DeleteSubscriptionError, Options<DeleteSubscriptionData>> => {
    const mutationOptions: UseMutationOptions<
        DeleteSubscriptionResponse2,
        DeleteSubscriptionError,
        Options<DeleteSubscriptionData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await deleteSubscription({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getSubscriptionByIdQueryKey = (options: Options<GetSubscriptionByIdData>) =>
    createQueryKey('getSubscriptionById', options)

/**
 * Get subscription by ID
 *
 * Retrieve a specific subscription by its ID
 */
export const getSubscriptionByIdOptions = (options: Options<GetSubscriptionByIdData>) =>
    queryOptions<
        GetSubscriptionByIdResponse,
        GetSubscriptionByIdError,
        GetSubscriptionByIdResponse,
        ReturnType<typeof getSubscriptionByIdQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSubscriptionById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getSubscriptionByIdQueryKey(options)
    })

/**
 * Update subscription
 *
 * Update an existing subscription with the provided data
 */
export const updateSubscriptionMutation = (
    options?: Partial<Options<UpdateSubscriptionData>>
): UseMutationOptions<UpdateSubscriptionResponse2, UpdateSubscriptionError, Options<UpdateSubscriptionData>> => {
    const mutationOptions: UseMutationOptions<
        UpdateSubscriptionResponse2,
        UpdateSubscriptionError,
        Options<UpdateSubscriptionData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await updateSubscription({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Delete all transactions
 *
 * Delete all transactions associated with the user
 */
export const deleteTransactionsMutation = (
    options?: Partial<Options<DeleteTransactionsData>>
): UseMutationOptions<DeleteTransactionsResponse, DeleteTransactionsError, Options<DeleteTransactionsData>> => {
    const mutationOptions: UseMutationOptions<
        DeleteTransactionsResponse,
        DeleteTransactionsError,
        Options<DeleteTransactionsData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await deleteTransactions({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getTransactionsQueryKey = (options?: Options<GetTransactionsData>) =>
    createQueryKey('getTransactions', options)

/**
 * Get all transactions
 *
 * Retrieve a list of all transactions associated with the user
 */
export const getTransactionsOptions = (options?: Options<GetTransactionsData>) =>
    queryOptions<
        GetTransactionsResponse,
        GetTransactionsError,
        GetTransactionsResponse,
        ReturnType<typeof getTransactionsQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getTransactions({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getTransactionsQueryKey(options)
    })

/**
 * Create transaction
 *
 * Create a new transaction with the provided data
 */
export const createTransactionMutation = (
    options?: Partial<Options<CreateTransactionData>>
): UseMutationOptions<CreateTransactionResponse2, CreateTransactionError, Options<CreateTransactionData>> => {
    const mutationOptions: UseMutationOptions<
        CreateTransactionResponse2,
        CreateTransactionError,
        Options<CreateTransactionData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await createTransaction({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

/**
 * Delete transaction
 *
 * Delete an existing transaction with the provided ID
 */
export const deleteTransactionMutation = (
    options?: Partial<Options<DeleteTransactionData>>
): UseMutationOptions<DeleteTransactionResponse2, DeleteTransactionError, Options<DeleteTransactionData>> => {
    const mutationOptions: UseMutationOptions<
        DeleteTransactionResponse2,
        DeleteTransactionError,
        Options<DeleteTransactionData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await deleteTransaction({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getTransactionByIdQueryKey = (options: Options<GetTransactionByIdData>) =>
    createQueryKey('getTransactionById', options)

/**
 * Get transaction by ID
 *
 * Retrieve a specific transaction by its ID
 */
export const getTransactionByIdOptions = (options: Options<GetTransactionByIdData>) =>
    queryOptions<
        GetTransactionByIdResponse,
        GetTransactionByIdError,
        GetTransactionByIdResponse,
        ReturnType<typeof getTransactionByIdQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getTransactionById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getTransactionByIdQueryKey(options)
    })

/**
 * Update transaction
 *
 * Update an existing transaction with the provided data
 */
export const updateTransactionMutation = (
    options?: Partial<Options<UpdateTransactionData>>
): UseMutationOptions<UpdateTransactionResponse2, UpdateTransactionError, Options<UpdateTransactionData>> => {
    const mutationOptions: UseMutationOptions<
        UpdateTransactionResponse2,
        UpdateTransactionError,
        Options<UpdateTransactionData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await updateTransaction({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}

export const getAuthenticatedUserQueryKey = (options?: Options<GetAuthenticatedUserData>) =>
    createQueryKey('getAuthenticatedUser', options)

/**
 * Get authenticated user
 *
 * Get authenticated user information and preferences
 */
export const getAuthenticatedUserOptions = (options?: Options<GetAuthenticatedUserData>) =>
    queryOptions<
        GetAuthenticatedUserResponse,
        GetAuthenticatedUserError,
        GetAuthenticatedUserResponse,
        ReturnType<typeof getAuthenticatedUserQueryKey>
    >({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAuthenticatedUser({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            })
            return data
        },
        queryKey: getAuthenticatedUserQueryKey(options)
    })

/**
 * Update authenticated user
 *
 * Updates the authenticated user's profile. Email changes require verification and may be subject to additional security checks.
 */
export const updateAuthenticatedUserMutation = (
    options?: Partial<Options<UpdateAuthenticatedUserData>>
): UseMutationOptions<
    UpdateAuthenticatedUserResponse,
    UpdateAuthenticatedUserError,
    Options<UpdateAuthenticatedUserData>
> => {
    const mutationOptions: UseMutationOptions<
        UpdateAuthenticatedUserResponse,
        UpdateAuthenticatedUserError,
        Options<UpdateAuthenticatedUserData>
    > = {
        mutationFn: async fnOptions => {
            const { data } = await updateAuthenticatedUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            })
            return data
        }
    }
    return mutationOptions
}
