volumes:
    database-data:

networks:
    poveroh_network:
        external: true

services:
    db:
        container_name: db
        build:
            context: .
            dockerfile: ./packages/prisma/db.dockerfile
        restart: always
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - database-data:/var/lib/postgresql/data
        networks:
            - poveroh_network

    #Better if you comment out the studio service in production
    studio:
        container_name: studio
        build:
            context: .
            dockerfile: ./packages/prisma/studio.dockerfile
            args:
                DATABASE_URL: ${DATABASE_URL}
        restart: always
        env_file: .env
        environment:
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
        ports:
            - 5555:5555
        networks:
            - poveroh_network
        depends_on:
            - db

    api:
        container_name: api
        build:
            context: .
            dockerfile: ./apps/api/api.dockerfile
            args:
                API_PORT: ${API_PORT}
                JWT_KEY: ${JWT_KEY}
                DATABASE_URL: ${DATABASE_URL}
        restart: always
        env_file: .env
        environment:
            - API_PORT=${API_PORT}
            - JWT_KEY=${JWT_KEY}
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
            - CDN_DATA_PATH=${CDN_DATA_PATH}
        ports:
            - 3001:3001
        volumes:
            - ${CDN_DATA_PATH}:/usr/share/cdn-data
        networks:
            - poveroh_network
        depends_on:
            - db

    app:
        container_name: app
        build:
            context: .
            dockerfile: ./apps/app/app.dockerfile
            args:
                NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        restart: always
        env_file: .env
        environment:
            - NODE_ENV=production
            - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        ports:
            - 3000:3000
        networks:
            - poveroh_network
        depends_on:
            - api

    cdn:
        container_name: cdn
        build:
            context: .
            dockerfile: ./apps/cdn/cdn.dockerfile
        env_file: .env
        ports:
            - '3002:3002'
        volumes:
            - ${CDN_DATA_PATH}:/usr/share/cdn-data
        networks:
            - poveroh_network
