import { z } from '../zod'
import { TransactionActionEnum } from './enum.schema'
import { StringFilterSchema } from './filter.schema'
import { MultipartRequestSchema } from './media.schema'
import { SubcategorySchema } from './subcategory.schema'

/**
 * Category schema representing a transaction category in the system
 * It includes fields for category details such as title, description, associated transaction action, logo icon, color, and timestamps
 */
export const CategorySchema = z
    .object({
        id: z.string().uuid(),
        userId: z.string().uuid(),
        title: z.string(),
        description: z.string().optional(),
        for: TransactionActionEnum,
        logoIcon: z.string().url(),
        color: z.string().default('#8B5CF6'),
        subcategories: z.array(SubcategorySchema).optional(),
        createdAt: z.string().datetime(),
        updatedAt: z.string().datetime()
    })
    .openapi('Category')

/**
 * Category schema representing a transaction category in the system
 * It includes fields for category details such as title, description, associated transaction action, logo icon, color, and timestamps
 */
export const CreateCategoryRequestSchema = CategorySchema.omit({
    id: true,
    userId: true,
    createdAt: true,
    updatedAt: true
}).openapi('CreateCategoryRequest')

export const CreateCategoryMultipartRequestSchema = MultipartRequestSchema(CreateCategoryRequestSchema).openapi(
    'CreateCategoryMultipartRequest'
)

/**
 * Request schema for updating an existing category
 * It makes all fields optional to allow partial updates, while still omitting fields that are automatically generated by the system
 */
export const UpdateCategoryRequestSchema = CategorySchema.partial()
    .omit({
        id: true,
        userId: true,
        createdAt: true,
        updatedAt: true
    })
    .openapi('UpdateCategoryRequest')

/**
 * Response schema for category operations
 * It picks IDs for referencing specific categories in path parameters
 */
export const CategoryParamsId = CategorySchema.pick({
    id: true
}).openapi('CategoryParamsId')

/**
 * Category filters schema representing the structure of filters that can be applied when querying categories
 * It includes optional fields for filtering by ID, title, description, and type, allowing for flexible querying based on various criteria
 */
export const CategoryFiltersSchema = z
    .object({
        id: CategoryParamsId,
        title: StringFilterSchema.optional(),
        description: StringFilterSchema.optional(),
        for: CategorySchema.pick({ for: true }).optional()
    })
    .partial()
    .catchall(z.union([z.string(), StringFilterSchema]))
    .openapi('CategoryFilters')
