import { z } from '../zod'
import { FinancialAccountTypeEnum } from './enum.schema'
import { StringFilterSchema } from './filter.schema'
import { MultipartRequestSchema } from './media.schema'

/**
 * Financial account schema representing a user's financial account
 * Includes fields for account details such as title, description, balance, type, and timestamps
 */
export const FinancialAccountSchema = z
    .object({
        id: z.string().uuid(),
        userId: z.string().uuid(),
        title: z.string(),
        description: z.string(),
        balance: z.number(),
        type: FinancialAccountTypeEnum,
        logoIcon: z.string(),
        createdAt: z.string().datetime(),
        updatedAt: z.string().datetime()
    })
    .openapi('FinancialAccount')

/**
 * Request schema for creating a new financial account
 * It omits fields that are automatically generated by the system (id, userId, createdAt, updatedAt)
 */
export const CreateFinancialAccountRequestSchema = FinancialAccountSchema.omit({
    id: true,
    userId: true,
    createdAt: true,
    updatedAt: true
}).openapi('CreateFinancialAccountRequest')

export const CreateFinancialAccountMultipartRequestSchema = MultipartRequestSchema(
    CreateFinancialAccountRequestSchema
).openapi('CreateFinancialAccountMultipartRequest')

/**
 * Request schema for updating an existing financial account
 * It makes all fields optional to allow partial updates, while still omitting fields that are automatically generated by the system
 */
export const UpdateFinancialAccountRequestSchema = FinancialAccountSchema.partial()
    .omit({
        userId: true,
        createdAt: true,
        updatedAt: true
    })
    .openapi('UpdateFinancialAccountRequest')

/**
 * Response schema for financial account operations
 * It picks IDs for referencing specific financial accounts in path parameters
 */
export const FinancialAccountParamsId = FinancialAccountSchema.pick({
    id: true
}).openapi('FinancialAccountParamsId')

/**
 * Financial account filters schema representing the structure of filters that can be applied when querying financial accounts
 * It includes optional fields for filtering by ID, title, description, and type, allowing for flexible querying based on various criteria
 */
export const FinancialAccountFiltersSchema = z
    .object({
        id: FinancialAccountParamsId,
        title: StringFilterSchema.optional(),
        description: StringFilterSchema.optional(),
        type: FinancialAccountTypeEnum.optional()
    })
    .partial()
    .catchall(z.union([z.string(), StringFilterSchema, FinancialAccountTypeEnum]))
    .openapi('FinancialAccountFilters')
