import { z } from '../zod'
import { StringFilterSchema } from './filter.schema'
import { MultipartRequestSchema } from './media.schema'

/**
 * Subcategory schema representing a transaction subcategory in the system
 * It includes fields for subcategory details such as title, description, associated category, logo icon, and timestamps
 */
export const SubcategorySchema = z
    .object({
        id: z.string().uuid(),
        categoryId: z.string().uuid(),
        title: z.string(),
        description: z.string().optional(),
        logoIcon: z.string().url(),
        createdAt: z.string().datetime(),
        updatedAt: z.string().datetime()
    })
    .openapi('Subcategory')

/**
 * Category schema representing a transaction category in the system
 * It includes fields for category details such as title, description, associated transaction action, logo icon, color, and timestamps
 */
export const CreateSubcategoryRequestSchema = SubcategorySchema.omit({
    id: true,
    createdAt: true,
    updatedAt: true
}).openapi('CreateSubcategoryRequest')

export const CreateSubcategoryMultipartRequestSchema = MultipartRequestSchema(CreateSubcategoryRequestSchema).openapi(
    'CreateSubcategoryMultipartRequest'
)

/**
 * Request schema for updating an existing subcategory
 * It makes all fields optional to allow partial updates, while still omitting fields that are automatically generated by the system
 */
export const UpdateSubcategoryRequestSchema = SubcategorySchema.partial()
    .omit({
        id: true,
        categoryId: true,
        createdAt: true,
        updatedAt: true
    })
    .openapi('UpdateSubcategoryRequest')

/**
 * Response schema for subcategory operations
 * It picks IDs for referencing specific subcategories in path parameters
 */
export const SubcategoryParamsId = SubcategorySchema.pick({
    id: true
}).openapi('SubcategoryParamsId')

/**
 * Subcategory filters schema representing the structure of filters that can be applied when querying subcategories
 * It includes optional fields for filtering by ID, title, description, and type, allowing for flexible querying based on various criteria
 */
export const SubcategoryFiltersSchema = z
    .object({
        id: SubcategoryParamsId,
        title: StringFilterSchema.optional(),
        description: StringFilterSchema.optional(),
        categoryId: SubcategorySchema.pick({ categoryId: true }).optional()
    })
    .partial()
    .catchall(z.union([z.string(), StringFilterSchema]))
    .openapi('SubcategoryFilters')
