import { CreateFinancialAccountRequestSchema, DateFilterSchema, StringFilterSchema } from '../../schemas/src'
import { StringFilter } from '../../types/src/contracts'
import { z } from '../zod'
import { CurrencyEnum, TransactionActionEnum, TransactionStatusEnum } from './enum.schema'
import { MultipartRequestSchema } from './media.schema'

/**
 * Transaction media schema representing media files associated with a transaction
 * It includes fields for media details such as filename, filetype, path, and timestamps
 */
export const TransactionMediaSchema = z
    .object({
        id: z.string(),
        transactionId: z.string().uuid(),
        filename: z.string(),
        filetype: z.string(),
        path: z.string().url(),
        createdAt: z.string().datetime(),
        updatedAt: z.string().datetime()
    })
    .openapi('TransactionMedia')

/**
 * Create transaction media request schema representing the structure of a request to create a new transaction media
 * It omits fields that are automatically generated by the system (id, createdAt, updatedAt) and includes necessary fields for creating a new transaction media
 */
export const CreateTransactionMediaRequestSchema = TransactionMediaSchema.omit({
    id: true,
    createdAt: true,
    updatedAt: true
}).openapi('CreateTransactionMediaRequest')

export const CreateTransactionMediaMultipartRequestSchema = MultipartRequestSchema(
    CreateTransactionMediaRequestSchema
).openapi('CreateTransactionMediaMultipartRequest')

/**
 * Response schema for transaction media operations
 * It picks IDs for referencing specific transaction media in path parameters
 */
export const TransactionMediaParamsId = TransactionMediaSchema.pick({
    id: true
}).openapi('TransactionMediaParamsId')

/**
 * Transaction media filters schema representing the structure of filters that can be applied when querying transaction media
 * It includes optional fields for filtering by ID, transaction ID, and filetype, allowing for flexible querying based on various criteria
 */
export const TransactionMediaFiltersSchema = z
    .object({
        id: TransactionMediaParamsId,
        transactionId: z.string().uuid(),
        filetype: StringFilterSchema.optional()
    })
    .partial()
    .catchall(z.union([z.string(), StringFilterSchema]))
    .openapi('TransactionMediaFilters')

// ----------------------------------------------------------------------------------------------------------------------------

/**
 * Amount schema representing the amount details of a transaction
 * It includes fields for amount details such as amount, currency, action, associated financial account, and timestamps
 */
export const AmountSchema = z
    .object({
        id: z.string(),
        transactionId: z.string().uuid(),
        amount: z.number(),
        currency: CurrencyEnum,
        action: TransactionActionEnum,
        financialAccountId: z.string().uuid(),
        importReferenceId: z.string().nullable(),
        createdAt: z.string().datetime(),
        updatedAt: z.string().datetime()
    })
    .openapi('Amount')

/**
 * Create amount request schema representing the structure of a request to create a new amount
 * It omits fields that are automatically generated by the system (id, createdAt, updatedAt) and includes necessary fields for creating a new amount
 */
export const CreateAmountRequestSchema = AmountSchema.omit({
    id: true,
    createdAt: true,
    updatedAt: true
}).openapi('CreateAmountRequest')

/**
 * Response schema for amount operations
 * It picks IDs for referencing specific amounts in path parameters
 */
export const AmountParamsId = AmountSchema.pick({
    id: true
}).openapi('AmountParamsId')

// ----------------------------------------------------------------------------------------------------------------------------

/**
 * Transaction schema representing a financial transaction in the system
 * It includes fields for transaction details such as date, title, note, icon, category, status, and timestamps
 * It also includes nested schemas for associated media and amounts, allowing for a comprehensive representation of a transaction and its related data
 */
export const TransactionSchema = z
    .object({
        id: z.string(),
        userId: z.string(),
        date: z.string().datetime(),
        title: z.string(),
        note: z.string().nullable(),
        icon: z.string().nullable(),
        categoryId: z.string().nullable(),
        subcategoryId: z.string().nullable(),
        importId: z.string().nullable(),
        action: TransactionActionEnum,
        status: TransactionStatusEnum,
        ignore: z.boolean(),
        createdAt: z.string().datetime(),
        updatedAt: z.string().datetime(),
        media: z.array(TransactionMediaSchema),
        amounts: z.array(AmountSchema),
        transferId: z.string().nullable(),
        transferHash: z.string().nullable()
    })
    .openapi('Transaction')

/**
 * Create transaction request schema representing the structure of a request to create a new transaction
 * It omits fields that are automatically generated by the system (id, userId, createdAt, updatedAt) and includes necessary fields for creating a new transaction
 * It also omits fields that are related to the transaction's status and media, as these are typically handled separately after the initial transaction creation
 */
export const CreateTransactionRequestSchema = TransactionSchema.omit({
    id: true,
    userId: true,
    createdAt: true,
    status: true,
    importId: true,
    updatedAt: true,
    amounts: true,
    action: true,
    media: true,
    transferId: true,
    transferHash: true
}).openapi('CreateTransactionRequest')

export const CreateTransactionMultipartRequestSchema = MultipartRequestSchema(CreateTransactionRequestSchema).openapi(
    'CreateTransactionMultipartRequest'
)

/**
 * Request schema for updating an existing transaction
 * It makes all fields optional to allow partial updates, while still omitting fields that are automatically generated by the system
 */
export const UpdateTransactionRequestSchema = TransactionSchema.partial()
    .omit({
        id: true,
        userId: true,
        createdAt: true,
        status: true,
        importId: true,
        updatedAt: true,
        amounts: true,
        action: true,
        media: true,
        transferId: true,
        transferHash: true
    })
    .openapi('UpdateTransactionRequest')

/**
 * Response schema for transaction operations
 * It picks IDs for referencing specific transactions in path parameters
 */
export const TransactionParamsId = TransactionSchema.pick({
    id: true
}).openapi('TransactionParamsId')

/**
 * Transaction filters schema representing the structure of filters that can be applied when querying transactions
 * It includes optional fields for filtering by ID, title, description, and type, allowing for flexible querying based on various criteria
 */
export const TransactionFiltersSchema = z
    .object({
        id: TransactionParamsId,
        title: StringFilterSchema,
        note: StringFilterSchema,
        action: TransactionActionEnum,
        categoryId: z.string().uuid(),
        subcategoryId: z.string().uuid(),
        financialAccountId: z.string().uuid(),
        date: DateFilterSchema
    })
    .partial()
    .catchall(z.union([z.string(), StringFilterSchema, TransactionActionEnum]))
    .openapi('TransactionFilters')
