import { TimezoneEnum } from '../contracts'
import { Item } from './item'

export const TimezoneCatalog: Item<TimezoneEnum>[] = [
    { label: '(-12:00) International Date Line West', value: 'ETC_GMT_PLUS_12' },
    { label: '(-11:00) American Samoa', value: 'PACIFIC_PAGO_PAGO' },
    { label: '(-11:00) Midway Island', value: 'PACIFIC_MIDWAY' },
    { label: '(-10:00) Hawaii', value: 'PACIFIC_HONOLULU' },
    { label: '(-09:00) Alaska', value: 'AMERICA_JUNEAU' },
    { label: '(-08:00) Pacific Time', value: 'AMERICA_LOS_ANGELES' },
    { label: '(-08:00) Tijuana', value: 'AMERICA_TIJUANA' },
    { label: '(-07:00) Arizona', value: 'AMERICA_PHOENIX' },
    { label: '(-07:00) Mazatlan', value: 'AMERICA_MAZATLAN' },
    { label: '(-07:00) Mountain Time', value: 'AMERICA_DENVER' },
    { label: '(-06:00) Central America', value: 'AMERICA_GUATEMALA' },
    { label: '(-06:00) Central Time', value: 'AMERICA_CHICAGO' },
    { label: '(-06:00) Chihuahua', value: 'AMERICA_CHIHUAHUA' },
    { label: '(-06:00) Guadalajara', value: 'AMERICA_GUADALAJARA' },
    { label: '(-06:00) Mexico City', value: 'AMERICA_MEXICO_CITY' },
    { label: '(-06:00) Monterrey', value: 'AMERICA_MONTERREY' },
    { label: '(-06:00) Saskatchewan', value: 'AMERICA_REGINA' },
    { label: '(-05:00) Bogota', value: 'AMERICA_BOGOTA' },
    { label: '(-05:00) Eastern Time', value: 'AMERICA_NEW_YORK' },
    { label: '(-05:00) Indiana (East)', value: 'AMERICA_INDIANA_INDIANAPOLIS' },
    { label: '(-05:00) Lima', value: 'AMERICA_LIMA' },
    { label: '(-05:00) Quito', value: 'AMERICA_QUITO' },
    { label: '(-04:00) Atlantic Time (Canada)', value: 'AMERICA_HALIFAX' },
    { label: '(-04:00) Caracas', value: 'AMERICA_CARACAS' },
    { label: '(-04:00) Georgetown', value: 'AMERICA_GUYANA' },
    { label: '(-04:00) La Paz', value: 'AMERICA_LA_PAZ' },
    { label: '(-04:00) Puerto Rico', value: 'AMERICA_PUERTO_RICO' },
    { label: '(-04:00) Santiago', value: 'AMERICA_SANTIAGO' },
    { label: '(-03:30) Newfoundland', value: 'AMERICA_ST_JOHNS' },
    { label: '(-03:00) Brasilia', value: 'AMERICA_SAO_PAULO' },
    { label: '(-03:00) Buenos Aires', value: 'AMERICA_ARGENTINA_BUENOS_AIRES' },
    { label: '(-03:00) Montevideo', value: 'AMERICA_MONTEVIDEO' },
    { label: '(-02:00) Mid-Atlantic', value: 'ATLANTIC_SOUTH_GEORGIA' },
    { label: '(-01:00) Azores', value: 'ATLANTIC_AZORES' },
    { label: '(-01:00) Cape Verde Is.', value: 'ATLANTIC_CAPE_VERDE' },
    { label: '(+00:00) Edinburgh', value: 'EUROPE_EDINBURGH' },
    { label: '(+00:00) Lisbon', value: 'EUROPE_LISBON' },
    { label: '(+00:00) London', value: 'EUROPE_LONDON' },
    { label: '(+00:00) Monrovia', value: 'AFRICA_MONROVIA' },
    { label: '(+00:00) UTC', value: 'ETC_UTC' },
    { label: '(+01:00) Amsterdam', value: 'EUROPE_AMSTERDAM' },
    { label: '(+01:00) Belgrade', value: 'EUROPE_BELGRADE' },
    { label: '(+01:00) Bern', value: 'EUROPE_BERN' },
    { label: '(+01:00) Bratislava', value: 'EUROPE_BRATISLAVA' },
    { label: '(+01:00) Brussels', value: 'EUROPE_BRUSSELS' },
    { label: '(+01:00) Budapest', value: 'EUROPE_BUDAPEST' },
    { label: '(+01:00) Casablanca', value: 'AFRICA_CASABLANCA' },
    { label: '(+01:00) Copenhagen', value: 'EUROPE_COPENHAGEN' },
    { label: '(+01:00) Dublin', value: 'EUROPE_DUBLIN' },
    { label: '(+01:00) Ljubljana', value: 'EUROPE_LJUBLJANA' },
    { label: '(+01:00) Madrid', value: 'EUROPE_MADRID' },
    { label: '(+01:00) Paris', value: 'EUROPE_PARIS' },
    { label: '(+01:00) Prague', value: 'EUROPE_PRAGUE' },
    { label: '(+01:00) Rome', value: 'EUROPE_ROME' },
    { label: '(+01:00) Sarajevo', value: 'EUROPE_SARAJEVO' },
    { label: '(+01:00) Skopje', value: 'EUROPE_SKOPJE' },
    { label: '(+01:00) Stockholm', value: 'EUROPE_STOCKHOLM' },
    { label: '(+01:00) Vienna', value: 'EUROPE_VIENNA' },
    { label: '(+01:00) Warsaw', value: 'EUROPE_WARSAW' },
    { label: '(+01:00) West Central Africa', value: 'AFRICA_WEST_CENTRAL' },
    { label: '(+01:00) Zagreb', value: 'EUROPE_ZAGREB' },
    { label: '(+01:00) Zurich', value: 'EUROPE_ZURICH' },
    { label: '(+02:00) Athens', value: 'EUROPE_ATHENS' },
    { label: '(+02:00) Bucharest', value: 'EUROPE_BUCHAREST' },
    { label: '(+02:00) Cairo', value: 'AFRICA_CAIRO' },
    { label: '(+02:00) Harare', value: 'AFRICA_HARARE' },
    { label: '(+02:00) Helsinki', value: 'EUROPE_HELSINKI' },
    { label: '(+02:00) Jerusalem', value: 'ASIA_JERUSALEM' },
    { label: '(+02:00) Kaliningrad', value: 'EUROPE_KALININGRAD' },
    { label: '(+02:00) Pretoria', value: 'AFRICA_JOHANNESBURG' },
    { label: '(+02:00) Riga', value: 'EUROPE_RIGA' },
    { label: '(+02:00) Sofia', value: 'EUROPE_SOFIA' },
    { label: '(+02:00) Tallinn', value: 'EUROPE_TALLINN' },
    { label: '(+02:00) Vilnius', value: 'EUROPE_VILNIUS' },
    { label: '(+03:00) Baghdad', value: 'ASIA_BAGHDAD' },
    { label: '(+03:00) Istanbul', value: 'EUROPE_ISTANBUL' },
    { label: '(+03:00) Kuwait', value: 'ASIA_KUWAIT' },
    { label: '(+03:00) Minsk', value: 'EUROPE_MINSK' },
    { label: '(+03:00) Moscow', value: 'EUROPE_MOSCOW' },
    { label: '(+03:00) Nairobi', value: 'AFRICA_NAIROBI' },
    { label: '(+03:00) Riyadh', value: 'ASIA_RIYADH' },
    { label: '(+03:00) St. Petersburg', value: 'EUROPE_ST_PETERSBURG' },
    { label: '(+03:00) Volgograd', value: 'EUROPE_VOLGOGRAD' },
    { label: '(+03:30) Tehran', value: 'ASIA_TEHRAN' },
    { label: '(+04:00) Abu Dhabi', value: 'ASIA_ABU_DHABI' },
    { label: '(+04:00) Baku', value: 'ASIA_BAKU' },
    { label: '(+04:00) Muscat', value: 'ASIA_MUSCAT' },
    { label: '(+04:00) Samara', value: 'EUROPE_SAMARA' },
    { label: '(+04:00) Tbilisi', value: 'ASIA_TBILISI' },
    { label: '(+04:00) Yerevan', value: 'ASIA_YEREVAN' },
    { label: '(+04:30) Kabul', value: 'ASIA_KABUL' },
    { label: '(+05:00) Almaty', value: 'ASIA_ALMATY' },
    { label: '(+05:00) Astana', value: 'ASIA_ASTANA' },
    { label: '(+05:00) Ekaterinburg', value: 'ASIA_YEKATERINBURG' },
    { label: '(+05:00) Islamabad', value: 'ASIA_ISLAMABAD' },
    { label: '(+05:00) Karachi', value: 'ASIA_KARACHI' },
    { label: '(+05:00) Tashkent', value: 'ASIA_TASHKENT' },
    { label: '(+05:30) Chennai', value: 'ASIA_CHENNAI' },
    { label: '(+05:30) Kolkata', value: 'ASIA_KOLKATA' },
    { label: '(+05:30) Mumbai', value: 'ASIA_MUMBAI' },
    { label: '(+05:30) New Delhi', value: 'ASIA_NEW_DELHI' },
    { label: '(+05:30) Sri Jayawardenepura', value: 'ASIA_COLOMBO' },
    { label: '(+05:45) Kathmandu', value: 'ASIA_KATHMANDU' },
    { label: '(+06:00) Dhaka', value: 'ASIA_DHAKA' },
    { label: '(+06:00) Urumqi', value: 'ASIA_URUMQI' },
    { label: '(+07:00) Bangkok', value: 'ASIA_BANGKOK' },
    { label: '(+07:00) Hanoi', value: 'ASIA_HANOI' },
    { label: '(+07:00) Jakarta', value: 'ASIA_JAKARTA' },
    { label: '(+07:00) Krasnoyarsk', value: 'ASIA_KRASNOYARSK' },
    { label: '(+07:00) Novosibirsk', value: 'ASIA_NOVOSIBIRSK' },
    { label: '(+08:00) Beijing', value: 'ASIA_SHANGHAI' },
    { label: '(+08:00) Chongqing', value: 'ASIA_CHONGQING' },
    { label: '(+08:00) Hong Kong', value: 'ASIA_HONG_KONG' },
    { label: '(+08:00) Irkutsk', value: 'ASIA_IRKUTSK' },
    { label: '(+08:00) Kuala Lumpur', value: 'ASIA_KUALA_LUMPUR' },
    { label: '(+08:00) Perth', value: 'AUSTRALIA_PERTH' },
    { label: '(+08:00) Singapore', value: 'ASIA_SINGAPORE' },
    { label: '(+08:00) Taipei', value: 'ASIA_TAIPEI' },
    { label: '(+08:00) Ulaanbaatar', value: 'ASIA_ULAANBAATAR' },
    { label: '(+09:00) Osaka', value: 'ASIA_OSAKA' },
    { label: '(+09:00) Sapporo', value: 'ASIA_SAPPORO' },
    { label: '(+09:00) Seoul', value: 'ASIA_SEOUL' },
    { label: '(+09:00) Tokyo', value: 'ASIA_TOKYO' },
    { label: '(+09:00) Yakutsk', value: 'ASIA_YAKUTSK' },
    { label: '(+09:30) Adelaide', value: 'AUSTRALIA_ADELAIDE' },
    { label: '(+09:30) Darwin', value: 'AUSTRALIA_DARWIN' },
    { label: '(+10:00) Brisbane', value: 'AUSTRALIA_BRISBANE' },
    { label: '(+10:00) Canberra', value: 'AUSTRALIA_CANBERRA' },
    { label: '(+10:00) Guam', value: 'PACIFIC_GUAM' },
    { label: '(+10:00) Hobart', value: 'AUSTRALIA_HOBART' },
    { label: '(+10:00) Melbourne', value: 'AUSTRALIA_MELBOURNE' },
    { label: '(+10:00) Port Moresby', value: 'PACIFIC_PORT_MORESBY' },
    { label: '(+10:00) Sydney', value: 'AUSTRALIA_SYDNEY' },
    { label: '(+10:00) Vladivostok', value: 'ASIA_VLADIVOSTOK' },
    { label: '(+11:00) Magadan', value: 'ASIA_MAGADAN' },
    { label: '(+11:00) New Caledonia', value: 'PACIFIC_NOUMEA' },
    { label: '(+11:00) Solomon Is.', value: 'PACIFIC_GUADALCANAL' },
    { label: '(+11:00) Srednekolymsk', value: 'ASIA_SREDNEKOLYMSK' },
    { label: '(+12:00) Auckland', value: 'PACIFIC_AUCKLAND' },
    { label: '(+12:00) Fiji', value: 'PACIFIC_FIJI' },
    { label: '(+12:00) Kamchatka', value: 'ASIA_KAMCHATKA' },
    { label: '(+12:00) Marshall Is.', value: 'PACIFIC_MAJURO' },
    { label: '(+12:00) Wellington', value: 'PACIFIC_WELLINGTON' },
    { label: '(+12:45) Chatham Is.', value: 'PACIFIC_CHATHAM' },
    { label: "(+13:00) Nuku'alofa", value: 'PACIFIC_TONGATAPU' },
    { label: '(+13:00) Samoa', value: 'PACIFIC_APIA' },
    { label: '(+13:00) Tokelau Is.', value: 'PACIFIC_FAKAOFO' }
]
