import { IItem } from './item.js'

export enum Timezone {
    AFRICA_ALGIERS = 'AFRICA_ALGIERS',
    AFRICA_WEST_CENTRAL = 'AFRICA_WEST_CENTRAL',
    AFRICA_CAIRO = 'AFRICA_CAIRO',
    AFRICA_CASABLANCA = 'AFRICA_CASABLANCA',
    AFRICA_HARARE = 'AFRICA_HARARE',
    AFRICA_JOHANNESBURG = 'AFRICA_JOHANNESBURG',
    AFRICA_MONROVIA = 'AFRICA_MONROVIA',
    AFRICA_NAIROBI = 'AFRICA_NAIROBI',
    AMERICA_ARGENTINA_BUENOS_AIRES = 'AMERICA_ARGENTINA_BUENOS_AIRES',
    AMERICA_BOGOTA = 'AMERICA_BOGOTA',
    AMERICA_CARACAS = 'AMERICA_CARACAS',
    AMERICA_CHICAGO = 'AMERICA_CHICAGO',
    AMERICA_CHIHUAHUA = 'AMERICA_CHIHUAHUA',
    AMERICA_DENVER = 'AMERICA_DENVER',
    AMERICA_GUATEMALA = 'AMERICA_GUATEMALA',
    AMERICA_GUYANA = 'AMERICA_GUYANA',
    AMERICA_HALIFAX = 'AMERICA_HALIFAX',
    AMERICA_INDIANA_INDIANAPOLIS = 'AMERICA_INDIANA_INDIANAPOLIS',
    AMERICA_JUNEAU = 'AMERICA_JUNEAU',
    AMERICA_LA_PAZ = 'AMERICA_LA_PAZ',
    AMERICA_LIMA = 'AMERICA_LIMA',
    AMERICA_QUITO = 'AMERICA_QUITO',
    AMERICA_LOS_ANGELES = 'AMERICA_LOS_ANGELES',
    AMERICA_MAZATLAN = 'AMERICA_MAZATLAN',
    AMERICA_MEXICO_CITY = 'AMERICA_MEXICO_CITY',
    AMERICA_GUADALAJARA = 'AMERICA_GUADALAJARA',
    AMERICA_MONTERREY = 'AMERICA_MONTERREY',
    AMERICA_MONTEVIDEO = 'AMERICA_MONTEVIDEO',
    AMERICA_NEW_YORK = 'AMERICA_NEW_YORK',
    AMERICA_PHOENIX = 'AMERICA_PHOENIX',
    AMERICA_PUERTO_RICO = 'AMERICA_PUERTO_RICO',
    AMERICA_REGINA = 'AMERICA_REGINA',
    AMERICA_SANTIAGO = 'AMERICA_SANTIAGO',
    AMERICA_SAO_PAULO = 'AMERICA_SAO_PAULO',
    AMERICA_ST_JOHNS = 'AMERICA_ST_JOHNS',
    AMERICA_TIJUANA = 'AMERICA_TIJUANA',
    ASIA_ALMATY = 'ASIA_ALMATY',
    ASIA_ASTANA = 'ASIA_ASTANA',
    ASIA_BAGHDAD = 'ASIA_BAGHDAD',
    ASIA_BAKU = 'ASIA_BAKU',
    ASIA_BANGKOK = 'ASIA_BANGKOK',
    ASIA_HANOI = 'ASIA_HANOI',
    ASIA_CHONGQING = 'ASIA_CHONGQING',
    ASIA_COLOMBO = 'ASIA_COLOMBO',
    ASIA_DHAKA = 'ASIA_DHAKA',
    ASIA_HONG_KONG = 'ASIA_HONG_KONG',
    ASIA_IRKUTSK = 'ASIA_IRKUTSK',
    ASIA_JAKARTA = 'ASIA_JAKARTA',
    ASIA_JERUSALEM = 'ASIA_JERUSALEM',
    ASIA_KABUL = 'ASIA_KABUL',
    ASIA_KAMCHATKA = 'ASIA_KAMCHATKA',
    ASIA_KARACHI = 'ASIA_KARACHI',
    ASIA_ISLAMABAD = 'ASIA_ISLAMABAD',
    ASIA_KATHMANDU = 'ASIA_KATHMANDU',
    ASIA_KOLKATA = 'ASIA_KOLKATA',
    ASIA_CHENNAI = 'ASIA_CHENNAI',
    ASIA_MUMBAI = 'ASIA_MUMBAI',
    ASIA_NEW_DELHI = 'ASIA_NEW_DELHI',
    ASIA_KRASNOYARSK = 'ASIA_KRASNOYARSK',
    ASIA_KUALA_LUMPUR = 'ASIA_KUALA_LUMPUR',
    ASIA_KUWAIT = 'ASIA_KUWAIT',
    ASIA_MAGADAN = 'ASIA_MAGADAN',
    ASIA_MUSCAT = 'ASIA_MUSCAT',
    ASIA_ABU_DHABI = 'ASIA_ABU_DHABI',
    ASIA_NOVOSIBIRSK = 'ASIA_NOVOSIBIRSK',
    ASIA_RIYADH = 'ASIA_RIYADH',
    ASIA_SEOUL = 'ASIA_SEOUL',
    ASIA_SHANGHAI = 'ASIA_SHANGHAI',
    ASIA_SINGAPORE = 'ASIA_SINGAPORE',
    ASIA_SREDNEKOLYMSK = 'ASIA_SREDNEKOLYMSK',
    ASIA_TAIPEI = 'ASIA_TAIPEI',
    ASIA_TASHKENT = 'ASIA_TASHKENT',
    ASIA_TBILISI = 'ASIA_TBILISI',
    ASIA_TEHRAN = 'ASIA_TEHRAN',
    ASIA_TOKYO = 'ASIA_TOKYO',
    ASIA_OSAKA = 'ASIA_OSAKA',
    ASIA_SAPPORO = 'ASIA_SAPPORO',
    ASIA_ULAANBAATAR = 'ASIA_ULAANBAATAR',
    ASIA_URUMQI = 'ASIA_URUMQI',
    ASIA_VLADIVOSTOK = 'ASIA_VLADIVOSTOK',
    ASIA_YAKUTSK = 'ASIA_YAKUTSK',
    ASIA_YEKATERINBURG = 'ASIA_YEKATERINBURG',
    ASIA_YEREVAN = 'ASIA_YEREVAN',
    ATLANTIC_AZORES = 'ATLANTIC_AZORES',
    ATLANTIC_CAPE_VERDE = 'ATLANTIC_CAPE_VERDE',
    ATLANTIC_SOUTH_GEORGIA = 'ATLANTIC_SOUTH_GEORGIA',
    AUSTRALIA_ADELAIDE = 'AUSTRALIA_ADELAIDE',
    AUSTRALIA_BRISBANE = 'AUSTRALIA_BRISBANE',
    AUSTRALIA_CANBERRA = 'AUSTRALIA_CANBERRA',
    AUSTRALIA_DARWIN = 'AUSTRALIA_DARWIN',
    AUSTRALIA_HOBART = 'AUSTRALIA_HOBART',
    AUSTRALIA_MELBOURNE = 'AUSTRALIA_MELBOURNE',
    AUSTRALIA_PERTH = 'AUSTRALIA_PERTH',
    AUSTRALIA_SYDNEY = 'AUSTRALIA_SYDNEY',
    ETC_GMT_PLUS_12 = 'ETC_GMT_PLUS_12',
    ETC_UTC = 'ETC_UTC',
    EUROPE_AMSTERDAM = 'EUROPE_AMSTERDAM',
    EUROPE_ATHENS = 'EUROPE_ATHENS',
    EUROPE_BELGRADE = 'EUROPE_BELGRADE',
    EUROPE_BERN = 'EUROPE_BERN',
    EUROPE_BERLIN = 'EUROPE_BERLIN',
    EUROPE_BRATISLAVA = 'EUROPE_BRATISLAVA',
    EUROPE_BRUSSELS = 'EUROPE_BRUSSELS',
    EUROPE_BUCHAREST = 'EUROPE_BUCHAREST',
    EUROPE_BUDAPEST = 'EUROPE_BUDAPEST',
    EUROPE_COPENHAGEN = 'EUROPE_COPENHAGEN',
    EUROPE_DUBLIN = 'EUROPE_DUBLIN',
    EUROPE_HELSINKI = 'EUROPE_HELSINKI',
    EUROPE_ISTANBUL = 'EUROPE_ISTANBUL',
    EUROPE_KALININGRAD = 'EUROPE_KALININGRAD',
    EUROPE_LISBON = 'EUROPE_LISBON',
    EUROPE_LJUBLJANA = 'EUROPE_LJUBLJANA',
    EUROPE_LONDON = 'EUROPE_LONDON',
    EUROPE_EDINBURGH = 'EUROPE_EDINBURGH',
    EUROPE_MADRID = 'EUROPE_MADRID',
    EUROPE_MINSK = 'EUROPE_MINSK',
    EUROPE_MOSCOW = 'EUROPE_MOSCOW',
    EUROPE_ST_PETERSBURG = 'EUROPE_ST_PETERSBURG',
    EUROPE_PARIS = 'EUROPE_PARIS',
    EUROPE_PRAGUE = 'EUROPE_PRAGUE',
    EUROPE_RIGA = 'EUROPE_RIGA',
    EUROPE_ROME = 'EUROPE_ROME',
    EUROPE_SAMARA = 'EUROPE_SAMARA',
    EUROPE_SARAJEVO = 'EUROPE_SARAJEVO',
    EUROPE_SKOPJE = 'EUROPE_SKOPJE',
    EUROPE_SOFIA = 'EUROPE_SOFIA',
    EUROPE_STOCKHOLM = 'EUROPE_STOCKHOLM',
    EUROPE_TALLINN = 'EUROPE_TALLINN',
    EUROPE_VIENNA = 'EUROPE_VIENNA',
    EUROPE_VILNIUS = 'EUROPE_VILNIUS',
    EUROPE_VOLGOGRAD = 'EUROPE_VOLGOGRAD',
    EUROPE_WARSAW = 'EUROPE_WARSAW',
    EUROPE_ZAGREB = 'EUROPE_ZAGREB',
    EUROPE_ZURICH = 'EUROPE_ZURICH',
    PACIFIC_APIA = 'PACIFIC_APIA',
    PACIFIC_AUCKLAND = 'PACIFIC_AUCKLAND',
    PACIFIC_WELLINGTON = 'PACIFIC_WELLINGTON',
    PACIFIC_CHATHAM = 'PACIFIC_CHATHAM',
    PACIFIC_FAKAOFO = 'PACIFIC_FAKAOFO',
    PACIFIC_FIJI = 'PACIFIC_FIJI',
    PACIFIC_GUADALCANAL = 'PACIFIC_GUADALCANAL',
    PACIFIC_GUAM = 'PACIFIC_GUAM',
    PACIFIC_HONOLULU = 'PACIFIC_HONOLULU',
    PACIFIC_MAJURO = 'PACIFIC_MAJURO',
    PACIFIC_MIDWAY = 'PACIFIC_MIDWAY',
    PACIFIC_NOUMEA = 'PACIFIC_NOUMEA',
    PACIFIC_PAGO_PAGO = 'PACIFIC_PAGO_PAGO',
    PACIFIC_PORT_MORESBY = 'PACIFIC_PORT_MORESBY',
    PACIFIC_TONGATAPU = 'PACIFIC_TONGATAPU'
}

export const timezoneCatalog: IItem[] = [
    { label: '(-12:00) International Date Line West', value: Timezone.ETC_GMT_PLUS_12 },
    { label: '(-11:00) American Samoa', value: Timezone.PACIFIC_PAGO_PAGO },
    { label: '(-11:00) Midway Island', value: Timezone.PACIFIC_MIDWAY },
    { label: '(-10:00) Hawaii', value: Timezone.PACIFIC_HONOLULU },
    { label: '(-09:00) Alaska', value: Timezone.AMERICA_JUNEAU },
    { label: '(-08:00) Pacific Time', value: Timezone.AMERICA_LOS_ANGELES },
    { label: '(-08:00) Tijuana', value: Timezone.AMERICA_TIJUANA },
    { label: '(-07:00) Arizona', value: Timezone.AMERICA_PHOENIX },
    { label: '(-07:00) Mazatlan', value: Timezone.AMERICA_MAZATLAN },
    { label: '(-07:00) Mountain Time', value: Timezone.AMERICA_DENVER },
    { label: '(-06:00) Central America', value: Timezone.AMERICA_GUATEMALA },
    { label: '(-06:00) Central Time', value: Timezone.AMERICA_CHICAGO },
    { label: '(-06:00) Chihuahua', value: Timezone.AMERICA_CHIHUAHUA },
    { label: '(-06:00) Guadalajara', value: Timezone.AMERICA_GUADALAJARA },
    { label: '(-06:00) Mexico City', value: Timezone.AMERICA_MEXICO_CITY },
    { label: '(-06:00) Monterrey', value: Timezone.AMERICA_MONTERREY },
    { label: '(-06:00) Saskatchewan', value: Timezone.AMERICA_REGINA },
    { label: '(-05:00) Bogota', value: Timezone.AMERICA_BOGOTA },
    { label: '(-05:00) Eastern Time', value: Timezone.AMERICA_NEW_YORK },
    { label: '(-05:00) Indiana (East)', value: Timezone.AMERICA_INDIANA_INDIANAPOLIS },
    { label: '(-05:00) Lima', value: Timezone.AMERICA_LIMA },
    { label: '(-05:00) Quito', value: Timezone.AMERICA_QUITO },
    { label: '(-04:00) Atlantic Time (Canada)', value: Timezone.AMERICA_HALIFAX },
    { label: '(-04:00) Caracas', value: Timezone.AMERICA_CARACAS },
    { label: '(-04:00) Georgetown', value: Timezone.AMERICA_GUYANA },
    { label: '(-04:00) La Paz', value: Timezone.AMERICA_LA_PAZ },
    { label: '(-04:00) Puerto Rico', value: Timezone.AMERICA_PUERTO_RICO },
    { label: '(-04:00) Santiago', value: Timezone.AMERICA_SANTIAGO },
    { label: '(-03:30) Newfoundland', value: Timezone.AMERICA_ST_JOHNS },
    { label: '(-03:00) Brasilia', value: Timezone.AMERICA_SAO_PAULO },
    { label: '(-03:00) Buenos Aires', value: Timezone.AMERICA_ARGENTINA_BUENOS_AIRES },
    { label: '(-03:00) Montevideo', value: Timezone.AMERICA_MONTEVIDEO },
    { label: '(-02:00) Mid-Atlantic', value: Timezone.ATLANTIC_SOUTH_GEORGIA },
    { label: '(-01:00) Azores', value: Timezone.ATLANTIC_AZORES },
    { label: '(-01:00) Cape Verde Is.', value: Timezone.ATLANTIC_CAPE_VERDE },
    { label: '(+00:00) Edinburgh', value: Timezone.EUROPE_EDINBURGH },
    { label: '(+00:00) Lisbon', value: Timezone.EUROPE_LISBON },
    { label: '(+00:00) London', value: Timezone.EUROPE_LONDON },
    { label: '(+00:00) Monrovia', value: Timezone.AFRICA_MONROVIA },
    { label: '(+00:00) UTC', value: Timezone.ETC_UTC },
    { label: '(+01:00) Amsterdam', value: Timezone.EUROPE_AMSTERDAM },
    { label: '(+01:00) Belgrade', value: Timezone.EUROPE_BELGRADE },
    { label: '(+01:00) Bern', value: Timezone.EUROPE_BERN },
    { label: '(+01:00) Bratislava', value: Timezone.EUROPE_BRATISLAVA },
    { label: '(+01:00) Brussels', value: Timezone.EUROPE_BRUSSELS },
    { label: '(+01:00) Budapest', value: Timezone.EUROPE_BUDAPEST },
    { label: '(+01:00) Casablanca', value: Timezone.AFRICA_CASABLANCA },
    { label: '(+01:00) Copenhagen', value: Timezone.EUROPE_COPENHAGEN },
    { label: '(+01:00) Dublin', value: Timezone.EUROPE_DUBLIN },
    { label: '(+01:00) Ljubljana', value: Timezone.EUROPE_LJUBLJANA },
    { label: '(+01:00) Madrid', value: Timezone.EUROPE_MADRID },
    { label: '(+01:00) Paris', value: Timezone.EUROPE_PARIS },
    { label: '(+01:00) Prague', value: Timezone.EUROPE_PRAGUE },
    { label: '(+01:00) Rome', value: Timezone.EUROPE_ROME },
    { label: '(+01:00) Sarajevo', value: Timezone.EUROPE_SARAJEVO },
    { label: '(+01:00) Skopje', value: Timezone.EUROPE_SKOPJE },
    { label: '(+01:00) Stockholm', value: Timezone.EUROPE_STOCKHOLM },
    { label: '(+01:00) Vienna', value: Timezone.EUROPE_VIENNA },
    { label: '(+01:00) Warsaw', value: Timezone.EUROPE_WARSAW },
    { label: '(+01:00) West Central Africa', value: Timezone.AFRICA_WEST_CENTRAL },
    { label: '(+01:00) Zagreb', value: Timezone.EUROPE_ZAGREB },
    { label: '(+01:00) Zurich', value: Timezone.EUROPE_ZURICH },
    { label: '(+02:00) Athens', value: Timezone.EUROPE_ATHENS },
    { label: '(+02:00) Bucharest', value: Timezone.EUROPE_BUCHAREST },
    { label: '(+02:00) Cairo', value: Timezone.AFRICA_CAIRO },
    { label: '(+02:00) Harare', value: Timezone.AFRICA_HARARE },
    { label: '(+02:00) Helsinki', value: Timezone.EUROPE_HELSINKI },
    { label: '(+02:00) Jerusalem', value: Timezone.ASIA_JERUSALEM },
    { label: '(+02:00) Kaliningrad', value: Timezone.EUROPE_KALININGRAD },
    { label: '(+02:00) Pretoria', value: Timezone.AFRICA_JOHANNESBURG },
    { label: '(+02:00) Riga', value: Timezone.EUROPE_RIGA },
    { label: '(+02:00) Sofia', value: Timezone.EUROPE_SOFIA },
    { label: '(+02:00) Tallinn', value: Timezone.EUROPE_TALLINN },
    { label: '(+02:00) Vilnius', value: Timezone.EUROPE_VILNIUS },
    { label: '(+03:00) Baghdad', value: Timezone.ASIA_BAGHDAD },
    { label: '(+03:00) Istanbul', value: Timezone.EUROPE_ISTANBUL },
    { label: '(+03:00) Kuwait', value: Timezone.ASIA_KUWAIT },
    { label: '(+03:00) Minsk', value: Timezone.EUROPE_MINSK },
    { label: '(+03:00) Moscow', value: Timezone.EUROPE_MOSCOW },
    { label: '(+03:00) Nairobi', value: Timezone.AFRICA_NAIROBI },
    { label: '(+03:00) Riyadh', value: Timezone.ASIA_RIYADH },
    { label: '(+03:00) St. Petersburg', value: Timezone.EUROPE_ST_PETERSBURG },
    { label: '(+03:00) Volgograd', value: Timezone.EUROPE_VOLGOGRAD },
    { label: '(+03:30) Tehran', value: Timezone.ASIA_TEHRAN },
    { label: '(+04:00) Abu Dhabi', value: Timezone.ASIA_ABU_DHABI },
    { label: '(+04:00) Baku', value: Timezone.ASIA_BAKU },
    { label: '(+04:00) Muscat', value: Timezone.ASIA_MUSCAT },
    { label: '(+04:00) Samara', value: Timezone.EUROPE_SAMARA },
    { label: '(+04:00) Tbilisi', value: Timezone.ASIA_TBILISI },
    { label: '(+04:00) Yerevan', value: Timezone.ASIA_YEREVAN },
    { label: '(+04:30) Kabul', value: Timezone.ASIA_KABUL },
    { label: '(+05:00) Almaty', value: Timezone.ASIA_ALMATY },
    { label: '(+05:00) Astana', value: Timezone.ASIA_ASTANA },
    { label: '(+05:00) Ekaterinburg', value: Timezone.ASIA_YEKATERINBURG },
    { label: '(+05:00) Islamabad', value: Timezone.ASIA_ISLAMABAD },
    { label: '(+05:00) Karachi', value: Timezone.ASIA_KARACHI },
    { label: '(+05:00) Tashkent', value: Timezone.ASIA_TASHKENT },
    { label: '(+05:30) Chennai', value: Timezone.ASIA_CHENNAI },
    { label: '(+05:30) Kolkata', value: Timezone.ASIA_KOLKATA },
    { label: '(+05:30) Mumbai', value: Timezone.ASIA_MUMBAI },
    { label: '(+05:30) New Delhi', value: Timezone.ASIA_NEW_DELHI },
    { label: '(+05:30) Sri Jayawardenepura', value: Timezone.ASIA_COLOMBO },
    { label: '(+05:45) Kathmandu', value: Timezone.ASIA_KATHMANDU },
    { label: '(+06:00) Dhaka', value: Timezone.ASIA_DHAKA },
    { label: '(+06:00) Urumqi', value: Timezone.ASIA_URUMQI },
    { label: '(+07:00) Bangkok', value: Timezone.ASIA_BANGKOK },
    { label: '(+07:00) Hanoi', value: Timezone.ASIA_HANOI },
    { label: '(+07:00) Jakarta', value: Timezone.ASIA_JAKARTA },
    { label: '(+07:00) Krasnoyarsk', value: Timezone.ASIA_KRASNOYARSK },
    { label: '(+07:00) Novosibirsk', value: Timezone.ASIA_NOVOSIBIRSK },
    { label: '(+08:00) Beijing', value: Timezone.ASIA_SHANGHAI },
    { label: '(+08:00) Chongqing', value: Timezone.ASIA_CHONGQING },
    { label: '(+08:00) Hong Kong', value: Timezone.ASIA_HONG_KONG },
    { label: '(+08:00) Irkutsk', value: Timezone.ASIA_IRKUTSK },
    { label: '(+08:00) Kuala Lumpur', value: Timezone.ASIA_KUALA_LUMPUR },
    { label: '(+08:00) Perth', value: Timezone.AUSTRALIA_PERTH },
    { label: '(+08:00) Singapore', value: Timezone.ASIA_SINGAPORE },
    { label: '(+08:00) Taipei', value: Timezone.ASIA_TAIPEI },
    { label: '(+08:00) Ulaanbaatar', value: Timezone.ASIA_ULAANBAATAR },
    { label: '(+09:00) Osaka', value: Timezone.ASIA_OSAKA },
    { label: '(+09:00) Sapporo', value: Timezone.ASIA_SAPPORO },
    { label: '(+09:00) Seoul', value: Timezone.ASIA_SEOUL },
    { label: '(+09:00) Tokyo', value: Timezone.ASIA_TOKYO },
    { label: '(+09:00) Yakutsk', value: Timezone.ASIA_YAKUTSK },
    { label: '(+09:30) Adelaide', value: Timezone.AUSTRALIA_ADELAIDE },
    { label: '(+09:30) Darwin', value: Timezone.AUSTRALIA_DARWIN },
    { label: '(+10:00) Brisbane', value: Timezone.AUSTRALIA_BRISBANE },
    { label: '(+10:00) Canberra', value: Timezone.AUSTRALIA_CANBERRA },
    { label: '(+10:00) Guam', value: Timezone.PACIFIC_GUAM },
    { label: '(+10:00) Hobart', value: Timezone.AUSTRALIA_HOBART },
    { label: '(+10:00) Melbourne', value: Timezone.AUSTRALIA_MELBOURNE },
    { label: '(+10:00) Port Moresby', value: Timezone.PACIFIC_PORT_MORESBY },
    { label: '(+10:00) Sydney', value: Timezone.AUSTRALIA_SYDNEY },
    { label: '(+10:00) Vladivostok', value: Timezone.ASIA_VLADIVOSTOK },
    { label: '(+11:00) Magadan', value: Timezone.ASIA_MAGADAN },
    { label: '(+11:00) New Caledonia', value: Timezone.PACIFIC_NOUMEA },
    { label: '(+11:00) Solomon Is.', value: Timezone.PACIFIC_GUADALCANAL },
    { label: '(+11:00) Srednekolymsk', value: Timezone.ASIA_SREDNEKOLYMSK },
    { label: '(+12:00) Auckland', value: Timezone.PACIFIC_AUCKLAND },
    { label: '(+12:00) Fiji', value: Timezone.PACIFIC_FIJI },
    { label: '(+12:00) Kamchatka', value: Timezone.ASIA_KAMCHATKA },
    { label: '(+12:00) Marshall Is.', value: Timezone.PACIFIC_MAJURO },
    { label: '(+12:00) Wellington', value: Timezone.PACIFIC_WELLINGTON },
    { label: '(+12:45) Chatham Is.', value: Timezone.PACIFIC_CHATHAM },
    { label: "(+13:00) Nuku'alofa", value: Timezone.PACIFIC_TONGATAPU },
    { label: '(+13:00) Samoa', value: Timezone.PACIFIC_APIA },
    { label: '(+13:00) Tokelau Is.', value: Timezone.PACIFIC_FAKAOFO }
]
