name: Bug report
description: Create a bug report to help us improve Poveroh 
title: "[bug]: "
labels: [🐛bug]
assignees: []
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to fill out this bug report.
- type: textarea
  attributes:
    label: Current behavior
    description: A concise description of what you're experiencing and what you expect
    placeholder: |
      A summary of the issue. 
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Add steps to reproduce this behaviour, include console or network logs and screenshots
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
- type: dropdown
  id: env
  attributes:
    label: Environment
    options:
      - Production
      - Preview
  validations:
    required: true
- type: dropdown
  id: browser
  attributes:
    label: Browser
    options:
      - Google Chrome
      - Mozilla Firefox
      - Safari
      - Other
- type: dropdown
  id: variant
  attributes:
    label: Variant
    options:
      - Cloud
      - Self-hosted (docker)
      - Local
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: Version
    placeholder: v1.0.0
  validations:
    required: true
