name: Build and Push Docker Images

on:
    push:
        branches: [main]

env:
    REGISTRY: ghcr.io
    IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
    build-and-push:
        name: Build & Push Docker Images
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set lowercase repo and owner
              id: vars
              run: |
                  echo "owner_lower=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
                  echo "repo_lower=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Copy and patch .env
              run: |
                  cp .env.example .env

            - name: Build Docker images using local compose file
              run: cd ./docker && docker compose -f docker-compose.local.yml build

            - name: Tag and push images
              run: |
                  for service in db studio api app cdn; do
                    docker tag ${{ steps.vars.outputs.repo_lower }}-$service ghcr.io/${{ steps.vars.outputs.owner_lower }}/${{ steps.vars.outputs.repo_lower }}-$service:latest
                    docker push ghcr.io/${{ steps.vars.outputs.owner_lower }}/${{ steps.vars.outputs.repo_lower }}-$service:latest
                  done
